-- QUERY SALDOS A RECEBER ATE O ULTIMO DIA DO MES -- FINANCEIRO
SELECT * 
FROM SE1010 
WHERE E1_SALDO > 0 
AND E1_VENCREA >= '20230326' -- COLOCAR DDATABASE PARA CONSIDERAR O QUE VENCERÁ PARA FRENTE
AND E1_VENCREA <= '20230331' -- COLOCAR VARIAVEL PARA CONSIDERAR O ULTIMO DIA DO MES CORRENTE
AND SE1010.D_E_L_E_T_ =''