-- QUERY SALDOS A PAGAR ATE O ULTIMO DIA DO MES -- FINANCEIRO
SELECT * 
FROM SE2010 
WHERE E2_SALDO > 0 
AND E2_VENCREA >= '20230326' -- COLOCAR DDATABASE PARA CONSIDERAR O QUE VENCERÁ PARA FRENTE
AND E2_VENCREA <= '20230331' -- COLOCAR VARIAVEL PARA CONSIDERAR O ULTIMO DIA DO MES CORRENTE
AND SE2010.D_E_L_E_T_ =''