SELECT 

RD.RD_FILIAL FILIAL,
RD.RD_MAT MATRICULA,
RA.RA_NOMECMP NOME,
RA.RA_HRSMES HORAS_MES,
RA.RA_SEXO SEXO,
RA.RA_CATFUNC CATEGORIA,
CASE WHEN RA.RA_TPCONTR = 1 THEN 'INDETERMINADO' WHEN RA.RA_TPCONTR = 2 THEN 'DETERMINADO' ELSE '' END TIPO_CONTRIBUCAO,
CASE WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '001' THEN '001-BANCO DO BRASIL' 
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '033' THEN '033-SANTANDER'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '104' THEN '104-CAIXA ECONOMICA FEDERAL'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '237' THEN '237-BRADESCO'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '399' THEN '399-HSBC'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '341' THEN '341-ITAU'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '777' THEN 'ORDEM DE PAGAMENTO' 
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '888' THEN 'FUNCIONARIO SEM CONTA'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '999' THEN 'CHEQUE'
 ELSE SUBSTR(RA.RA_BCDEPSA,1,3) END BANCO,
CASE WHEN SUBSTR(RA.RA_BCDEPSA,4,1)= '/' THEN SUBSTR(RA_BCDEPSA,5,8) ELSE SUBSTR(RA_BCDEPSA,4,8) END AGENCIA,
CASE WHEN SUBSTR(RA.RA_BCDEPSA,4,1)= '/' THEN RA.RA_BCDEPSA ELSE SUBSTR(RA.RA_BCDEPSA,1,3)||'/'||SUBSTR(RA_BCDEPSA,4,8) END BANCO_AGENCIA,
RA.RA_CTDEPSA CONTA,
1 CONTADOR,
(SELECT QB_DESCRIC FROM SQB010 WHERE QB_DEPTO = RA_DEPTO AND SQB010.D_E_L_E_T_=' 'AND ROWNUM = 1) DEPARTAMENTO,
RA.RA_ESTADO ESTADO,
RA.RA_MUNICIP CIDADE,
RA.RA_SALARIO SALARIO_BASE,
(SELECT CCH_PAIS FROM CCH010 PAIS WHERE PAIS.CCH_CODIGO = RA.RA_CPAISOR AND PAIS.D_E_L_E_T_=' ' AND ROWNUM = 1) PAIS_ORIGEM,
RA.RA_SINDICA COD_SINDICATO,
(SELECT RCE_ENTSIN FROM RCE010 WHERE RCE_CODIGO = RA.RA_SINDICA AND RCE010.D_E_L_E_T_=' 'AND ROWNUM = 1) ENTIDADE_SINDICATO,
(SELECT RCE_DESCRI FROM RCE010 WHERE RCE_CODIGO = RA.RA_SINDICA AND RCE010.D_E_L_E_T_=' 'AND ROWNUM = 1) SINDICATO,
RA.RA_TELEFON TELEFONE,
(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' 'AND ROWNUM = 1) FUNCAO,
(SELECT SQ3010.Q3_DESCSUM FROM SQ3010 WHERE Q3_CARGO = RA.RA_CARGO AND D_E_L_E_T_=' 'AND ROWNUM = 1) CARGO,
(SELECT RJ_CODCBO FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' 'AND ROWNUM = 1)  CBO,
(SUBSTR(RA_NASC,7,2)||'/'||SUBSTR(RA_NASC,5,2)||'/'||SUBSTR(RA_NASC,1,4)) NASCIMENTO,
(SUBSTR(RA_ADMISSA,7,2)||'/'||SUBSTR(RA_ADMISSA,5,2)||'/'||SUBSTR(RA_ADMISSA,1,4)) ADMISSAO,
(SUBSTR(RA_DEMISSA,7,2)||'/'||SUBSTR(RA_DEMISSA,5,2)||'/'||SUBSTR(RA_DEMISSA,1,4)) DEMISSAO,

(SELECT RG_TIPORES FROM SRG010 WHERE RG_MAT = RD_MAT AND RG_FILIAL = RD_FILIAL AND SRG010.D_E_L_E_T_=' 'AND ROWNUM = 1) COD_DEMISSAO,
(SELECT (SELECT SUBSTR(RX_TXT,0,30) FROM SRX010 WHERE RX_COD = RG_TIPORES AND RX_TIP ='32' AND SRX010.D_E_L_E_T_=' 'AND ROWNUM = 1) FROM SRG010 WHERE RG_MAT = RD_MAT AND RG_FILIAL = RD_FILIAL AND SRG010.D_E_L_E_T_=' 'AND ROWNUM = 1) DESC_DEMISSAO,

CASE WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' 'AND ROWNUM = 1 )= '2' THEN (RD.RD_VALOR)*-1 ELSE (RD.RD_VALOR) END VALOR,
RD_PD COD_VERBA,
(SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' 'AND ROWNUM = 1 )VERBA,
RD_HORAS REFERENCIA,
CASE WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' 'AND ROWNUM = 1 ) = '1' THEN 'PROVENTO'
WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' 'AND ROWNUM = 1 )= '2' THEN 'DESCONTO' ELSE 'BASE' END TIPO_VERBA,

CASE WHEN (SELECT RG_TIPORES FROM SRG010 WHERE RG_MAT = RA_MAT AND RG_FILIAL = RA_FILIAL AND SRG010.D_E_L_E_T_=' ' AND RG_DATADEM = RA_DEMISSA AND ROWNUM = 1) IS NULL AND RA_SITFOLH = 'D' THEN 'TRANSFERIDO'
    WHEN RA_SITFOLH = ' ' THEN 'NORMAL'
    WHEN RA_SITFOLH = 'F' THEN 'FERIAS' 
    WHEN RA_SITFOLH = 'D' THEN 'DEMITIDO'
    WHEN RA_SITFOLH = 'A' THEN 'AFASTADO'
    WHEN RA_SITFOLH = 'T' THEN 'TRANSFERIDO' ELSE ' ' END SITUACAO_FOLHA,
    
RD_CC CC,
RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,
SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC,

SUBSTR(RD.RD_DATARQ,5,2)||'/'||SUBSTR(RD.RD_DATARQ,1,4) DATA_ARQ,
SUBSTR(RD.RD_DATARQ,5,2) MES,
SUBSTR(RD.RD_DATARQ,1,4) ANO,
RA.RA_CATFUNC,

SUBSTR(RD.RD_DATPGT,7,2)||'/'||SUBSTR(RD.RD_DATPGT,5,2)||'/'||SUBSTR(RD.RD_DATPGT,1,4) DATA_PGTO,
SUBSTR(RD.RD_DATPGT,7,2) DIA_PGTO,
SUBSTR(RD.RD_DATPGT,5,2) MES_PGTO,
SUBSTR(RD.RD_DATPGT,1,4) ANO_PGTO


FROM SRD010 RD LEFT OUTER JOIN SRA010 RA ON RA.RA_MAT = RD.RD_MAT AND RA.RA_FILIAL = RD.RD_FILIAL

WHERE RA.D_E_L_E_T_=' ' AND RD.D_E_L_E_T_=' ' 
AND RD.RD_DATPGT BETWEEN :DATA_INICIO AND :DATA_FINAL AND RD.RD_DATPGT >='20150101'
