
SELECT RB_FILIAL, RB_MAT, (SELECT RA_NOMECMP FROM SRA010 WHERE RA_MAT = RB_MAT AND RA_FILIAL = RB_FILIAL AND SRA010.D_E_L_E_T_=' ') FUNCIONARIO, RB_NOME, RB_AUXCRE,TRUNC(SYSDATE)-TRUNC(TO_DATE(RB_DTNASC,'yyyymmdd'))IDADE FROM SRB010
WHERE D_E_L_E_T_=' '
AND TRUNC(SYSDATE)-TRUNC(TO_DATE(RB_DTNASC,'yyyymmdd')) <= 2191
AND RB_AUXCRE = '1' AND RB_FILIAL IN ('11057','11058')
ORDER BY RB_FILIAL, RB_MAT
;

UPDATE SRB010 SET RB_AUXCRE = '1' WHERE D_E_L_E_T_=' '
AND TRUNC(SYSDATE)-TRUNC(TO_DATE(RB_DTNASC,'yyyymmdd')) >= 1826 AND RB_FILIAL IN('11051')
AND RB_AUXCRE = '2';


