SELECT * FROM RG1010 WHERE RG1_ORDEM <> RG1_PD AND D_E_L_E_T_=' ';

SELECT RG1_FILIAL, RG1_MAT, RG1_AUTOM, LPAD((SELECT COUNT(RG1_ORDEM)+1 FROM RG1010 B WHERE B.D_E_L_E_T_=' ' AND B.RG1_FILIAL = A.RG1_FILIAL AND B.RG1_MAT = A.RG1_MAT AND B.RG1_PD < A.RG1_PD ),3,'0') RG1_ORDEM, RG1_TPCALC, RG1_PD, RG1_CODTAB,
RG1_LINHA, RG1_COLUNA, RG1_REFER, RG1_VALOR, RG1_PROP, RG1_CC, RG1_DINIPG, RG1_LIBPAG,
RG1_DFIMPG, RG1_TPDATO, RG1_DTBLEG, RG1_TPBLEG, RG1_NRBLEG, RG1_CMEMO, RG1_ITEM, RG1_CLVL,
RG1_ROT, RG1_NUMID, RG1_STATUS, A.D_E_L_E_T_, A.R_E_C_N_O_, A.R_E_C_D_E_L_ FROM RG1010 A WHERE RG1_MAT < '899999' AND D_E_L_E_T_=' ' ORDER BY RG1_FILIAL, RG1_MAT, RG1_PD;

UPDATE RG1010 A SET A.RG1_ORDEM = LPAD((SELECT COUNT(RG1_ORDEM)+1 FROM RG1010 B WHERE B.D_E_L_E_T_=' ' AND B.RG1_FILIAL = A.RG1_FILIAL AND B.RG1_MAT = A.RG1_MAT AND B.RG1_PD < A.RG1_PD ),3,'0')
WHERE A.RG1_MAT < '899999' AND A.RG1_ORDEM = A.RG1_PD AND A.D_E_L_E_T_=' ';