SELECT RD.RD_FILIAL,RD.RD_MAT,SUM(RD.RD_VALOR),RA.RA_NOMECMP,
RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,
SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC
FROM SRD010 RD JOIN SRA010 RA ON RA.RA_MAT = RD.RD_MAT AND RA.D_E_L_E_T_=' ' WHERE RD.D_E_L_E_T_=' ' AND RD.RD_PD IN ('403','405','427','495','500','705')
AND RD.RD_DATPGT BETWEEN :DATA_INICIAL AND :DATA_FINAL AND RD.RD_MAT < '900000' AND RA.RA_AFASFGT <> '5' GROUP BY RD.RD_FILIAL,RD.RD_MAT,RA.RA_NOMECMP,RA.RA_CC
UNION
SELECT RR.RR_FILIAL,RR.RR_MAT,SUM(RR.RR_VALOR),RA.RA_NOMECMP,
RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,
SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC
FROM SRR010 RR JOIN SRA010 RA ON RA.RA_MAT = RR.RR_MAT AND RA.D_E_L_E_T_=' ' WHERE RR.D_E_L_E_T_=' ' AND RR.RR_PD IN ('403','405','427','495','500','705')
AND RR.RR_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL  AND RR.RR_MAT < '900000' AND RA.RA_AFASFGT <> '5' 
GROUP BY RR.RR_FILIAL,RR.RR_MAT,RA.RA_NOMECMP,RA.RA_CC;


SELECT * FROM SRR010 WHERE  RR_PD IN ('403','405','427','495','500','705');
SELECT * FROM SRC010 WHERE RC_MAT = '018239';
