SELECT * FROM SEF010 WHERE D_E_L_E_T_=' ' AND EF_NATUR = '          ';

SELECT E5_FILIAL,E5_DATA,E5_VALOR,E5_BANCO,E5_AGENCIA,E5_CONTA,E5_NUMCHEQ,E5_BENEF,E5_RECONC FROM SE5010 WHERE D_E_L_E_T_=' ' AND E5_RECPAG='P' AND E5_TIPODOC = 'CH' ORDER BY E5_FILIAL, E5_CONTA,E5_NUMCHEQ, E5_RECONC;