SELECT 

E2_FILIAL FILIAL,
E2__RAZAO FORNECEDOR,
/*(SELECT A2_SALDUP FROM SA2010 WHERE A2_COD = E2_FORNECE AND A2_LOJA = E2_LOJA AND SUBSTR(A2_FILIAL,1,2) = SUBSTR(E2_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ') SALDO_A2,*/
SUM(E2_VALOR) VALOR,
/*SUM(E2_SALDO)*/ /*(SELECT SUM(E5_VALOR) FROM SE5010 WHERE E5_FILIAL = E2_FILIAL AND E2_FORNECE = E5_CLIFOR AND E2_LOJA = E5_LOJA AND SE5010.D_E_L_E_T_=' ' AND E5_DATA > :DATA_FINAL
AND E5_TIPODOC IN ('VL') AND E5_SITUACA = ' '  GROUP BY E5_FILIAL,E5_CLIFOR,E5_LOJA) SALDO_E5,
SUM(E2_SALDO)*/ /*SALDO,*/

--NVL((SELECT A.CTX_ATUDEB FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM IN ('F'||E2_FORNECE||E2_LOJA) /*AND A.CTX_CLVL IN (CT2_CLVLDB)*/ AND ROWID = 
--(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) DEBITOS,
--NVL((SELECT A.CTX_ATUCRD FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM IN ('F'||E2_FORNECE||E2_LOJA) /*AND A.CTX_CLVL IN (CT2_CLVLDB)*/ AND ROWID = 
--(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) CREDITOS,

NVL((SELECT A.CTX_ATUDEB FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM IN ('F'||E2_FORNECE||E2_LOJA) /*AND A.CTX_CLVL IN (CT2_CLVLDB)*/ AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(E2_EMISSAO,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(E2_EMISSAO,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0)
-
NVL((SELECT A.CTX_ATUCRD FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM IN ('F'||E2_FORNECE||E2_LOJA) /*AND A.CTX_CLVL IN (CT2_CLVLDB)*/ AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(E2_EMISSAO,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(E2_EMISSAO,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) CONTABIL
FROM SE2010
WHERE D_E_L_E_T_=' ' AND E2_EMISSAO BETWEEN :DATA_INICIAL AND :DATA_FINAL
GROUP BY E2_FILIAL, E2_FORNECE, E2_LOJA, E2__RAZAO, E2_EMISSAO
ORDER BY E2_FILIAL, E2__RAZAO;


SELECT * FROM CTU010 JOIN SE2010 ON CTU_CODIGO IN ('F'||E2_FORNECE||E2_LOJA) AND CTU_FILIAL = E2_FILIAL AND SE2010.D_E_L_E_T_=' ' WHERE  CTU_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(E2_EMISSAO,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(E2_EMISSAO,'YYYYMMDD')),0),'YYYYMMDD') AND CTU010.D_E_L_E_T_ = ' ';


SELECT 

E2_FILIAL FILIAL,
E2__RAZAO FORNECEDOR,
E2_FORNECE FORNECE,
E2_LOJA LOJA,

SUM(E2_VALOR) VALOR,

NVL((SELECT SUM(A.CTX_ATUDEB) FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM = 'F'||E2_FORNECE||E2_LOJA  AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND A.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(E2_EMISSAO,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(E2_EMISSAO,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0)
-
NVL((SELECT SUM(A.CTX_ATUCRD) FROM CTX010 A WHERE A.CTX_FILIAL = E2_FILIAL AND A.CTX_ITEM = 'F'||E2_FORNECE||E2_LOJA  AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(E2_EMISSAO,'YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(E2_EMISSAO,'YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) CONTABIL
FROM SE2010
WHERE D_E_L_E_T_=' ' AND E2_EMISSAO BETWEEN :DATA_INICIAL AND :DATA_FINAL
GROUP BY E2_FILIAL, E2_FORNECE, E2_LOJA, E2__RAZAO, E2_EMISSAO
ORDER BY E2_FILIAL, E2__RAZAO;


SELECT DISTINCT 
E2_FILIAL FILIAL,
E2__RAZAO FORNECEDOR,
E2_FORNECE FORNECE,
E2_LOJA LOJA,
SUM(E2_SALDO)+COALESCE((SELECT SUM(E5_VALOR) FROM SE5010 A WHERE  E5_FILIAL = E2_FILIAL AND E5_FORNECE = E2_FORNECE AND E2_LOJA = E5_LOJA AND E5_TIPODOC IN ('VL','BA') AND (E5_RECONC = 'x' OR E5_LOTE <> ' ') AND E5_SITUACA =' ' AND E5_RECPAG = 'P' AND A.D_E_L_E_T_=' ' AND E5_DATA >= '20170131' AND A.E5_LOTE NOT IN (SELECT B.E5_LOTE FROM SE5010 B WHERE  B.E5_LOTE = A.E5_LOTE AND B.E5_FILIAL = A.E5_FILIAL AND B.D_E_L_E_T_=' ' AND E5_RECPAG = 'R' AND B.E5_TIPODOC = 'ES') ),0) FINANCEIRO,ABS( COALESCE((SELECT SUM(A.CTU_ATUDEB) FROM CTU010 A WHERE  A.CTU_FILIAL = E2_FILIAL AND A.CTU_CODIGO = 'F'||E2_FORNECE||E2_LOJA AND ROWID = (SELECT MAX(ROWID) FROM CTU010 B WHERE  B.CTU_FILIAL = A.CTU_FILIAL AND B.CTU_CODIGO = A.CTU_CODIGO AND B.CTU_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE('20170101','YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(LAST_DAY(TO_DATE('20170131','YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ' AND B.CTU_IDENT = 'CTD')  AND A.D_E_L_E_T_=' '),0) -  COALESCE((SELECT SUM(A.CTU_ATUCRD) FROM CTU010 A WHERE  A.CTU_FILIAL = E2_FILIAL AND A.CTU_CODIGO = 'F'||E2_FORNECE||E2_LOJA AND ROWID = (SELECT MAX(ROWID) FROM CTU010 B WHERE  B.CTU_FILIAL = A.CTU_FILIAL AND B.CTU_CODIGO = A.CTU_CODIGO AND B.CTU_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE('20170101','YYYYMMDD'),0),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(LAST_DAY(TO_DATE('20170131','YYYYMMDD')),0),'YYYYMMDD') AND B.D_E_L_E_T_=' ' AND B.CTU_IDENT = 'CTD')  AND A.D_E_L_E_T_=' '),0)) CONTABIL

FROM SE2010 

WHERE  D_E_L_E_T_=' '
AND E2_EMISSAO BETWEEN '20170101' AND '20170131' 
AND E2_PREFIXO NOT IN ('FAT','FT') 
AND E2_TIPO IN ('NF ','BOL')
AND E2_FILIAL BETWEEN '11023' AND '11023' 
AND E2_FORNECE BETWEEN '      ' AND 'ZZZZZZ' 
AND E2_LOJA BETWEEN '  ' AND 'ZZ' 

GROUP BY E2_FILIAL, E2_FORNECE, E2_LOJA, E2__RAZAO 
ORDER BY  E2_FILIAL, E2__RAZAO;