SELECT 

R7_FILIAL FILIAL,
R7_MAT MATRICULA,
(SELECT RA_NOMECMP FROM SRA010 WHERE RA_MAT = R3_MAT AND RA_FILIAL = R3_FILIAL AND SRA010.D_E_L_E_T_=' ') FUNCIONARIO, 
SUBSTR(R7_DATA,7,2)||'/'||SUBSTR(R7_DATA,5,2)||'/'||SUBSTR(R7_DATA,1,4) DATA,
R7_TIPO||'-'||(SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = '41' AND X5_CHAVE = R7_TIPO AND SX5010.D_E_L_E_T_=' ') TIPO, 
R3_PD||'-'||R3_DESCPD VERBA,
R3_VALOR SALARIO,
R3_ANTEAUM BASE_DISSDIO,
CASE WHEN R3_VALOR != 0 AND R3_ANTEAUM != 0 THEN ROUND(((R3_VALOR-R3_ANTEAUM)/R3_ANTEAUM),4) ELSE 0 END PERCENTUAL,
R7_DESCFUN FUNCAO,
R7_DESCCAR CARGO,
R7_USUARIO USUARIO

FROM SR3010 
JOIN SR7010 ON R3_MAT = R7_MAT
AND R3_FILIAL = R7_FILIAL
AND R3_DATA = R7_DATA 
AND R3_TIPO = R7_TIPO
AND R3_SEQ = R7_SEQ 
AND SR7010.D_E_L_E_T_=' '

WHERE SR3010.D_E_L_E_T_=' ';