SELECT RC.RC_FILIAL FILIAL,
RC.RC_MAT MATRICULA,
RA.RA_RG RG,
RA.RA_CIC CPF,
RC.RC_PD COD_VERBA,
RV_DESC VERBA,
CASE WHEN RC.RC_PD = '403' THEN '132' ELSE RC.RC_ROTEIR END ROTEIRO,
SUM(CASE  WHEN RC_PD IN ('403','405','427','495','500') THEN RC_VALOR ELSE RC_VALOR * (-1) END) AS TOTAL_IR,
(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' ' AND SUBSTR(RC_FILIAL,1,2) = SUBSTR(RJ_FILIAL,1,2)) FUNCAO,
RA.RA_NOMECMP FUNCIONARIO,
TO_DATE(RC.RC_DATA,'YYYYMMDD') DATA,
SUBSTR(RC.RC_DATA,5,2)||'/'||SUBSTR(RC.RC_DATA,1,4) MES_ANO,
RC.RC_CC COD_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RC.RC_CC AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RC.RC_FILIAL,1,2)) CENTRO_CUSTO,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RC.RC_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RC.RC_FILIAL,1,2)) LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RC.RC_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RC.RC_FILIAL,1,2)) DEPTO_CC,
'RC' TABELA,
RA_CLVL
FROM SRC010 RC JOIN SRA010 RA ON RA.RA_MAT = RC.RC_MAT AND RA.RA_FILIAL = RC.RC_FILIAL AND RA.D_E_L_E_T_=' ' 
JOIN SRV010 ON SUBSTR(RV_FILIAL,1,2) = SUBSTR(RC.RC_FILIAL,1,2) AND RV_COD = RC.RC_PD AND SRV010.D_E_L_E_T_=' '
WHERE RC.D_E_L_E_T_=' ' 
AND RC.RC_PD IN ('403','405','427','495','500','360')
AND RC.RC_DATA BETWEEN :DATA_INICIO AND :DATA_FINAL AND RA.RA_CATFUNC <> 'A' 

AND RC.RC_MAT NOT IN 
    (SELECT RE.RE_MATP FROM SRE010 RE WHERE RE.RE_DATA > :DATA_FINAL AND RE.D_E_L_E_T_=' ' AND RE.RE_MATP <> RE.RE_MATD)

GROUP BY RC.RC_FILIAL,RC.RC_MAT,RA.RA_RG,RA.RA_CIC,RA.RA_NOMECMP,RC.RC_CC,RC.RC_DATA,RC.RC_PD,RV_DESC,RA_CODFUNC, RC.RC_ROTEIR, RA.RA_DEMISSA, RA_CLVL

UNION ALL

SELECT RD.RD_FILIAL,
RD.RD_MAT,
RA.RA_RG,
RA.RA_CIC,
RD.RD_PD,
RV_DESC VERBA,
CASE WHEN RD.RD_PD = '403' THEN '132' ELSE RD.RD_ROTEIR END ROTEIRO,
SUM(CASE  WHEN RD_PD IN ('403','405','427','495','500') THEN RD_VALOR ELSE RD_VALOR * (-1) END) AS TOTAL_IR,
(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' ' AND SUBSTR(RD_FILIAL,1,2) = SUBSTR(RJ_FILIAL,1,2)) FUNCAO,
RA.RA_NOMECMP,
TO_DATE(RD.RD_DATPGT,'YYYYMMDD')DATA,
SUBSTR(RD.RD_DATPGT,5,2)||'/'||SUBSTR(RD.RD_DATPGT,1,4) MES_ANO, 
RD.RD_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RD.RD_CC AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RD.RD_FILIAL,1,2)) CENTRO_CUSTO,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RD.RD_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RD.RD_FILIAL,1,2)) LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RD.RD_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2) = SUBSTR(RD.RD_FILIAL,1,2)) DEPTO_CC,
'RD' TABELA,
RA_CLVL
FROM SRD010 RD JOIN SRA010 RA ON RA.RA_MAT = RD.RD_MAT AND RA.RA_FILIAL = RD.RD_FILIAL AND RA.D_E_L_E_T_=' ' 
JOIN SRV010 ON SUBSTR(RV_FILIAL,1,2) = SUBSTR(RD.RD_FILIAL,1,2) AND RV_COD = RD.RD_PD AND SRV010.D_E_L_E_T_=' '
WHERE RD.D_E_L_E_T_=' ' AND RD.RD_PD IN ('403','405','427','495','500','360')
AND RD.RD_DATPGT BETWEEN :DATA_INICIO AND :DATA_FINAL AND RA.RA_CATFUNC <> 'A' 

AND RD.RD_MAT NOT IN 
    (SELECT RE.RE_MATP FROM SRE010 RE WHERE RE.RE_DATA > :DATA_FINAL AND RE.D_E_L_E_T_=' ' AND RE.RE_MATP <> RE.RE_MATD)
    
GROUP BY RD.RD_FILIAL,RD.RD_MAT,RA.RA_RG,RA.RA_CIC,RA.RA_NOMECMP,RD.RD_CC,RD.RD_DATPGT,RD.RD_PD,RV_DESC,RA_CODFUNC, RD.RD_ROTEIR, RA.RA_AFASFGT, RA_CLVL

UNION ALL

SELECT RR.RR_FILIAL,
RR.RR_MAT,
RA.RA_RG,
RA.RA_CIC,
RR.RR_PD,
RV_DESC VERBA,
CASE WHEN RR.RR_PD = '403' THEN '132' ELSE 'FOL' END ROTEIRO,
SUM(CASE  WHEN RR_PD IN ('403','405','427','495','500') THEN RR_VALOR ELSE RR_VALOR * (-1) END) AS TOTAL_IR,
(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' ' AND SUBSTR(RR_FILIAL,1,2) = SUBSTR(RJ_FILIAL,1,2)) FUNCAO,
RA.RA_NOMECMP,
TO_DATE(RR.RR_DATAPAG,'YYYYMMDD')DATA, 
SUBSTR(RR.RR_DATAPAG,5,2)||'/'||SUBSTR(RR.RR_DATAPAG,1,4) MES_ANO, 
RR.RR_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RR.RR_CC AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) CENTRO_CUSTO,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) DEPTO_CC, 
'RR' TABELA,
RA_CLVL
FROM SRR010 RR JOIN SRA010 RA ON RA.RA_MAT = RR.RR_MAT AND RA.RA_FILIAL = RR.RR_FILIAL AND RA.D_E_L_E_T_=' '
JOIN SRV010 ON SUBSTR(RV_FILIAL,1,2) = SUBSTR(RR.RR_FILIAL,1,2) AND RV_COD = RR.RR_PD AND SRV010.D_E_L_E_T_=' '
WHERE RR.D_E_L_E_T_=' ' 
AND RR.RR_PD IN ('403','405','427','495','500','360')
AND RR.RR_DATAPAG BETWEEN :DATA_INICIO AND :DATA_FINAL AND RA.RA_CATFUNC <> 'A' /*AND RA.RA_AFASFGT NOT IN ('5',' ')*/ AND RR.RR_TIPO3 = 'R'

AND RR.RR_MAT NOT IN 
		(SELECT RD.RD_MAT FROM SRD010 RD WHERE RR.RR_MAT = RD.RD_MAT AND RR.RR_FILIAL = RD.RD_FILIAL AND RD.D_E_L_E_T_=' ' 
		AND RD.RD_PD IN ('403','405','427','495','500','360')
		AND RD.RD_DATPGT = RR.RR_DATAPAG AND RA.RA_CATFUNC <> 'A' )

AND RR.RR_MAT NOT IN 
		(SELECT RC.RC_MAT FROM SRC010 RC WHERE RR.RR_MAT = RC.RC_MAT AND RR.RR_FILIAL = RC.RC_FILIAL AND RC.D_E_L_E_T_=' ' 
		AND RC.RC_PD IN ('403','405','427','495','500','360')
		AND RC.RC_DATA = RR.RR_DATAPAG AND RA.RA_CATFUNC <> 'A' )	
    
AND RR.RR_MAT NOT IN 
    (SELECT RE.RE_MATP FROM SRE010 RE WHERE RE.RE_DATA > :DATA_FINAL AND RE.D_E_L_E_T_=' ' AND RE.RE_MATP <> RE.RE_MATD)
		
GROUP BY RR.RR_FILIAL,RR.RR_MAT,RA.RA_RG,RA.RA_CIC,RA.RA_NOMECMP,RR.RR_CC, RR.RR_DATAPAG,RR.RR_PD,RV_DESC,RA_CODFUNC, RR.RR_ROTEIR, RA.RA_AFASFGT, RA_CLVL

UNION ALL

SELECT RR.RR_FILIAL,
RR.RR_MAT,
RA.RA_RG,
RA.RA_CIC,
RR.RR_PD,
RV_DESC VERBA,
CASE WHEN RR.RR_PD = '403' THEN '132' ELSE 'FOL' END ROTEIRO,
SUM(CASE  WHEN RR_PD IN ('403','405','427','495','500') THEN RR_VALOR ELSE RR_VALOR * (-1) END) AS TOTAL_IR,
(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA.RA_CODFUNC AND D_E_L_E_T_=' '  AND SUBSTR(RR_FILIAL,1,2) = SUBSTR(RJ_FILIAL,1,2)) FUNCAO,
RA.RA_NOMECMP,
TO_DATE(RR.RR_DATAPAG,'YYYYMMDD')DATA, 
SUBSTR(RR.RR_DATAPAG,5,2)||'/'||SUBSTR(RR.RR_DATAPAG,1,4) MES_ANO, 
RR.RR_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RR.RR_CC AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) CENTRO_CUSTO,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(CTT_FILIAL,1,2)=SUBSTR(RR_FILIAL,1,2)) DEPTO_CC, 
'RR' TABELA,
RA_CLVL
FROM SRR010 RR JOIN SRA010 RA ON RA.RA_MAT = RR.RR_MAT AND RA.RA_FILIAL = RR.RR_FILIAL AND RA.D_E_L_E_T_=' ' 
JOIN SRV010 ON SUBSTR(RV_FILIAL,1,2) = SUBSTR(RR.RR_FILIAL,1,2) AND RV_COD = RR.RR_PD AND SRV010.D_E_L_E_T_=' '
WHERE RR.D_E_L_E_T_=' ' 
AND RR.RR_PD IN ('403','405','427','495','500','360')
AND RR.RR_DATAPAG BETWEEN :DATA_INICIO AND :DATA_FINAL AND RA.RA_CATFUNC <> 'A' /*AND RA.RA_AFASFGT NOT IN ('5',' ')*/ AND RR.RR_TIPO3 <> 'R'

AND RR.RR_MAT NOT IN 
		(SELECT RD.RD_MAT FROM SRD010 RD WHERE RA.RA_MAT = RD.RD_MAT AND RA.RA_FILIAL = RD.RD_FILIAL AND RD.D_E_L_E_T_=' ' 
		AND RD.RD_PD IN ('403','405','427','495','500','360')
		AND RD.RD_DATPGT = RR.RR_DATAPAG AND RA.RA_CATFUNC <> 'A' )

AND RR.RR_MAT NOT IN 
		(SELECT RC.RC_MAT FROM SRC010 RC WHERE RA.RA_MAT = RC.RC_MAT AND RA.RA_FILIAL = RC.RC_FILIAL AND RC.D_E_L_E_T_=' ' 
		AND RC.RC_PD IN ('403','405','427','495','500','360')
		AND RC.RC_DATA = RR.RR_DATAPAG AND RA.RA_CATFUNC <> 'A' )	
    
AND RR.RR_MAT NOT IN 
    (SELECT RE.RE_MATP FROM SRE010 RE WHERE RE.RE_DATA > :DATA_FINAL AND RE.D_E_L_E_T_=' ' AND RE.RE_MATP <> RE.RE_MATD)
		
GROUP BY RR.RR_FILIAL,RR.RR_MAT,RA.RA_RG,RA.RA_CIC,RA.RA_NOMECMP,RR.RR_CC, RR.RR_DATAPAG,RR.RR_PD,RV_DESC,RA_CODFUNC, RR.RR_ROTEIR, RA.RA_AFASFGT, RA_CLVL

ORDER BY 1, 5, 6, 7