SELECT 
E2_FILIAL FILIAL,
E2_PREFIXO PREFIXO,
E2_NUM TITULO,
E2_PARCELA PARCELA, 
E2_TIPO TIPO_TITULO,
E2_NATUREZ COD_NATUREZA,
E2_CCD COD_CC,

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR((SELECT CASE WHEN D1.D1_RATEIO = '2' THEN D1.D1_CC ELSE (SELECT DE_CC FROM SDE010 WHERE DE_DOC = E2_NUM AND DE_SERIE = E2_PREFIXO AND DE_FORNECE = E2_FORNECE
      AND E2_LOJA = DE_LOJA AND E2_FILIAL = DE_FILIAL AND ROWNUM = 1) END FROM SD1010 D1 WHERE E2_NUM = D1.D1_DOC AND E2_PREFIXO = D1.D1_SERIE
          AND D1.D1_FORNECE = E2_FORNECE AND D1.D1_LOJA = E2_LOJA AND D1.D_E_L_E_T_=' ' AND D1.D1_CC IS NOT NULL AND ROWNUM = 1),1,5)||'       ' AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND SE2010.D_E_L_E_T_=' ')

     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E2_CCD,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') END LOCAL_CC,

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR((SELECT CASE WHEN D1.D1_RATEIO = '2' THEN D1.D1_CC ELSE (SELECT DE_CC FROM SDE010 WHERE DE_DOC = E2_NUM AND DE_SERIE = E2_PREFIXO AND DE_FORNECE = E2_FORNECE
      AND E2_LOJA = DE_LOJA AND E2_FILIAL = DE_FILIAL AND ROWNUM = 1) END FROM SD1010 D1 WHERE E2_NUM = D1.D1_DOC AND E2_PREFIXO = D1.D1_SERIE
          AND D1.D1_FORNECE = E2_FORNECE AND D1.D1_LOJA = E2_LOJA AND D1.D_E_L_E_T_=' ' AND D1.D1_CC IS NOT NULL AND ROWNUM = 1),1,8)||'    ' AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND SE2010.D_E_L_E_T_=' ')

     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E2_CCD,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') END DEPTO_CC,

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = (SELECT CASE WHEN D1.D1_RATEIO = '2' THEN D1.D1_CC ELSE (SELECT DE_CC FROM SDE010 WHERE DE_DOC = E2_NUM AND DE_SERIE = E2_PREFIXO AND DE_FORNECE = E2_FORNECE
      AND E2_LOJA = DE_LOJA AND E2_FILIAL = DE_FILIAL AND ROWNUM = 1) END FROM SD1010 D1 WHERE E2_NUM = D1.D1_DOC AND E2_PREFIXO = D1.D1_SERIE
          AND D1.D1_FORNECE = E2_FORNECE AND D1.D1_LOJA = E2_LOJA AND D1.D_E_L_E_T_=' ' AND D1.D1_CC IS NOT NULL AND ROWNUM = 1) AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND SE2010.D_E_L_E_T_=' ')

     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = E2_CCD AND CTT010.D_E_L_E_T_=' ') END CENTRO_CUSTO,
     
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = E2_NATUREZ AND D_E_L_E_T_=' ') NATUREZA,

E2__RAZAO FORNECEDOR,
ROUND(E2_VALOR,3) VALOR,
E2_SALDO SALDO,
E2_ISS ISS,
E2_IRRF IRRF,
E2_INSS INSS,
E2_CSLL CSLL,

SUBSTR(E2_EMISSAO,7,2)||'/'||SUBSTR(E2_EMISSAO,5,2)||'/'||SUBSTR(E2_EMISSAO,1,4) EMISSAO,
SUBSTR(E2_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E2_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E2_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E2_VENCTO,7,2)||'/'||SUBSTR(E2_VENCTO,5,2)||'/'||SUBSTR(E2_VENCTO,1,4) VECIMENTO,
SUBSTR(E2_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E2_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E2_VENCTO,1,4) ANO_VECIMENTO,

SUBSTR(E2_BAIXA,7,2)||'/'||SUBSTR(E2_BAIXA,5,2)||'/'||SUBSTR(E2_BAIXA,1,4) BAIXA,
SUBSTR(E2_BAIXA,7,2) DIA_BAIXA,
SUBSTR(E2_BAIXA,5,2) MES_BAIXA,
SUBSTR(E2_BAIXA,1,4) ANO_BAIXA,

E2_HIST HISTORICO

FROM SE2010

WHERE D_E_L_E_T_=' ';


SELECT D1_RATEIO FROM SD1010;