SELECT 
E1_FILIAL FILIAL,
E1_PREFIXO PREFIXO,
E1_NUM TITULO,
E1_PARCELA PARCELA, 
E1_TIPO TIPO_TITULO,
E1_NATUREZ COD_NATUREZA,
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = E1_NATUREZ AND D_E_L_E_T_=' ') NATUREZA,
E1_NOMCLI FORNECEDOR,
ROUND(E1_VALOR,3) VALOR,
E1_SALDO SALDO,
E1_ISS ISS,
E1_IRRF IRRF,
E1_INSS INSS,
E1_CSLL CSLL,

SUBSTR(E1_EMISSAO,7,2)||'/'||SUBSTR(E1_EMISSAO,5,2)||'/'||SUBSTR(E1_EMISSAO,1,4) EMISSAO,
SUBSTR(E1_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E1_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E1_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E1_VENCTO,7,2)||'/'||SUBSTR(E1_VENCTO,5,2)||'/'||SUBSTR(E1_VENCTO,1,4) VECIMENTO,
SUBSTR(E1_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E1_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E1_VENCTO,1,4) ANO_VECIMENTO,

SUBSTR(E1_BAIXA,7,2)||'/'||SUBSTR(E1_BAIXA,5,2)||'/'||SUBSTR(E1_BAIXA,1,4) BAIXA,
SUBSTR(E1_BAIXA,7,2) DIA_BAIXA,
SUBSTR(E1_BAIXA,5,2) MES_BAIXA,
SUBSTR(E1_BAIXA,1,4) ANO_BAIXA,

E1_HIST HISTORICO

FROM SE1010

WHERE D_E_L_E_T_=' '

;