SELECT 

CT2_FILIAL FILIAL,
TO_DATE(CT2_DATA,'YYYYMMDD') DATA, 
CT2_DEBITO DEBITO, 
CT2_CREDIT CREDITO,
CASE WHEN CT2_ITEMD <> ' ' THEN (CT2_VALOR) ELSE 0 END VALOR_DEBITO,
CASE WHEN CT2_ITEMC <> ' ' THEN CT2_VALOR*-1 ELSE 0 END VALOR_CREDITO,

CASE WHEN CT2_ITEMD <> ' ' THEN 'DEBITO' WHEN CT2_ITEMC <> ' ' THEN 'CREDITO' END TIPO,
CT2_HIST HISTORICO,
NVL(CASE WHEN CT2_CCD <> ' ' THEN CT2_CCD WHEN CT2_CCC <> ' ' THEN CT2_CCC END,' ') CENTRO_CUSTO, 
CASE WHEN CT2_ITEMD <> ' ' THEN CT2_ITEMD WHEN CT2_ITEMC <> ' ' THEN CT2_ITEMC END ITEM,
NVL(A2_NOME,A1_NOME)  CLIENTE_FORNECEDOR,

CASE WHEN CT2_CLVLDB <> ' ' THEN CT2_CLVLDB WHEN CT2_CLVLCR <> ' ' THEN CT2_CLVLCR END CLASSE,


NVL((SELECT A.CTX_ATUDEB FROM CTX010 A WHERE A.CTX_FILIAL = CT2_FILIAL AND A.CTX_ITEM IN (CT2_ITEMD,CT2_ITEMC) AND A.CTX_CLVL IN (CT2_CLVLDB) AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),-1),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),-1),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0)
-
NVL((SELECT A.CTX_ATUCRD FROM CTX010 A WHERE A.CTX_FILIAL = CT2_FILIAL AND A.CTX_ITEM IN (CT2_ITEMC,CT2_ITEMD) AND A.CTX_CLVL IN (CT2_CLVLCR) AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),-1),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),-1),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) 
SALDO_ANTERIOR,

NVL((SELECT A.CTX_ATUDEB FROM CTX010 A WHERE A.CTX_FILIAL = CT2_FILIAL AND A.CTX_ITEM IN (CT2_ITEMD,CT2_ITEMC) AND A.CTX_CLVL IN (CT2_CLVLDB) AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),-1),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),-1),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0)
-
NVL((SELECT A.CTX_ATUCRD FROM CTX010 A WHERE A.CTX_FILIAL = CT2_FILIAL AND A.CTX_ITEM IN (CT2_ITEMC,CT2_ITEMD) AND A.CTX_CLVL IN (CT2_CLVLCR) AND ROWID = 
(SELECT MAX(ROWID) FROM CTX010 B WHERE B.CTX_FILIAL = A.CTX_FILIAL AND B.CTX_ITEM = A.CTX_ITEM AND B.CTX_DATA BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:DATA_INICIAL,'YYYYMMDD'),-1),'YYYYMMDD') AND TO_CHAR(ADD_MONTHS(Last_Day(TO_DATE(:DATA_FINAL,'YYYYMMDD')),-1),'YYYYMMDD') AND B.D_E_L_E_T_=' ')),0) 
+
CASE WHEN CT2_ITEMD <> ' ' THEN (CT2_VALOR) ELSE CT2_VALOR*-1 END
RESULTADO

FROM CT2010 

LEFT JOIN SA2010 ON A2_COD||A2_LOJA = SUBSTR(NVL(NULLIF(CT2_ITEMD,' '),CT2_ITEMC),2,8) AND SUBSTR(CT2_FILIAL,1,2) = SUBSTR(A2_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ' AND SUBSTR(NVL(NULLIF(CT2_ITEMD,' '),CT2_ITEMC),1,1) = 'F'
LEFT JOIN SA1010 ON A1_COD||A1_LOJA = SUBSTR(NVL(NULLIF(CT2_ITEMD,' '),CT2_ITEMC),2,8) AND SUBSTR(CT2_FILIAL,1,2) = SUBSTR(A1_FILIAL,1,2) AND SA1010.D_E_L_E_T_=' ' AND SUBSTR(NVL(NULLIF(CT2_ITEMD,' '),CT2_ITEMC),1,1) = 'C' 

WHERE /*(CT2_ITEMC = 'F00009401   ' OR CT2_ITEMD = 'F00009401   ') 
AND (CT2_CLVLCR = '010410001   ' OR CT2_CLVLDB = '010410001   ') 
AND*/ CT2010.D_E_L_E_T_=' ' 
AND CT2_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL
AND CT2_DC = '3'
AND (CT2_ITEMD <> ' ' OR CT2_ITEMC <> ' ')
AND (CT2_CLVLDB <> ' ' OR CT2_CLVLCR <> ' ');

SELECT * FROM CTX010 WHERE CTX_ITEM = 'F00009401' AND CTX_DATA BETWEEN '20170301'AND'20170331' AND CTX_CLVL = '010410001';