SELECT 
E1_FILIAL FILIAL,
E1_PREFIXO PREFIXO,
E1_NUM TITULO,
E1_PARCELA PARCELA, 
E1_TIPO TIPO_TITULO,
(CASE WHEN (E1_NATUREZ = ' ' OR E1_NATUREZ IS NULL) THEN (SELECT EV_NATUREZ FROM SEV010 WHERE EV_NUM = E1_NUM AND EV_PREFIXO = E1_PREFIXO AND E1_CLIENTE = EV_CLIFOR AND E1_LOJA = EV_LOJA AND ROWNUM = 1 ) ELSE E1_NATUREZ END ) COD_NATUREZA,

CASE WHEN E1_CCC IS NULL OR E1_CCC = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = (SELECT D2.D2_CCUSTO FROM SD2010 D2 WHERE E1_NUM = D2.D2_DOC AND E1_PREFIXO = D2.D2_SERIE
          AND D2.D2_CLIENTE = E1_CLIENTE AND D2.D2_LOJA = E1_LOJA AND D2.D_E_L_E_T_=' ' AND D2.D2_CCUSTO IS NOT NULL AND ROWNUM = 1)||'       ' /*AND ROWNUM = 1*/ AND CTT010.D_E_L_E_T_=' ' AND E1.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E1_CCC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') END LOCAL_CC,
     
CASE WHEN E1_CCC IS NULL OR E1_CCC = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = (SELECT D2.D2_CCUSTO FROM SD2010 D2 WHERE E1_NUM = D2.D2_DOC AND E1_PREFIXO = D2.D2_SERIE
          AND D2.D2_CLIENTE = E1_CLIENTE AND D2.D2_LOJA = E1_LOJA AND D2.D_E_L_E_T_=' ' AND D2.D2_CCUSTO IS NOT NULL AND ROWNUM = 1)||'    ' AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND E1.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E1_CCC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') END DEPTO_CC,

CASE WHEN E1_CCC IS NULL OR E1_CCC = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = (SELECT D2.D2_CCUSTO FROM SD2010 D2 WHERE E1_NUM = D2.D2_DOC AND E1_PREFIXO = D2.D2_SERIE
          AND D2.D2_CLIENTE = E1_CLIENTE AND D2.D2_LOJA = E1_LOJA AND D2.D_E_L_E_T_=' ' AND D2.D2_CCUSTO IS NOT NULL AND ROWNUM = 1) AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND E1.D_E_L_E_T_=' ')

     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = E1_CCC AND CTT010.D_E_L_E_T_=' ') END CENTRO_CUSTO,
     
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = CASE WHEN (E1_NATUREZ = ' ' OR E1_NATUREZ IS NULL) THEN (SELECT EV_NATUREZ FROM SEV010 WHERE EV_NUM = E1_NUM AND EV_PREFIXO = E1_PREFIXO AND E1_CLIENTE = EV_CLIFOR AND E1_LOJA = EV_LOJA AND ROWNUM = 1) ELSE E1_NATUREZ END AND D_E_L_E_T_=' ') NATUREZA,

E1.E1_NOMCLI CLIENTE,
/*EV_VALOR,
EV_PERC,
E1_VALOR,*/
ROUND(CASE WHEN EV_VALOR IS NULL THEN ROUND(E1_VALOR,2) ELSE ROUND(EV_VALOR,2) END ,2) VALOR,
/*E1_ISS ISS,
E1_IRRF IRRF,
E1_INSS INSS,
E1_CSLL CSLL,
*/
SUBSTR(E1_EMISSAO,7,2)||'/'||SUBSTR(E1_EMISSAO,5,2)||'/'||SUBSTR(E1_EMISSAO,1,4) EMISSAO,
SUBSTR(E1_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E1_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E1_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E1_VENCTO,7,2)||'/'||SUBSTR(E1_VENCTO,5,2)||'/'||SUBSTR(E1_VENCTO,1,4) VECIMENTO,
SUBSTR(E1_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E1_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E1_VENCTO,1,4) ANO_VECIMENTO,

SUBSTR(E1_BAIXA,7,2)||'/'||SUBSTR(E1_BAIXA,5,2)||'/'||SUBSTR(E1_BAIXA,1,4) BAIXA,
SUBSTR(E1_BAIXA,7,2) DIA_BAIXA,
SUBSTR(E1_BAIXA,5,2) MES_BAIXA,
SUBSTR(E1_BAIXA,1,4) ANO_BAIXA,
E1_HIST HISTORICO

FROM SE1010 E1 

LEFT OUTER JOIN SEV010 EV ON EV.EV_NUM = E1.E1_NUM
AND EV.EV_PREFIXO = E1.E1_PREFIXO
AND EV.EV_CLIFOR = E1.E1_CLIENTE
AND E1.E1_LOJA = EV.EV_LOJA
AND E1.E1_FILIAL = EV.EV_FILIAL
AND EV.D_E_L_E_T_=' '
AND EV.EV_RECPAG = 'R'

WHERE E1.D_E_L_E_T_=' ' ;/*AND E1_EMISSAO BETWEEN '20150201' AND '20150228' AND (SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = CASE WHEN (E1_NATUREZ = ' ' OR E1_NATUREZ IS NULL) THEN (SELECT EV_NATUREZ FROM SEV010 WHERE EV_NUM = E1_NUM AND EV_PREFIXO = E1_PREFIXO AND E1_CLIENTE = EV_CLIFOR AND E1_LOJA = EV_LOJA AND ROWNUM = 1) ELSE E1_NATUREZ END AND D_E_L_E_T_=' ') LIKE 'GENEROS ALI%' AND E1_NUM = '000052166';*/
