SELECT CN9_FILIAL FILIAL,
CN9_NUMERO CONTRATO,
CNC_CODIGO COD_FORNECEDOR,
CNC_LOJA LOJA,
CASE WHEN CN9_CLIENT = ' ' THEN 
(SELECT A2_NOME FROM SA2010 WHERE A2_COD = CNC_CODIGO AND A2_LOJA = CNC_LOJA AND SA2010.D_E_L_E_T_=' ')
ELSE (SELECT A1_NOME FROM SA1010 WHERE A1_COD = CN9_CLIENT AND A1_LOJA = CN9_LOJACL AND SA1010.D_E_L_E_T_=' ') END FORNECEDOR, 
CN9_DTINIC DATA_INICIO,
CN9_DTFIM DATA_FINAL,
CN9_CONDPG COND_PAGAMENTO,
CN9_TPCTO TIPO_PAGAMENTO,
CN9_VLINI VALOR_INICIAL,
CN9_VLATU VALOR_ATUAL,
CN9_SALDO SALDO

FROM CN9010 JOIN CNC010 ON CNC_FILIAL = CN9_FILIAL AND CNC_NUMERO = CN9_NUMERO AND CN9010.D_E_L_E_T_=' ' WHERE CN9010.D_E_L_E_T_=' ';
