SELECT 
E2_FILIAL FILIAL,
E2_PREFIXO PREFIXO,
E2_NUM TITULO,
E2_PARCELA PARCELA, 
E2_TIPO TIPO_TITULO,
/*(CASE WHEN (E2_NATUREZ = ' ' OR E2_NATUREZ IS NULL) THEN EV_NATUREZ ELSE E2_NATUREZ END ) COD_NATUREZA,*/

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(CASE WHEN DE.DE_CC IS NULL THEN (D1.D1_CC)ELSE DE.DE_CC END,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND E2.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E2_CCD,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') END LOCAL_CC,

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(CASE WHEN DE.DE_CC IS NULL THEN (D1.D1_CC)ELSE DE.DE_CC END,1,8)||'    ' AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND E2.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(E2_CCD,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') END DEPTO_CC,

CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = CASE WHEN DE.DE_CC IS NULL THEN (D1.D1_CC)ELSE DE.DE_CC END AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND E2.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = E2_CCD AND CTT010.D_E_L_E_T_=' ') END CENTRO_CUSTO,
     
CASE WHEN E2_CCD IS NULL OR E2_CCD = '            ' THEN 
      (SELECT CTT_CUSTO FROM CTT010 WHERE CTT_CUSTO = CASE WHEN DE.DE_CC IS NULL THEN (D1.D1_CC)ELSE DE.DE_CC END AND ROWNUM = 1 AND CTT010.D_E_L_E_T_=' ' AND E2.D_E_L_E_T_=' ')
     ELSE (SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = E2_CCD AND CTT010.D_E_L_E_T_=' ') END COD_CUSTO,
     
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO =  CASE WHEN EV_NATUREZ IS NULL THEN E2_NATUREZ ELSE EV_NATUREZ END AND D_E_L_E_T_=' ') NATUREZA,

E2__RAZAO FORNECEDOR,

ROUND(CASE WHEN D1.D1_CUSTO IS NULL THEN
      CASE WHEN EV.EV_VALOR IS NULL THEN 
            E2.E2_VALOR ELSE EV.EV_VALOR END
      ELSE (CASE WHEN D1_RATEIO = '2' THEN (D1.D1_CUSTO)
             ELSE (DE.DE_CUSTO1) END*EV.EV_PERC) END/
  (SELECT COUNT(E2_PARCELA) FROM SE2010 WHERE E2_NUM = E2.E2_NUM
  AND E2_FILIAL = E2.E2_FILIAL AND E2_PREFIXO = E2.E2_PREFIXO AND E2_FORNECE = E2.E2_FORNECE AND E2_LOJA = E2.E2_LOJA AND SE2010.D_E_L_E_T_=' ' AND E2.E2_EMISSAO = E2_EMISSAO GROUP BY E2_NUM),6) VALOR,

/*E2_ISS ISS,
E2_IRRF IRRF,
E2_INSS INSS,
E2_CSLL CSLL,
*/
SUBSTR(E2_EMISSAO,7,2)||'/'||SUBSTR(E2_EMISSAO,5,2)||'/'||SUBSTR(E2_EMISSAO,1,4) EMISSAO,
SUBSTR(E2_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E2_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E2_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E2_VENCTO,7,2)||'/'||SUBSTR(E2_VENCTO,5,2)||'/'||SUBSTR(E2_VENCTO,1,4) VECIMENTO,
SUBSTR(E2_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E2_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E2_VENCTO,1,4) ANO_VECIMENTO,

SUBSTR(E2_BAIXA,7,2)||'/'||SUBSTR(E2_BAIXA,5,2)||'/'||SUBSTR(E2_BAIXA,1,4) BAIXA,
SUBSTR(E2_BAIXA,7,2) DIA_BAIXA,
SUBSTR(E2_BAIXA,5,2) MES_BAIXA,
SUBSTR(E2_BAIXA,1,4) ANO_BAIXA,
E2_HIST HISTORICO,

(SELECT E5_BANCO FROM SE5010 WHERE E2_NUM = E5_NUMERO AND E2_PREFIXO = E5_PREFIXO AND E2_FILIAL = E5_FILIAL AND E2_BAIXA = E5_DATA AND E2_FORNECE = E5_FORNECE AND E2_LOJA = E5_LOJA AND SE5010.D_E_L_E_T_=' ' AND ROWNUM = 1) BANCO_BAIXA,
/*(SELECT E5_AGENCIA FROM SE5010 WHERE E2_NUM = E5_NUMERO AND E2_PREFIXO = E5_PREFIXO AND E2_FILIAL = E5_FILIAL AND E2_BAIXA = E5_DATA AND E2_FORNECE = E5_FORNECE AND E2_LOJA = E5_LOJA AND SE5010.D_E_L_E_T_=' ' AND ROWNUM = 1) AGENCIA_BAIXA,*/
(SELECT E5_CONTA FROM SE5010 WHERE E2_NUM = E5_NUMERO AND E2_PREFIXO = E5_PREFIXO AND E2_FILIAL = E5_FILIAL AND E2_BAIXA = E5_DATA AND E2_FORNECE = E5_FORNECE AND E2_LOJA = E5_LOJA AND SE5010.D_E_L_E_T_=' ' AND ROWNUM = 1) CONTA_BAIXA

FROM SE2010 E2 

LEFT JOIN SD1010 D1 ON D1.D1_DOC = E2.E2_NUM
AND D1.D1_SERIE = E2.E2_PREFIXO
AND D1.D1_FORNECE = E2.E2_FORNECE
AND E2.E2_LOJA = D1.D1_LOJA
AND E2.E2_FILIAL = D1.D1_FILIAL
AND D1.D_E_L_E_T_=' '

LEFT JOIN SDE010 DE ON DE.DE_DOC = E2.E2_NUM
AND DE.DE_SERIE = E2.E2_PREFIXO
AND DE.DE_FORNECE = E2.E2_FORNECE
AND E2.E2_LOJA = DE.DE_LOJA
AND E2.E2_FILIAL = DE.DE_FILIAL
AND D1.D1_RATEIO = '1'
AND D1.D1_ITEM = DE.DE_ITEMNF
AND DE.D_E_L_E_T_=' '

LEFT JOIN SEV010 EV ON EV.EV_NUM = E2.E2_NUM
AND EV.EV_PREFIXO = E2.E2_PREFIXO
AND EV.EV_CLIFOR = E2.E2_FORNECE
AND EV.EV_PARCELA = E2.E2_PARCELA
AND E2.E2_LOJA = EV.EV_LOJA
AND E2.E2_FILIAL = EV.EV_FILIAL
AND EV.D_E_L_E_T_=' '

WHERE E2.D_E_L_E_T_=' ' AND E2.E2_PARCELA NOT IN ('00','0')
AND E2.E2_EMISSAO BETWEEN :DATA_INICIAL AND :DATA_FINAL