SELECT 
D1.D1_FILIAL FILIAL,
D1.D1_DOC NOTA,
D1.D1_SERIE SERIE,
/*D1.D1_COD COD_PRODUTO,*/
D1.D1_TP TIPO_PRODUTO,
(SELECT SUBSTR(B1.B1_DESC,1,40) FROM SB1010 B1 WHERE B1.B1_COD = D1.D1_COD AND B1.D_E_L_E_T_=' ' AND ROWNUM = 1) PRODUTO,
/*D1.D1_UM UNIDADE,*/
ABS(D1.D1_QUANT * CASE WHEN D1.D1_RATEIO = '1' AND DE.DE_PERC IS NOT NULL THEN (DE.DE_PERC/100) ELSE 1 END) QUANTIDADE,
ABS(D1.D1_VUNIT * CASE WHEN D1.D1_RATEIO = '1' AND DE.DE_PERC IS NOT NULL THEN (DE.DE_PERC/100) ELSE 1 END) VALOR_UNITARIO,
ABS(D1.D1_TOTAL * CASE WHEN D1.D1_RATEIO = '1' AND DE.DE_PERC IS NOT NULL THEN (DE.DE_PERC/100) ELSE 1 END) TOTAL,
/*CASE WHEN D1.D1_RATEIO = '1' THEN DE.DE_CUSTO1 ELSE D1.D1_CUSTO END CUSTO,*/
D1.D1_TES||'-'||(SELECT SUBSTR(F4.F4_FINALID,1,40) FROM SF4010 F4 WHERE F4.F4_CODIGO = D1.D1_TES AND F4.D_E_L_E_T_=' ' AND ROWNUM=1) TES,

/*CASE WHEN (SELECT (F4.F4_DUPLIC) FROM SF4010 F4 WHERE F4.F4_CODIGO = D1.D1_TES AND F4.D_E_L_E_T_=' ' AND ROWNUM=1) = 'S' THEN 'SIM' ELSE 'NÃO' END FINANCEIRO,*/

/*D1.D1__NATURE COD_NATUREZA,*/
(SELECT ED_DESCRIC FROM SED010 WHERE D1.D1__NATURE = ED_CODIGO AND SED010.D_E_L_E_T_=' ') NATUREZA,

/*D1.D1_CF CFOP, */
/*D1.D1_DESC DESCONTO,*/
/*D1.D1_FORNECE||'-'||D1.D1_LOJA COD_FORNECEDOR,*/
(SELECT A2.A2_NOME FROM SA2010 A2 WHERE A2.A2_COD = D1.D1_FORNECE AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_=' ' AND ROWNUM =1) RAZAO_FORNECEDOR,
/*(SELECT A2.A2_NREDUZ FROM SA2010 A2 WHERE A2.A2_COD = D1.D1_FORNECE AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_=' ') NOME_FANTASIA,*/
(SELECT A2.A2_CGC FROM SA2010 A2 WHERE A2.A2_COD = D1.D1_FORNECE AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_=' ' AND ROWNUM = 1) CNPJ,

(SELECT A2.A2_DDD||'-'||CASE WHEN A2.A2_TEL =' ' THEN CASE WHEN A2.A2_FAX = ' ' THEN A2.A2_TELRE ELSE A2.A2_TEL END ELSE A2.A2_TEL END FROM SA2010 A2 WHERE A2.A2_COD = D1.D1_FORNECE AND A2.A2_LOJA = D1.D1_LOJA AND A2.D_E_L_E_T_=' ' AND ROWNUM =1) TELEFONE,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(CASE WHEN D1.D1_CC = ' ' THEN NVL(DE.DE_CC,D1.D1_CC) ELSE D1.D1_CC END,1,5)||'       ' AND CTT010.D_E_L_E_T_<>'*') LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(CASE WHEN D1.D1_CC = ' ' THEN NVL(DE.DE_CC,D1.D1_CC) ELSE D1.D1_CC END,1,8)||'    ' AND CTT010.D_E_L_E_T_<>'*') DEPTO_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = CASE WHEN D1.D1_CC = ' ' THEN NVL(DE.DE_CC,D1.D1_CC) ELSE D1.D1_CC END AND CTT010.D_E_L_E_T_<>'*') CENTRO_CUSTO,

CASE WHEN DE.DE_PERC IS NULL THEN 100 ELSE DE.DE_PERC END PERCENTUAL_RATEIO,

/*D1.D1_CONTA CONTA_CONTABIL,*/
SUBSTR(D1.D1_EMISSAO,7,2)||'/'||SUBSTR(D1.D1_EMISSAO,5,2)||'/'||SUBSTR(D1.D1_EMISSAO,1,4) EMISSAO,
SUBSTR(D1.D1_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(D1.D1_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(D1.D1_EMISSAO,1,4) ANO_EMISSAO

FROM SD1010 D1 /*LEFT OUTER JOIN SF1010 F1 ON D1.D1_DOC = F1.F1_DOC AND F1.F1_FILIAL = D1.D1_FILIAL  AND F1.F1_SERIE = D1.D1_SERIE AND F1.D_E_L_E_T_= ' '*/

LEFT OUTER JOIN SDE010 DE ON DE.DE_DOC = D1.D1_DOC AND DE.DE_SERIE = D1.D1_SERIE AND DE.DE_FORNECE = D1.D1_FORNECE AND D1.D1_LOJA = DE.DE_LOJA 
AND D1.D1_FILIAL = DE.DE_FILIAL AND D1.D1_RATEIO = '1' AND D1.D1_ITEM = DE.DE_ITEMNF AND DE.D_E_L_E_T_=' ' AND D1.D1_CC = ' '

WHERE D1.D_E_L_E_T_=' ' AND D1.D1_EMISSAO BETWEEN :INICIO AND :FIM AND D1.D1_FILIAL BETWEEN :FILIAL_DE AND :FILIAL_ATE
AND (SELECT (F4.F4_DUPLIC) FROM SF4010 F4 WHERE F4.F4_CODIGO = D1.D1_TES AND F4.D_E_L_E_T_=' ' AND ROWNUM=1) = 'S'

;	