--SELECT * FROM SRA010 WHERE RA_MAT = :MATRICULA ;
--SELECT * FROM SR9010 WHERE R9_MAT IN :MATRICULA;
--SELECT * FROM SRB010 WHERE RB_MAT IN :MATRICULA;
--SELECT * FROM SRC010 WHERE RC_MAT IN :MATRICULA;
--SELECT * FROM SRZ010 WHERE RZ_MAT IN :MATRICULA;
--SELECT * FROM SPC010 WHERE PC_MAT = :MATRICULA;
--SELECT * FROM SPF010 WHERE PF_MAT = :MATRICULA;
--SELECT * FROM SRF010 WHERE RF_MAT = :MATRICULA;


UPDATE SRA010 SET D_E_L_E_T_='*', R_E_C_D_E_L_=R_E_C_N_O_ WHERE RA_MAT = '254377' ;

UPDATE SR9010 SET D_E_L_E_T_='*' WHERE R9_MAT = '254377' ;

UPDATE SRB010 SET D_E_L_E_T_='*',R_E_C_D_E_L_=R_E_C_N_O_ WHERE RB_MAT = '254377';

UPDATE SRC010 SET D_E_L_E_T_='*', R_E_C_D_E_L_=R_E_C_N_O_ WHERE RC_MAT = '254377';

UPDATE SRZ010 SET D_E_L_E_T_='*', R_E_C_D_E_L_=R_E_C_N_O_ WHERE RZ_MAT = '254377';

UPDATE SPC010 SET D_E_L_E_T_='*' WHERE PC_MAT = '254377';

UPDATE SPF010 SET D_E_L_E_T_='*', R_E_C_D_E_L_=R_E_C_N_O_ WHERE PF_MAT = '254377';

UPDATE SRF010 SET D_E_L_E_T_='*', R_E_C_D_E_L_=R_E_C_N_O_ WHERE RF_MAT = '254377';
