SELECT DISTINCT
E1_FILIAL FILIAL,

E1_PREFIXO PREFIXO,

E1_NUM TITULO,

E1_PARCELA PARCELA,

SUBSTR(E1_BAIXA,7,2)||'/'||SUBSTR(E1_BAIXA,5,2)||'/'||SUBSTR(E1_BAIXA,1,4) BAIXA,
SUBSTR(E1_BAIXA,7,2) DIA_BAIXA,
SUBSTR(E1_BAIXA,5,2) MES_BAIXA,
SUBSTR(E1_BAIXA,1,4) ANO_BAIXA,

SUBSTR(E1_EMISSAO,7,2)||'/'||SUBSTR(E1_EMISSAO,5,2)||'/'||SUBSTR(E1_EMISSAO,1,4) EMISSAO,
SUBSTR(E1_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E1_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E1_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E1_VENCTO,7,2)||'/'||SUBSTR(E1_VENCTO,5,2)||'/'||SUBSTR(E1_VENCTO,1,4) VENCIMENTO,
SUBSTR(E1_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E1_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E1_VENCTO,1,4) ANO_VENCIMENTO,

CASE WHEN EV_FILIAL IS NOT NULL THEN 'EV' ELSE 'E1' END TABELA,

E1_TIPO TIPO_TITULO,

CASE WHEN E1_SALDO = 0 THEN 'FINALIZADO' WHEN E1_SALDO > 0 AND E1_SALDO < E1_VALOR THEN 'PARCIAL' ELSE 'ABERTO' END STATUS,

E1_CLIENTE||'-'||E1_LOJA COD_FORNECEDOR,

(SELECT A1_NOME FROM SA1010 WHERE A1_COD = CASE WHEN EV_CLIFOR IS NULL THEN E1_CLIENTE ELSE EV_CLIFOR END AND A1_LOJA = CASE WHEN EV_LOJA IS NULL THEN E1_LOJA ELSE EV_LOJA END AND SA1010.D_E_L_E_T_=' ' AND ROWNUM = 1) FORNECEDOR,

E1_NATUREZ COD_NATUREZA,

(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = CASE WHEN EV_NATUREZ IS NULL THEN E1_NATUREZ ELSE EV_NATUREZ END AND SED010.D_E_L_E_T_=' ') NATUREZA,

/*CASE WHEN E1_SALDO = 0 THEN 'SIM' WHEN E1_SALDO >= 0 AND E1_SALDO < E1_VALOR THEN 'PARCIAL' ELSE 'NAO' END CONCILIADO,*/

0 TARIFA,

0 GLOSA,

ROUND(E1_DESCONT+E1_DECRESC * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) DESCONTO,

ROUND(E1_JUROS * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) JUROS,

ROUND(E1_MULTA * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) MULTA,

ROUND(E1_VALOR * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) VALOR_TILULO,

ROUND(E1_SALDO * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) A_RECEBER,

ROUND((E1_VALOR+E1_MULTA+E1_JUROS+E1_ACRESC-E1_DESCONT-E1_SALDO)* CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) RECEBIDO

FROM SE1010 

  LEFT OUTER JOIN SEV010
  ON EV_FILIAL = E1_FILIAL
  AND EV_NUM = E1_NUM
  AND EV_PREFIXO = E1_PREFIXO
  AND EV_PARCELA = E1_PARCELA
  AND EV_CLIFOR = E1_CLIENTE
  AND EV_TIPO = E1_TIPO
  AND E1_MULTNAT = '1'
  AND SEV010.D_E_L_E_T_=' '
  AND EV_RECPAG = 'R'  

WHERE SE1010.D_E_L_E_T_=' '
AND E1_FILORIG != ' '
AND E1_EMISSAO BETWEEN :DATA_INICIAL AND :DATA_FINAL
AND E1_PARCELA NOT IN('0','00')
AND E1_NUM = '000015618'


UNION


SELECT DISTINCT

E5_FILIAL FILIAL,

E5_PREFIXO PREFIXO,

E5_NUMERO TITULO,

E5_PARCELA PARCELA,

SUBSTR(E5_DATA,7,2)||'/'||SUBSTR(E5_DATA,5,2)||'/'||SUBSTR(E5_DATA,1,4) BAIXA,
SUBSTR(E5_DATA,7,2) DIA_BAIXA,
SUBSTR(E5_DATA,5,2) MES_BAIXA,
SUBSTR(E5_DATA,1,4) ANO_BAIXA,

SUBSTR(E1_EMISSAO,7,2)||'/'||SUBSTR(E1_EMISSAO,5,2)||'/'||SUBSTR(E1_EMISSAO,1,4) EMISSAO,
SUBSTR(E1_EMISSAO,7,2) DIA_EMISSAO,
SUBSTR(E1_EMISSAO,5,2) MES_EMISSAO,
SUBSTR(E1_EMISSAO,1,4) ANO_EMISSAO,

SUBSTR(E1_VENCTO,7,2)||'/'||SUBSTR(E1_VENCTO,5,2)||'/'||SUBSTR(E1_VENCTO,1,4) VENCIMENTO,
SUBSTR(E1_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(E1_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(E1_VENCTO,1,4) ANO_VENCIMENTO,

CASE WHEN EV_FILIAL IS NOT NULL THEN 'EV' WHEN E5_FILIAL IS NOT NULL THEN 'E5' ELSE 'E1' END TABELA,

E5_TIPO TIPO_TITULO,

CASE WHEN E1_SALDO = 0 THEN 'FINALIZADO' WHEN E1_SALDO > 0 AND E1_SALDO < E1_VALOR THEN 'PARCIAL' ELSE 'ABERTO' END STATUS,

E5_CLIFOR||'-'||E5_LOJA COD_FORNECEDOR,

(SELECT A1_NOME FROM SA1010 WHERE A1_COD = CASE WHEN EV_CLIFOR IS NULL THEN E5_CLIFOR ELSE E5_CLIFOR END AND A1_LOJA = CASE WHEN EV_LOJA IS NULL THEN E5_LOJA ELSE EV_LOJA END AND SA1010.D_E_L_E_T_=' ') FORNECEDOR,

E1_NATUREZ COD_NATUREZA,

(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = CASE WHEN EV_NATUREZ IS NULL THEN E1_NATUREZ ELSE EV_NATUREZ END AND SED010.D_E_L_E_T_=' ') NATUREZA,

/*CASE WHEN (E5_LOTE != ' ' OR E5_RECONC = 'x' OR E5_MOTBX IN('LIQ','TAC','GNR')) THEN 'SIM' ELSE 'NAO' END  CONCILIADO,*/

/*E5_TIPODOC, E5_MOTBX,E5_RECONC,E5_LOTE,*/

CASE WHEN E5_MOTBX = 'TAC' THEN ROUND(E5_VALOR,2) ELSE 0 END * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END AS TARIFA,

CASE WHEN E5_MOTBX = 'GNR' THEN ROUND(E5_VALOR,2) ELSE 0 END * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END AS GLOSA,

CASE WHEN E5_TIPODOC = 'DC' AND E1_DESCONT = 0 THEN ROUND(E5_VALOR * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) ELSE 0 END DESCONTO,

CASE WHEN E5_TIPODOC = 'JR' AND E1_JUROS = 0 THEN ROUND(E5_VLJUROS * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) ELSE 0 END JUROS,

CASE WHEN E5_TIPODOC = 'MT' AND E1_MULTA = 0 THEN ROUND(E5_VLMULTA * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END,2) ELSE 0 END MULTA,

/*E5_TIPODOC,E5_MOTBX,E5_RECONC, E5_LOTE,*/

0 VALOR_TILULO,

CASE WHEN (E5_RECONC = ' ' AND E5_MOTBX NOT IN('GNR','TAC')) THEN (ROUND(E5_VALOR,2)-E1_MULTA-E1_JUROS) ELSE 0 END * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END A_RECEBER,

(CASE WHEN (E5_RECONC = ' ' OR E5_MOTBX IN('GNR','TAC'))
           THEN ROUND(E5_VALOR,2)
      ELSE 0 
END * CASE WHEN EV_FILIAL IS NOT NULL THEN EV_PERC ELSE 1 END)*-1 RECEBIDO

FROM SE5010 

  LEFT OUTER JOIN SEV010
  ON EV_FILIAL = E5_FILIAL
  AND EV_NUM = E5_NUMERO
  AND EV_PREFIXO = E5_PREFIXO
  AND EV_PARCELA = E5_PARCELA
  AND EV_CLIFOR = E5_CLIFOR
  AND EV_LOJA = E5_LOJA
  AND EV_TIPO = E5_TIPO
  AND SEV010.D_E_L_E_T_=' '
  AND EV_RECPAG = 'R'
  
  LEFT OUTER JOIN SE1010
  ON E1_FILIAL = E5_FILIAL
  AND E1_NUM = E5_NUMERO
  AND E1_PREFIXO = E5_PREFIXO
  AND E1_PARCELA = E5_PARCELA
  AND E1_CLIENTE = E5_CLIFOR
  AND E1_LOJA = E5_LOJA
  AND E1_TIPO = E5_TIPO
  AND SE1010.D_E_L_E_T_=' '
  
WHERE 
  SE5010.D_E_L_E_T_=' '
  AND E5_RECPAG = 'R'
  AND E5_MOTBX IN ('GNR','TAC','NOR','CMP')
  AND E5_SITUACA != 'C'
  
  AND CASE WHEN (E5_LOTE = ' ' AND E5_RECONC = ' ') THEN 1
           WHEN E5_MOTBX IN('GNR','TAC') THEN 1
           WHEN (E5_LOTE = ' ' AND E5_RECONC = 'x') THEN 0
           WHEN (E5_LOTE != ' ' AND E5_RECONC = ' ') THEN 0
           ELSE 0
      END = 1 /*NAO CONCILIADO APENAS*/
      
  AND E5_TIPODOC IN ('BA','VL','CP')
  
  AND E5_FILIAL||E5_PREFIXO||E5_NUMERO IN (
  SELECT E1_FILIAL||E1_PREFIXO||E1_NUM FROM SE1010
      WHERE SE1010.D_E_L_E_T_=' '
      AND E1_FILORIG != ' '
      AND E1_EMISSAO BETWEEN :DATA_INICIAL AND :DATA_FINAL
      AND E1_PARCELA NOT IN('0','00'))
      /*AND CASE WHEN E5_TIPODOC IN('DC','JR','MT') AND (E1_JUROS > 0 OR E1_MULTA > 0 OR E1_DESCONT > 0) THEN 0 ELSE 1 END = 1 */
      AND E5_NUMERO = '000015618'
           

;