SELECT 
RR.RR_FILIAL FILIAL,
RR.RR_MAT MATRICULA,
RA.RA_NOMECMP FUNCIONARIO,
CASE WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '001' THEN '001-BANCO DO BRASIL' 
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '033' THEN '033-SANTANDER'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '104' THEN '104-CAIXA ECONOMICA FEDERAL'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '237' THEN '237-BRADESCO'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '399' THEN '399-HSBC'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '341' THEN '341-ITAU'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '777' THEN 'ORDEM DE PAGAMENTO' 
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '888' THEN 'FUNCIONARIO SEM CONTA'
WHEN SUBSTR(RA.RA_BCDEPSA,1,3) = '999' THEN 'CHEQUE'
 ELSE SUBSTR(RA.RA_BCDEPSA,1,3) END BANCO,
SUBSTR(RA.RA_BCDEPSA,4,7) AGENCIA,
RA.RA_CTDEPSA CONTA,
RR.RR_PD COD_VERBA,
(SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RR.RR_PD AND RV.D_E_L_E_T_=' ') VERBA,
RR.RR_TIPO3 TIPO,
RR.RR_VALOR VALOR,
SUBSTR(RR.RR_DATA,7,2)||'/'||SUBSTR(RR.RR_DATA,5,2)||'/'||SUBSTR(RR.RR_DATA,1,4) DATA,
SUBSTR(RR.RR_DATA,7,2) DIA,
SUBSTR(RR.RR_DATA,5,2) MES,
SUBSTR(RR.RR_DATA,1,4) ANO,

SUBSTR(RR.RR_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RR.RR_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RR.RR_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC,
RR.RR_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RR.RR_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,
SRH010.RH_DATABAS BASE_INICIAL,
SRH010.RH_DBASEAT BASE_FINAL

FROM SRR010 RR JOIN SRA010 RA ON RA.RA_MAT = RR.RR_MAT AND RR.RR_FILIAL = RA.RA_FILIAL AND RA.D_E_L_E_T_=' '

LEFT JOIN SRH010 ON RH_FILIAL = RR.RR_FILIAL AND RH_MAT = RR.RR_MAT AND RR.RR_TIPO3 = 'F' AND SRH010.RH_DATAINI BETWEEN :DATA_INICIAL AND :DATA_FINAL AND SRH010.D_E_L_E_T_=' '

WHERE RR.RR_PD IN('404','496','709','998','999')
 AND RR.D_E_L_E_T_=' ' AND RA.RA_CATFUNC!='A' AND RR.RR_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL