SELECT 

distinct

RA_FILIAL FILIAL,

1 CONTADOR,

RA_NOMECMP NOME,

RA_MAT MATRICULA,

RJ_CODCBO CBO,

RA_SINDICA COD_SINDICATO,
RCE_ENTSIN ENTIDADE_SINDICATO,
RCE_DESCRI SINDICATO,

RA_CIC CPF,

RA_RG RG,

RA_PIS PIS,

RA_NUMCP CARTEIRA,

RA_SERCP SERIE_CARTEIRA,

RA_TNOTRAB COD_TURNO,

RA_X_CPLAN CC_PLANISA,

Z3_X_DESC DESC_PLANISA,

CASE WHEN RA_TPCONTR = '1' THEN 'INDETERMINADO' WHEN RA_TPCONTR = '2' THEN 'DETERMINADO' ELSE '' END TIPO_CONTRIBUCAO,

R6_DESC TURNO,

CCH_PAIS PAIS_ORIGEM,

(SELECT X5_DESCRI FROM SX5010 WHERE X5_TABELA = '34' AND X5_CHAVE = RA_NACIONA AND ROWNUM = 1) NATURALIDADE,

QB_DESCRIC DEPARTAMENTO,

RA_ESTADO ESTADO,

RA_MUNICIP CIDADE,

RA_CEP CEP,

RA_ENDEREC ENDERECO,

RA_LOGRNUM NUMERO,

RA_BAIRRO BAIRRO,

RA_TELEFON TELEFONE,

RA_DDDFONE DDD,

RA_SEXO SEXO,

CASE WHEN RA_BRPDH = '1' THEN 'BENEFICIARIO REABILITADO'
WHEN RA_BRPDH = '2' THEN 'PORTADOR DE DEFICIENCIA HABILITADO'
ELSE 'NÃO APLICAVEL' END BR_PDH,

CASE WHEN RA_TPDEFFI = '0' THEN 'NÃO É DEFICIENTE'
WHEN RA_TPDEFFI = '1' THEN 'FISICA'
WHEN RA_TPDEFFI = '2' THEN 'AUDITIVA'
WHEN RA_TPDEFFI = '3' THEN 'VISUAL'
WHEN RA_TPDEFFI = '4' THEN 'INTELECTUAL (MENTAL)'
WHEN RA_TPDEFFI = '5' THEN 'MULTIPLA'
WHEN RA_TPDEFFI = '6' THEN 'REABILITADO'
ELSE '' END TIPO_DEFICIENCIA,

CASE WHEN SUBSTR(RA_BCDEPSA,1,3) = '001' THEN 'BANCO DO BRASIL' 
WHEN SUBSTR(RA_BCDEPSA,1,3) = '033' THEN 'SANTANDER'
WHEN SUBSTR(RA_BCDEPSA,1,3) = '104' THEN 'CAIXA ECONOMICA FEDERAL'
WHEN SUBSTR(RA_BCDEPSA,1,3) = '237' THEN 'BRADESCO'
WHEN SUBSTR(RA_BCDEPSA,1,3) = '399' THEN 'HSBC'
WHEN SUBSTR(RA_BCDEPSA,1,3) = '409' THEN 'ITAU' ELSE '' END BANCO,

CASE WHEN SUBSTR(RA_BCDEPSA,4,1)= '/' THEN RA_BCDEPSA ELSE SUBSTR(RA_BCDEPSA,1,3)||'/'||SUBSTR(RA_BCDEPSA,3,5) END BANCO_AGENCIA,
RA_CATFUNC CATEGORIA,

RA_CTDEPSA CONTA,
(SELECT X5_DESCRI FROM SX5010 WHERE X5_CHAVE = RA_GRINRAI AND X5_TABELA = '26' AND SX5010.D_E_L_E_T_=' ' AND ROWNUM = 1) ESCOLARIDADE,

RA_SALARIO SALARIO_BASE,
/*
(SELECT SUM(RD_VALOR) FROM SRD010 WHERE RD_HORAS != 0 AND RD_DATARQ = CASE WHEN (SELECT 1 FROM SRD010 WHERE RD_PD = '404' AND RD_MAT = RA_MAT AND RA_FILIAL = RD_FILIAL
AND RD_DATARQ = CASE WHEN TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') = '12' THEN TO_CHAR(ADD_MONTHS(sysdate,-12), 'YYYY') ELSE TO_CHAR(sysdate,'YYYY') END||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM')) = 1 
THEN EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-2), 'MM')
ELSE EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') END
AND RD_MAT = RA_MAT AND RD_PD IN('002','003','005','006','007','008','011','012','016','018','027','070','118','','HE1','HE2') AND RA_FILIAL = RD_FILIAL AND ROWNUM = 1)PROVENTOS,

(SELECT SUM(RD_VALOR) FROM SRD010 WHERE RD_HORAS != 0 AND RD_DATPGT BETWEEN '20150301' AND '20150331' AND RD_MAT = RA_MAT AND RD_PD NOT IN ('508','604','499','418','431')
AND (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) = '2'
AND (SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) NOT LIKE '%FERIAS%'
AND RA_FILIAL = RD_FILIAL )DESCONTOS,
*/
RA_HRSEMAN HORAS_SEMANAL,

RA_HRSMES HORAS_MES,

(SUBSTR(RA_NASC,7,2)||'/'||SUBSTR(RA_NASC,5,2)||'/'||SUBSTR(RA_NASC,1,4)) NASCIMENTO,
SUBSTR(RA_NASC,7,2) DIA_NASCIMENTO,
SUBSTR(RA_NASC,5,2) MES_NASCIMENTO,
SUBSTR(RA_NASC,1,4) ANO_NASCIMENTO,

(SUBSTR(RA_ADMISSA,7,2)||'/'||SUBSTR(RA_ADMISSA,5,2)||'/'||SUBSTR(RA_ADMISSA,1,4)) ADMISSAO,
SUBSTR(RA_ADMISSA,7,2) DIA_ADMISSAO,
SUBSTR(RA_ADMISSA,5,2) MES_ADMISSAO,
SUBSTR(RA_ADMISSA,1,4) ANO_ADMISSAO,


(SUBSTR(RA_DEMISSA,7,2)||'/'||SUBSTR(RA_DEMISSA,5,2)||'/'||SUBSTR(RA_DEMISSA,1,4)) DEMISSAO,
SUBSTR(RA_DEMISSA,7,2) DIA_DEMISSAO,
SUBSTR(RA_DEMISSA,5,2) MES_DEMISSAO,
SUBSTR(RA_DEMISSA,1,4) ANO_DEMISSAO,

RG_TIPORES COD_DEMISSAO,
CASE WHEN RA_DEMISSA != ' ' OR RA_SITFOLH = 'D' THEN (SELECT SUBSTR(RX_TXT,0,30) FROM SRX010 WHERE RX_COD = RG_TIPORES AND RX_TIP ='32' AND SRX010.D_E_L_E_T_=' ' AND ROWNUM = 1) ELSE ' ' END DESC_DEMISSAO,

RJ_DESC FUNCAO,

Q3_DESCSUM CARGO,

CASE WHEN RG_TIPORES IS NULL AND RA_SITFOLH = 'D' THEN 'TRANSFERIDO'
    WHEN RA_SITFOLH = ' ' THEN 'NORMAL'
    WHEN RA_SITFOLH = 'F' THEN 'FERIAS' 
    WHEN RA_SITFOLH = 'D' THEN 'DEMITIDO'
    WHEN RA_SITFOLH = 'A' THEN 'AFASTADO'
    WHEN RA_SITFOLH = 'T' THEN 'TRANSFERIDO' ELSE ' ' END SITUACAO_FOLHA,
    
    
CASE WHEN RA_SITFOLH = 'A' THEN (SELECT X5.X5_DESCRI AFASTAMENTO FROM SX5010 X5 WHERE X5_TABELA = '30' AND X5.X5_CHAVE = (SELECT AF.R8_TIPO FROM SR8010 AF WHERE RA_MAT = R8_MAT AND RA_FILIAL = R8_FILIAL AND RA_SITFOLH = 'A' AND ROWNUM = 1)AND ROWNUM=1 ) ELSE ' ' END AFASTAMENTO,
   
/*SUBSTR(RA_CC,1,2)||'.'||SUBSTR(RA_CC,3,3)||'.'||SUBSTR(RA_CC,6,3)||'.'||SUBSTR(RA_CC,9,4) CENTRO_CUSTO,*/

SUBSTR(RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA_CC,1,5)||'       ' AND D_E_L_E_T_=' ' AND ROWNUM = 1) LOCAL_CC,

SUBSTR(RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA_CC,1,8)||'    ' AND D_E_L_E_T_=' ' AND ROWNUM = 1) DEPTO_CC,

RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA_CC AND D_E_L_E_T_=' ' AND ROWNUM = 1) DESC_CC

FROM SRA010 

LEFT JOIN SRJ010 ON RJ_FUNCAO = RA_CODFUNC AND SRJ010.D_E_L_E_T_=' '
LEFT JOIN RCE010 ON RCE_CODIGO = RA_SINDICA AND RCE010.D_E_L_E_T_=' '
LEFT JOIN SZ3010 ON Z3_X_COD = RA_X_CPLAN AND RA_X_CPLAN !=' ' AND SZ3010.D_E_L_E_T_=' '
LEFT JOIN SR6010 ON R6_TURNO = RA_TNOTRAB AND SR6010.D_E_L_E_T_=' '
LEFT JOIN CCH010 ON CCH_CODIGO = RA_CPAISOR AND CCH010.D_E_L_E_T_=' '
LEFT JOIN SQB010 ON QB_DEPTO = RA_DEPTO AND SQB010.D_E_L_E_T_=' '
LEFT JOIN SRG010 ON RG_MAT = RA_MAT AND RG_FILIAL = RA_FILIAL AND SRG010.D_E_L_E_T_=' ' AND RG_DATADEM = RA_DEMISSA AND RA_DEMISSA != ' '
LEFT JOIN SQ3010 ON Q3_CARGO = RA_CARGO AND SQ3010.D_E_L_E_T_=' '

WHERE SRA010.D_E_L_E_T_= ' ' ORDER BY RA_FILIAL, RA_MAT;
