
SELECT RD_FILIAL FILIAL, RD_MAT MATRICULA, (SELECT RA_NOMECMP FROM SRA010 WHERE RD_MAT = RA_MAT AND RD_FILIAL = RA_FILIAL AND SRA010.D_E_L_E_T_=' ') FUNCIONARIO,RD_PD COD_VERBA, (SELECT RV_DESC FROM SRV010 WHERE RV_COD = RD_PD AND SRV010.D_E_L_E_T_=' ') VERBA, RD_TIPO1 TIPO, RD_HORAS HORAS, RD_VALOR VALOR,
SUBSTR(RD_DATARQ,5,2)||'/'||SUBSTR(RD_DATARQ,1,4) MES_REFERENCIA, TO_DATE(RD_DATPGT,'YYYYMMDD') PAGAMENTO, RD_CC CENTRO_CUSTO FROM SRD010 WHERE RD_DATARQ < '201501' AND RD_FILIAL = '11051';
