SELECT 
RC1_FILTIT FILIAL,

(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RC1_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RC1_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC,
(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RC1_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,

RC1_MAT MATRICULA,
(SELECT RA_NOMECMP FROM SRA010 WHERE RC1_MAT = RA_MAT AND RA_FILIAL = RC1_FILTIT AND SRA010.D_E_L_E_T_=' ') FUNCIONARIO,
RC1_PREFIX PREFIXO,
RC1_NUMTIT TITULO,
CASE WHEN RC1_INTEGR = '0' THEN 'NÃO INTEGRADO' WHEN RC1_INTEGR = '1' THEN 'INTEGRADO' WHEN RC1_INTEGR = '2' THEN 'INCONSISTENTE' ELSE '' END INTEGRACAO,
RC1_CODTIT COD_TITULO,
RC1_DESCRI DESCRICAO_TILUTO,
RC1_VALOR VALOR,
SUBSTR(RC1_EMISSA,7,2)||'/'||SUBSTR(RC1_EMISSA,5,2)||'/'||SUBSTR(RC1_EMISSA,1,4) EMISSAO,
SUBSTR(RC1_EMISSA,7,2) DIA_EMISSAO,
SUBSTR(RC1_EMISSA,5,2) MES_EMISSAO,
SUBSTR(RC1_EMISSA,1,4) ANO_EMISSAO,

SUBSTR(RC1_VENCTO,7,2)||'/'||SUBSTR(RC1_VENCTO,5,2)||'/'||SUBSTR(RC1_VENCTO,1,4) VENCIMENTO,
SUBSTR(RC1_VENCTO,7,2) DIA_VENCIMENTO,
SUBSTR(RC1_VENCTO,5,2) MES_VENCIMENTO,
SUBSTR(RC1_VENCTO,1,4) ANO_VENCIMENTO,

RC1_TIPO TIPO_TITULO,
RC1_NATURE NATUREZA,
(SELECT A2_NOME FROM SA2010 WHERE RC1_FORNEC = A2_COD AND RC1_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' ') FORNECEDOR,
(SELECT A2_BANCO FROM SA2010 WHERE RC1_FORNEC = A2_COD AND RC1_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' ') BANCO_FORN,
(SELECT A2_AGENCIA FROM SA2010 WHERE RC1_FORNEC = A2_COD AND RC1_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' ') AGENCIA_FORN,
(SELECT A2_NUMCON FROM SA2010 WHERE RC1_FORNEC = A2_COD AND RC1_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' ') CONTA_FORN

FROM RC1010

WHERE D_E_L_E_T_=' '

;