SELECT '11' CTD_FILIAL, 'C'||A1_COD||A1_LOJA CTD_ITEM,'2' CTD_CLASSE,' ' CTD_NORMAL, A1_NOME CTD_DESC01,' ' CTD_DESC02,' ' CTD_DESC03,' ' CTD_DESC04,' ' CTD_DESC05,'2' CTD_BLOQ,
' ' CTD_DTBLIN,' ' CTD_DTBLFI,'20150101' CTD_DTEXIS,' ' CTD_DTEXSF,'C'||A1_COD||A1_LOJA CTD_ITLP,' ' CTD_ITPON,' ' CTD_BOOK,'C' CTD_ITSUP,' ' CTD_RES,' ' CTD_CRGNV1,' ' CTD_CRGNV2,
' ' CTD_RGNV3,'2' CTD_CLOBRG,'1' CTD_ACCLVL,' ' CTD_ITVM,' ' CTD_ITRED,' ' CTD_ACATIV,' ' CTD_ATOBRG,' ' CTD_ACAT01,' ' CTD_AT01OB,' ' CTD_ACAT02,' ' CTD_AT02OB,' ' CTD_ACAT03,' ' CTD_AT03OB,
' ' CTD_ACAT04,' ' CTD_AT04OB,' ' CTD_TPO04,' ' CTD_TPO03,' ' CTD_TPO02,' ' CTD_TPO01,' ' D_E_L_E_T_,(SELECT MAX(R_E_C_N_O_)+1 FROM CTD010 WHERE CTD010.D_E_L_E_T_=' ') R_E_C_N_O_,
0 R_E_C_D_E_L_ FROM SA1010 LEFT OUTER JOIN CTD010 ON CTD_ITSUP = 'C' AND SUBSTR(CTD_ITEM,2,8) = A1_COD||A1_LOJA AND CTD010.D_E_L_E_T_=' ' 
WHERE SA1010.D_E_L_E_T_=' '  AND A1_X_ITEMC = ' ' AND A1_PESSOA != ' ';