SELECT * FROM AJ7010 WHERE AJ7_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AJ7_FILIAL AND AF8_PROJET = AJ7_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';
UPDATE AJ7010 SET D_E_L_E_T_='*',R_E_C_D_E_L_ = R_E_C_N_O_  WHERE AJ7_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AJ7_FILIAL AND AF8_PROJET = AJ7_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';

SELECT * FROM AFG010 WHERE AFG_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AFG_FILIAL AND AF8_PROJET = AFG_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';
UPDATE AFG010 SET D_E_L_E_T_='*',R_E_C_D_E_L_ = R_E_C_N_O_  WHERE AFG_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AFG_FILIAL AND AF8_PROJET = AFG_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';

SELECT * FROM AFN010 WHERE AFN_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AFN_FILIAL AND AF8_PROJET = AFN_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';
UPDATE AFN010 SET D_E_L_E_T_='*' WHERE AFN_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AFN_FILIAL AND AF8_PROJET = AFN_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';

SELECT * FROM AF9010 WHERE AF9_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AF9_FILIAL AND AF8_PROJET = AF9_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';
UPDATE AF9010 SET D_E_L_E_T_='*',R_E_C_D_E_L_ = R_E_C_N_O_ WHERE AF9_REVISA <> (SELECT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AF9_FILIAL AND AF8_PROJET = AF9_PROJET AND AF8010.D_E_L_E_T_=' ') AND D_E_L_E_T_=' ';