SELECT * FROM SEV010 WHERE EV_NUM = '0459/2014';

SELECT * FROM SEZ010 WHERE D_E_L_E_T_=' ' AND EZ_NUM = 'SUS 02-21' AND EZ_PARCELA = '02';

SELECT 

B1_COD CODIGO,
B1_DESC PRODUTO,
B1_TIPO TIPO,
B1_UM UNIDADE,
B1_GRUPO GRUPO,
B1__CSAUDE COD_CONTA_SAUDE,
(SELECT CT1_DESC01 FROM CT1010 WHERE D_E_L_E_T_=' ' AND CT1_CONTA = B1__CSAUDE) CONTA_SAUDE,
B1__CASSIS COD_CONTA_ASS,
(SELECT CT1_DESC01 FROM CT1010 WHERE D_E_L_E_T_=' ' AND CT1_CONTA = B1__CASSIS) CONTA_ASS,
B1__COUTRA COD_CONTA_OUTRA,
(SELECT CT1_DESC01 FROM CT1010 WHERE D_E_L_E_T_=' ' AND CT1_CONTA = B1__COUTRA) CONTA_OUTRA,
B1__NATURE COD_NATUREZA,
(SELECT ED_DESCRIC FROM SED010 WHERE B1__NATURE = ED_CODIGO AND SED010.D_E_L_E_T_=' ') NATUREZA

FROM SB1010 WHERE D_E_L_E_T_=' ';