SELECT A.E5_FILIAL FILIAL,
SUBSTR(A.E5_DATA,7,2)||'/'||SUBSTR(A.E5_DATA,5,2)||'/'||SUBSTR(A.E5_DATA,1,4) DATA,
A.E5_TIPO TIPO,
A.E5_VALOR VALOR, 
A.E5_NATUREZ COD_NATUREZA,
(SELECT ED_DESCRIC FROM SED010 WHERE A.E5_NATUREZ = ED_CODIGO AND SED010.D_E_L_E_T_=' ') NATUREZA,

A.E5_BANCO BANCO,
A.E5_AGENCIA AGENCIA,
A.E5_CONTA CONTA,

B.E5_BANCO BANCO_ORIGEM,
B.E5_AGENCIA AGENCIA_ORIGEM,
B.E5_CONTA CONTA_ORIGEM,

A.E5_DOCUMEN CHEQUE,
A.E5_RECPAG RECEBER_PAGAR,
CASE WHEN A.E5_RECONC = 'x' THEN 'SIM' ELSE 'NÃO' END CONCILIADO,
A.E5_BENEF BENEFICIARIO,
A.E5_HISTOR HISTORICO

FROM SE5010 A
JOIN SE5010 B ON
A.E5_FILIAL = B.E5_FILIAL
AND A.E5_DATA = B.E5_DATA
AND A.E5_DOCUMEN = B.E5_NUMCHEQ
AND B.E5_RECPAG = 'P'

WHERE A.E5_TIPODOC IN('TR') AND A.D_E_L_E_T_=' ' 
AND A.R_E_C_N_O_ IN (SELECT SE5010.R_E_C_N_O_ FROM SE5010 WHERE SE5010.E5_CONTA = A.E5_CONTA AND SE5010.E5_RECPAG = 'R' AND SE5010.D_E_L_E_T_=' ')
AND A.E5_CONTA IN ('13004185','00010696','27662')

ORDER BY A.E5_FILIAL, A.E5_VALOR, A.E5_BANCO, A.E5_AGENCIA, A.E5_CONTA;

