SELECT 
CNF_FILIAL FILIAL,
CNF_CONTRA CONTRATO,
CASE WHEN CN9_ESPCTR = '1' THEN (SELECT A2_NOME FROM SA2010 WHERE A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(CNF_FILIAL,1,2) = SUBSTR(A2_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ')
     ELSE (SELECT A1_NOME FROM SA1010 WHERE A1_COD||A1_LOJA = COALESCE(NULLIF(CNC_CLIENT||CNC_LOJACL,' '),CN9_CLIENT||CN9_LOJACL) AND SUBSTR(CNF_FILIAL,1,2) = SUBSTR(A1_FILIAL,1,2) AND SA1010.D_E_L_E_T_=' ') END CLIENTE_FORNECEDOR,
CNF_COMPET COMPETENCIA,
CNF_VLPREV VALOR_PREVISTO,
TO_DATE(CNF_DTVENC,'YYYYMMDD') VENCIMENTO
FROM CNF010
JOIN CN9010 ON CN9_NUMERO = CNF_CONTRA AND CN9_FILIAL = CNF_FILIAL AND CN9_REVISA = CNF_REVISA AND CN9010.D_E_L_E_T_=' '
LEFT JOIN CNC010 ON CNF_FILIAL = CNC_FILIAL AND CNF_CONTRA = CNC_NUMERO AND CNC_REVISA = CNF_REVISA AND CNC010.D_E_L_E_T_=' '
WHERE CNF_DTVENC BETWEEN '20190301'AND'20190331'
AND CNF_FILIAL BETWEEN ' ' AND '99999' 
AND CNF_CONTRA BETWEEN ' ' AND 'ZZZZZZZZZZZZZZZ' 
AND CNF010.D_E_L_E_T_=' '
AND CNF_SALDO <> 0
AND CN9_SITUAC IN ('05','07')
AND COALESCE(NULLIF(CNC_CODIGO||CNC_LOJA,' '),NULLIF(CNC_CLIENT||CNC_LOJACL,' '),NULLIF(CN9_CLIENT||CN9_LOJACL,' '),' ') BETWEEN ' ' AND 'ZZZZZZZZ'

UNION 

SELECT 
CN9_FILIAL FILIAL,
CN9_NUMERO CONTRATO,
CASE WHEN CN9_ESPCTR = '1' THEN (SELECT A2_NOME FROM SA2010 WHERE A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(CN9_FILIAL,1,2) = SUBSTR(A2_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ')
     ELSE (SELECT A1_NOME FROM SA1010 WHERE A1_COD||A1_LOJA = COALESCE(NULLIF(CN9_CLIENT||CN9_LOJACL,' '),NULLIF(CNC_CLIENT||CNC_LOJACL,' ')) AND SUBSTR(CN9_FILIAL,1,2) = SUBSTR(A1_FILIAL,1,2) AND SA1010.D_E_L_E_T_=' ') END CLIENTE_FORNECEDOR,
'INDETERMINADO' COMPETENCIA, --SUBSTR(TO_CHAR(SYSDATE,'YYYYMMDD'),5,2)||'/'||SUBSTR(TO_CHAR(SYSDATE,'YYYYMMDD'),1,4) COMPETENCIA,
CN9_VLINI VALOR_PREVISTO,
TO_DATE(TO_CHAR((SYSDATE),'YYYY')||TO_CHAR((SYSDATE),'MM')||SUBSTR(CN9_DTINIC,7,2),'YYYYMMDD') VENCIMENTO
FROM CN9010 
JOIN CNC010 ON CN9_FILIAL = CNC_FILIAL AND CN9_NUMERO = CNC_NUMERO AND CNC_REVISA = CN9_REVISA AND CNC010.D_E_L_E_T_=' '
WHERE CN9_UNVIGE NOT IN ('1','2','3') 
AND CN9010.D_E_L_E_T_=' ' 
AND CN9_DTINIC < '20190301' 
AND CN9_SITUAC IN ('05','07')
AND COALESCE(NULLIF(CNC_CODIGO||CNC_LOJA,' '),NULLIF(CNC_CLIENT||CNC_LOJACL,' '),NULLIF(CN9_CLIENT||CN9_LOJACL,' '),' ') BETWEEN ' ' AND 'ZZZZZZZZ'

ORDER BY FILIAL, CONTRATO, COMPETENCIA;


SELECT * FROM SE4010;
SELECT * FROM CNF010;
SELECT * FROM CNC010;


UPDATE CN9010 A SET A.CN9_X_CLFR = NVL((SELECT CASE WHEN B.CN9_ESPCTR = '1' THEN (SELECT A2_NOME FROM SA2010 WHERE A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(B.CN9_FILIAL,1,2) = SUBSTR(A2_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ' AND ROWNUM = 1)
     ELSE (SELECT A1_NOME FROM SA1010 WHERE A1_COD||A1_LOJA = CNC_CLIENT||CNC_LOJACL AND SUBSTR(B.CN9_FILIAL,1,2) = SUBSTR(A1_FILIAL,1,2) AND SA1010.D_E_L_E_T_=' ' AND ROWNUM = 1) END 
     FROM CN9010 B JOIN CNC010 ON B.CN9_FILIAL = CNC_FILIAL AND B.CN9_NUMERO = CNC_NUMERO AND CNC_REVISA = B.CN9_REVISA AND CNC010.D_E_L_E_T_=' ' WHERE B.CN9_SITUAC IN ('05','07') AND B.D_E_L_E_T_=' ' 
     AND B.CN9_FILIAL = A.CN9_FILIAL AND B.CN9_NUMERO = A.CN9_NUMERO AND B.CN9_REVISA = A.CN9_REVISA AND B.R_E_C_N_O_ = A.R_E_C_N_O_ AND ROWNUM = 1),' ')
WHERE A.D_E_L_E_T_=' ';

SELECT CN9_FILIAL, CN9_NUMERO, CN9_X_CLFR FROM CN9010 WHERE CN9_X_CLFR = ' ' AND D_E_L_E_T_=' ';

UPDATE CN9010 SET CN9_X_CLFR = NVL((SELECT A2_NOME FROM SA2010 JOIN CNC010 ON A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(CN9_FILIAL,1,2) = SUBSTR(A2_FILIAL,1,2) AND CNC010.D_E_L_E_T_ =' '
WHERE SA2010.D_E_L_E_T_=' ' AND CNC_FILIAL = CN9_FILIAL AND CN9_NUMERO = CNC_NUMERO AND CN9_REVISA = CNC_REVISA AND ROWNUM = 1),' ') 
WHERE CN9_ESPCTR = '1' AND CN9010.D_E_L_E_T_=' ' AND CN9_X_CLFR = ' ';

UPDATE CN9010 SET CN9_X_CLFR = NVL((SELECT A1_NOME FROM SA1010 JOIN CNC010 ON A1_COD||A1_LOJA = NVL(NULLIF(CNC_CLIENT||CNC_LOJACL,' '),CN9_CLIENT||CN9_LOJACL) AND SUBSTR(CN9_FILIAL,1,2) = SUBSTR(A1_FILIAL,1,2) AND CNC010.D_E_L_E_T_ =' '
WHERE SA1010.D_E_L_E_T_=' ' AND CNC_FILIAL = CN9_FILIAL AND CN9_NUMERO = CNC_NUMERO AND CN9_REVISA = CNC_REVISA AND ROWNUM = 1),' ') 
WHERE CN9_ESPCTR = '2' AND CN9010.D_E_L_E_T_=' ' AND CN9_X_CLFR = ' ';

SELECT * FROM CNC010;
