SELECT
DISTINCT
  MVB.E5_FILIAL FILIAL,
  MVB.E5_PREFIXO PREFIXO,
  MVB.E5_NUMERO TITULO,
  MVB.E5_NUMCHEQ NUM_CHEQUE,
  MVB.E5_PARCELA PARCELA, 
  MVB.E5_TIPO TIPO_TITULO,
  NVL(SEV.EV_NATUREZ,MVB.E5_NATUREZ)  COD_NATUREZA,
  MVB.E5_HISTOR HISTORICO, 
  COALESCE(MVB.R_E_C_N_O_,SEV.R_E_C_N_O_,CTP.R_E_C_N_O_,CTR.R_E_C_N_O_) RECNO,
  
  (SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = NVL(SEV.EV_NATUREZ,MVB.E5_NATUREZ)  AND D_E_L_E_T_=' ' AND ROWNUM = 1) NATUREZA,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN 'PAGAR' WHEN MVB.E5_RECPAG = 'R' THEN 'RECEBER' ELSE ' ' END MOVIMENTO,
  
   CASE WHEN MVB.E5_RECONC != ' ' THEN 'SIM' 
    ELSE 
      CASE WHEN MVB.E5_LOTE = ' ' THEN 'NÃO' 
      ELSE 'SIM'       
    END
  END CONCILIADO,
  
  CASE WHEN CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_CONTA END IN (SELECT AF8_X_CONT FROM AF8010 WHERE AF8010.D_E_L_E_T_=' ') THEN 'SIM' ELSE 'NÃO' END CONTA_PMS,
  
CASE WHEN MVB.E5_FORNECE != ' ' THEN (SELECT A2_NOME FROM SA2010 WHERE 
  MVB.E5_CLIFOR = A2_COD AND MVB.E5_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' 'AND ROWNUM=1) 
     WHEN MVB.E5_CLIENTE != ' ' THEN (SELECT A1_NOME FROM SA1010 WHERE
  MVB.E5_CLIFOR = A1_COD AND MVB.E5_LOJA =  A1_LOJA AND SA1010.D_E_L_E_T_=' ' AND ROWNUM=1)
     ELSE MVB.E5_BENEF
  END CLIENTE_FORNECEDOR,
  
  MVB.E5_BENEF BENEFICIARIO,
  
  ROUND(CASE WHEN MVB.E5_RECPAG = 'P' THEN MVB.E5_VALOR*-1 ELSE MVB.E5_VALOR END * NVL(SEV.EV_PERC,1),2) VALOR,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1) 
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP' THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1)
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_AGENCIA END AGENCIA,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP' THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_BANCO END BANCO,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP'  THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_CONTA END CONTA,
  
  MVB.E5_TIPODOC TIPO_DOC,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2) DIA_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2) MES_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) ANO_EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2) DIA_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2) MES_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) ANO_VENCIMENTO,
  	
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) VENCIMENTO,


  SUBSTR(MVB.E5_DTDISPO,7,2)||'/'||SUBSTR(MVB.E5_DTDISPO,5,2)||'/'||SUBSTR(MVB.E5_DTDISPO,1,4) BAIXA,
  SUBSTR(MVB.E5_DTDISPO,7,2) DIA_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,5,2) MES_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,1,4) ANO_BAIXA,
	1 CONTADOR,
	MVB.E5_LOTE LOTE,

CASE WHEN MVB.E5_HISTOR LIKE 'Baixa Automatica%' THEN 'SIM' ELSE 'NAO' END BAIXA_AUTOMATICA,
CASE WHEN /*MVB.E5_HISTOR LIKE '%Fatura%'*/ MVB.E5_PREFIXO = 'FT' OR MVB.E5_TIPO = 'FT' THEN 'SIM' ELSE 'NAO' END FATURA,

NVL(AF8.AF8_PROJET,'NAO')  PROJETO,
NVL(AF8.AF8_DESCRI,'NAO') DESCRICAO_PROJETO,
NVL(AF8.AF8_X_BANK,'NAO') BANCO_PROJETO,
NVL(AF8.AF8_X_AGEN,'NAO') AGENCIA_PROJETO,
NVL(AF8.AF8_X_CONT,'NAO') CONTA_PROJETO,
COALESCE(NULLIF(AFR.AFR_TAREFA,' '),NULLIF(AFN.AFN_TAREFA,' '),'NAO') TAREFA,
NVL(AF9.AF9_DESCRI,'NAO') DESCRICAO_TAREFA, '1' TABELA
/*,SEV.R_E_C_N_O_, SZ9.R_E_C_N_O_*/
 
FROM SE5010 MVB 
  LEFT OUTER JOIN SE2010 CTP ON CTP.E2_FILIAL = MVB.E5_FILIAL
    AND CTP.E2_NUM = MVB.E5_NUMERO AND CTP.E2_PARCELA = MVB.E5_PARCELA AND CTP.E2_PREFIXO = MVB.E5_PREFIXO AND CTP.E2_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'P'
    AND CTP.E2_FORNECE = MVB.E5_FORNECE AND CTP.E2_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '

  LEFT OUTER JOIN SE1010 CTR ON CTR.E1_FILIAL = MVB.E5_FILIAL
    AND CTR.E1_NUM = MVB.E5_NUMERO AND CTR.E1_PARCELA = MVB.E5_PARCELA AND CTR.E1_PREFIXO = MVB.E5_PREFIXO AND CTR.E1_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'R'
    AND CTR.E1_CLIENTE = MVB.E5_CLIENTE AND CTR.E1_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '
       
   LEFT JOIN SEV010 SEV ON
    SEV.EV_FILIAL = MVB.E5_FILIAL AND
    SEV.EV_NUM = MVB.E5_NUMERO AND
    SEV.EV_PREFIXO = MVB.E5_PREFIXO AND
    SEV.EV_CLIFOR = MVB.E5_CLIFOR AND
    SEV.EV_LOJA = MVB.E5_LOJA AND
    SEV.EV_RECPAG = MVB.E5_RECPAG AND
    SEV.D_E_L_E_T_=' '
    
  LEFT JOIN AFN010 AFN ON
    AFN.AFN_FILIAL = NVL(SEV.EV_FILIAL,MVB.E5_FILIAL) AND
    AFN.AFN_DOC = NVL(SEV.EV_NUM,MVB.E5_NUMERO) AND
    AFN.AFN_SERIE = NVL(SEV.EV_PREFIXO,MVB.E5_PREFIXO) AND
    AFN.AFN_FORNEC = NVL(SEV.EV_CLIFOR,MVB.E5_CLIFOR) AND
    AFN.AFN_LOJA = NVL(SEV.EV_LOJA,MVB.E5_LOJA) AND
    AFN.D_E_L_E_T_=' ' AND
    AFN.AFN_REVISA = (SELECT AF8_REVISA FROM AF8010 WHERE AFN_FILIAL = AF8_FILIAL AND AF8_PROJET = AFN_PROJET AND AF8010.D_E_L_E_T_=' ')
  /*
  JOIN SZ9010 SZ9 ON
     SZ9.Z9_PROJETO = AFN.AFN_PROJET AND
     SZ9.Z9_TAREFA = AFN.AFN_TAREFA AND
     SZ9.D_E_L_E_T_=' ' AND 
     SUBSTR(SZ9.Z9_FILIAL,3,3) = SUBSTR(AFN.AFN_FILIAL,3,3) AND
     SEV.EV_NATUREZ = SZ9.Z9_NATUREZ   
  */       

  LEFT JOIN AFR010 AFR ON
    AFR.AFR_FILIAL = NVL(SEV.EV_FILIAL,MVB.E5_FILIAL) AND
    AFR.AFR_NUM = NVL(SEV.EV_NUM,MVB.E5_NUMERO) AND
    AFR.AFR_PREFIX = NVL(SEV.EV_PREFIXO,MVB.E5_PREFIXO) AND
    AFR.AFR_FORNEC = NVL(SEV.EV_CLIFOR,MVB.E5_CLIFOR) AND
    AFR.AFR_LOJA = NVL(SEV.EV_LOJA,MVB.E5_LOJA) AND
    AFR.AFR_TIPO = NVL(SEV.EV_TIPO,MVB.E5_TIPO) AND
    AFR.D_E_L_E_T_=' ' 

  LEFT JOIN AF8010 AF8 ON
    AF8.AF8_FILIAL = NVL(AFR.AFR_FILIAL,AFN.AFN_FILIAL) AND
    AF8.AF8_PROJET = NVL(AFR.AFR_PROJET,AFN.AFN_PROJET) AND
    AF8.AF8_REVISA = NVL(AFR.AFR_REVISA,AFN.AFN_REVISA) AND
    AF8.D_E_L_E_T_= ' '
  
  LEFT JOIN AF9010 AF9 ON
    AF9.AF9_TAREFA = NVL(AFR.AFR_TAREFA,AFN.AFN_TAREFA) AND
    AF9_FILIAL = AF8_FILIAL AND
    AF9_PROJET = AF8_PROJET AND
    AF9_REVISA = AF8_REVISA AND
    AF9.D_E_L_E_T_=' '


  WHERE MVB.D_E_L_E_T_=' ' 
   AND MVB.E5_SITUACA != 'C'
       
   AND CASE WHEN CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND CASE WHEN CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND MVB.E5_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL AND AFN.AFN_DOC IS NULL 
   AND MVB.E5_FILIAL NOT IN ('11006','11010','11013','11014','11017','11023','11027','11028','11031','11032','11033','11035','11037','11042','11045','11047','11049','11052','11053','11055','11056','11057','11058','11059','11060')
   AND MVB.E5_MOTBX NOT IN ('DSD')
   AND MVB.E5_TIPODOC NOT IN ('CM')
   

SELECT * FROM AFR010 WHERE AFR_NUM = '000033999'; --11034	000007    	0002
SELECT * FROM AF8010 WHERE AF8_FILIAL = '11034';
SELECT * FROM SE5010 WHERE E5_NUMERO = '000033999';

UNION

SELECT
DISTINCT
  MVB.E5_FILIAL FILIAL,
  MVB.E5_PREFIXO PREFIXO,
  MVB.E5_NUMERO TITULO,
  MVB.E5_NUMCHEQ NUM_CHEQUE,
  MVB.E5_PARCELA PARCELA, 
  MVB.E5_TIPO TIPO_TITULO,
  NVL(SEV.EV_NATUREZ,MVB.E5_NATUREZ) COD_NATUREZA,
  MVB.E5_HISTOR HISTORICO, 
  COALESCE(MVB.R_E_C_N_O_,SEV.R_E_C_N_O_,CTP.R_E_C_N_O_,CTR.R_E_C_N_O_) RECNO,
  
  (SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = NVL(SEV.EV_NATUREZ,MVB.E5_NATUREZ) AND D_E_L_E_T_=' ' AND ROWNUM = 1) NATUREZA,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN 'PAGAR' WHEN MVB.E5_RECPAG = 'R' THEN 'RECEBER' ELSE ' ' END MOVIMENTO,
  
   CASE WHEN MVB.E5_RECONC != ' ' THEN 'SIM' 
    ELSE 
      CASE WHEN MVB.E5_LOTE = ' ' THEN 'NÃO' 
      ELSE 'SIM'       
    END
  END CONCILIADO,
  
CASE WHEN CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP'  THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_CONTA END IN (SELECT AF8_X_CONT FROM AF8010 WHERE AF8010.D_E_L_E_T_=' ') THEN 'SIM' ELSE 'NÃO' END CONTA_PMS,
  
CASE WHEN MVB.E5_FORNECE != ' ' THEN (SELECT A2_NOME FROM SA2010 WHERE 
  MVB.E5_CLIFOR = A2_COD AND MVB.E5_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' 'AND ROWNUM=1) 
     WHEN MVB.E5_CLIENTE != ' ' THEN (SELECT A1_NOME FROM SA1010 WHERE
  MVB.E5_CLIFOR = A1_COD AND MVB.E5_LOJA =  A1_LOJA AND SA1010.D_E_L_E_T_=' ' AND ROWNUM=1)
     ELSE MVB.E5_BENEF
  END CLIENTE_FORNECEDOR,
  
  MVB.E5_BENEF BENEFICIARIO,
  
  ROUND(CASE WHEN MVB.E5_RECPAG = 'P' THEN MVB.E5_VALOR*-1 ELSE MVB.E5_VALOR END * NVL(SEV.EV_PERC,1),2) VALOR,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1) 
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP'  THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1)
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_AGENCIA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_AGENCIA END AGENCIA,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP'  THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_BANCO FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_BANCO END BANCO,
  
  CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND TRIM(SE5010.E5_NUMERO) = TRIM(SUBSTR(MVB.E5_HISTOR,15,10)) AND SE5010.D_E_L_E_T_=' ' AND (SE5010.E5_RECONC = 'x' OR SE5010.E5_LOTE <> ' ' OR SE5010.E5_NUMCHEQ <> ' ') AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('VL','BA') AND ROWNUM = 1)
  WHEN E5_TIPODOC = 'CP' OR E5_MOTBX = 'CMP'  THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND SUBSTR(MVB.E5_DOCUMEN,18,6) = SE5010.E5_CLIFOR AND SUBSTR(MVB.E5_DOCUMEN,24,2) = SE5010.E5_LOJA AND SE5010.E5_NUMERO = SUBSTR(MVB.E5_DOCUMEN,4,9) AND SE5010.D_E_L_E_T_=' ' AND SUBSTR(MVB.E5_DOCUMEN,1,3) = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND E5_TIPODOC IN ('PA') AND ROWNUM = 1) 
  WHEN E5_MOTBX = 'PCC' THEN (SELECT SE5010.E5_CONTA FROM SE5010 WHERE MVB.E5_FILIAL = SE5010.E5_FILIAL AND MVB.E5_CLIFOR = SE5010.E5_CLIFOR AND MVB.E5_LOJA = SE5010.E5_LOJA AND SE5010.E5_NUMERO = MVB.E5_NUMERO AND SE5010.D_E_L_E_T_=' ' AND MVB.E5_PREFIXO = SE5010.E5_PREFIXO AND SE5010.E5_RECPAG = 'P' AND TRIM(MVB.E5_DOCUMEN) = TRIM(SE5010.E5_DOCUMEN) AND SE5010.E5_MOTBX = 'NOR' AND SE5010.E5_TIPODOC IN ('BA','VL') AND ROWNUM = 1)
  ELSE MVB.E5_CONTA END CONTA,
  
  MVB.E5_TIPODOC TIPO_DOC,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2) DIA_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2) MES_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) ANO_EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2) DIA_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2) MES_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) ANO_VENCIMENTO,
  	
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) VENCIMENTO,


  SUBSTR(MVB.E5_DTDISPO,7,2)||'/'||SUBSTR(MVB.E5_DTDISPO,5,2)||'/'||SUBSTR(MVB.E5_DTDISPO,1,4) BAIXA,
  SUBSTR(MVB.E5_DTDISPO,7,2) DIA_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,5,2) MES_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,1,4) ANO_BAIXA,
	1 CONTADOR,
	MVB.E5_LOTE LOTE,

CASE WHEN MVB.E5_HISTOR LIKE 'Baixa Automatica%' THEN 'SIM' ELSE 'NAO' END BAIXA_AUTOMATICA,
CASE WHEN /*MVB.E5_HISTOR LIKE '%Fatura%'*/ MVB.E5_PREFIXO = 'FT' OR MVB.E5_TIPO = 'FT' THEN 'SIM' ELSE 'NAO' END FATURA,

NVL(AF8.AF8_PROJET,NVL(AFR.AFR_PROJET,'NAO'))  PROJETO,
NVL(AF8.AF8_DESCRI,'NAO') DESCRICAO_PROJETO,
NVL(AF8.AF8_X_BANK,'NAO') BANCO_PROJETO,
NVL(AF8.AF8_X_AGEN,'NAO') AGENCIA_PROJETO,
NVL(AF8.AF8_X_CONT,'NAO') CONTA_PROJETO,
NVL(AFN.AFN_TAREFA,NVL(AFR.AFR_TAREFA,'NAO')) TAREFA,
NVL(AF9.AF9_DESCRI,'NAO') DESCRICAO_TAREFA, '2' TABELA
/*,SEV.R_E_C_N_O_, SZ9.R_E_C_N_O_*/
 
FROM SE5010 MVB 
  LEFT OUTER JOIN SE2010 CTP ON CTP.E2_FILIAL = MVB.E5_FILIAL
    AND CTP.E2_NUM = MVB.E5_NUMERO AND CTP.E2_PARCELA = MVB.E5_PARCELA AND CTP.E2_PREFIXO = MVB.E5_PREFIXO AND CTP.E2_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'P'
    AND CTP.E2_FORNECE = MVB.E5_FORNECE AND CTP.E2_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '

  LEFT OUTER JOIN SE1010 CTR ON CTR.E1_FILIAL = MVB.E5_FILIAL
    AND CTR.E1_NUM = MVB.E5_NUMERO AND CTR.E1_PARCELA = MVB.E5_PARCELA AND CTR.E1_PREFIXO = MVB.E5_PREFIXO AND CTR.E1_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'R'
    AND CTR.E1_CLIENTE = MVB.E5_CLIENTE AND CTR.E1_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '
       
   LEFT JOIN SEV010 SEV ON
    SEV.EV_FILIAL = MVB.E5_FILIAL AND
    SEV.EV_NUM = MVB.E5_NUMERO AND
    SEV.EV_PREFIXO = MVB.E5_PREFIXO AND
    SEV.EV_CLIFOR = MVB.E5_CLIFOR AND
    SEV.EV_LOJA = MVB.E5_LOJA AND
    SEV.EV_RECPAG = MVB.E5_RECPAG AND
    SEV.D_E_L_E_T_=' '
    
  LEFT JOIN AFN010 AFN ON
    AFN.AFN_FILIAL = NVL(SEV.EV_FILIAL,MVB.E5_FILIAL) AND
    AFN.AFN_DOC = NVL(SEV.EV_NUM,MVB.E5_NUMERO) AND
    AFN.AFN_SERIE = NVL(SEV.EV_PREFIXO,MVB.E5_PREFIXO) AND
    AFN.AFN_FORNEC = NVL(SEV.EV_CLIFOR,MVB.E5_CLIFOR) AND
    AFN.AFN_LOJA = NVL(SEV.EV_LOJA,MVB.E5_LOJA) AND
    AFN.D_E_L_E_T_=' ' AND
    AFN.AFN_REVISA = (SELECT AF8_REVISA FROM AF8010 WHERE AFN_FILIAL = AF8_FILIAL AND AF8_PROJET = AFN_PROJET AND AF8010.D_E_L_E_T_=' ')
  
  LEFT JOIN AFR010 AFR ON
    AFR.AFR_FILIAL = NVL(SEV.EV_FILIAL,MVB.E5_FILIAL) AND
    AFR.AFR_NUM = NVL(SEV.EV_NUM,MVB.E5_NUMERO) AND
    AFR.AFR_PREFIX = NVL(SEV.EV_PREFIXO,MVB.E5_PREFIXO) AND
    AFR.AFR_FORNEC = NVL(SEV.EV_CLIFOR,MVB.E5_CLIFOR) AND
    AFR.AFR_LOJA = NVL(SEV.EV_LOJA,MVB.E5_LOJA) AND
    AFR.AFR_TIPO = NVL(SEV.EV_TIPO,MVB.E5_TIPO) AND
    AFR.D_E_L_E_T_=' ' 
    
    JOIN SZ9010 SZ9 ON
     SZ9.Z9_PROJETO = NVL(AFN.AFN_PROJET,AFR.AFR_PROJET) AND
     SZ9.Z9_TAREFA = NVL(AFN.AFN_TAREFA,AFR.AFR_TAREFA) AND
     SZ9.D_E_L_E_T_=' ' AND 
     SUBSTR(SZ9.Z9_FILIAL,3,3) = SUBSTR(NVL(AFN.AFN_FILIAL,AFR.AFR_FILIAL),3,3) AND
     SEV.EV_NATUREZ = SZ9.Z9_NATUREZ 
    
  LEFT JOIN AF8010 AF8 ON
    AF8.AF8_FILIAL = NVL(AFN.AFN_FILIAL,AFR.AFR_FILIAL) AND
    AF8.AF8_PROJET = NVL(AFN.AFN_PROJET,AFR.AFR_PROJET) AND
    AF8.AF8_REVISA = NVL(AFN.AFN_REVISA,AFR.AFR_REVISA) AND
    AF8.D_E_L_E_T_= ' '
    
  LEFT JOIN AF9010 AF9 ON
  AF9.AF9_TAREFA = NVL(AFN.AFN_TAREFA,AFR.AFR_TAREFA) AND
  AF9_FILIAL = NVL(AFN_FILIAL,AFR.AFR_FILIAL) AND
  AF9_PROJET = NVL(AFN_PROJET,AFR.AFR_PROJET) AND
  AF9_REVISA = NVL(AFN.AFN_REVISA,AFR.AFR_REVISA) AND
  AF9.D_E_L_E_T_=' '

  WHERE MVB.D_E_L_E_T_=' ' 
   AND MVB.E5_SITUACA != 'C'
       
   AND CASE WHEN CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND CASE WHEN CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND MVB.E5_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND MVB.E5_FILIAL NOT IN ('11006','11010','11013','11014','11017','11023','11027','11028','11031','11032','11033','11035','11037','11042','11045','11047','11049','11052','11053','11055','11056','11057','11058','11059','11060')
   AND MVB.E5_MOTBX NOT IN ('DSD')
   AND MVB.E5_TIPODOC NOT IN ('CM')
   
   AND MVB.E5_NUMERO IN ('000334883','000335349','000335350','000337622','000334800','000337241','000336394','000335647','000336023','000336687','000337791','000337000','000335486')
   
   