SELECT 
  MVB.E5_FILIAL FILIAL,
  MVB.E5_PREFIXO PREFIXO,
  MVB.E5_NUMERO TITULO,
  MVB.E5_NUMCHEQ NUM_CHEQUE,
  MVB.E5_DOCUMEN DOCUMENTO,
  MVB.E5_PARCELA PARCELA, 
  MVB.E5_TIPO TIPO_TITULO,
  MVB.E5_NATUREZ COD_NATUREZA,
     
  MVB.E5_ORIGEM ORIGEM,
  MVB.E5_LOTE LOTE,

   CASE WHEN SE5.E5_VALOR IS NOT NULL OR MVB.E5_TIPODOC = 'ES' THEN 'SIM' ELSE 'NÃO' END 
   ESTORNADO, 
   
  (SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = MVB.E5_NATUREZ AND D_E_L_E_T_=' ' AND ROWNUM = 1) NATUREZA,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN 'PAGAR' WHEN MVB.E5_RECPAG = 'R' THEN 'RECEBER' ELSE ' ' END MOVIMENTO,
  CASE WHEN (MVB.E5_RECONC != ' ' OR MVB.E5_LOTE != ' ' OR MVB.E5_MOTBX = 'CH' OR MVB.E5_MOTBX = 'LIQ' ) AND SE5.E5_VALOR IS NULL THEN 'SIM' ELSE 'NÃO' END CONCILIADO,
  MVB.E5_MOTBX MOTIVO_BAIXA,
  MVB.E5_BENEF BENEFICIARIO,
  CASE WHEN MVB.E5_CLIENTE != ' ' THEN (SELECT A1_NOME FROM SA1010 WHERE A1_COD = MVB.E5_CLIENTE AND A1_LOJA = MVB.E5_LOJA AND SA1010.D_E_L_E_T_=' ' AND A1_FILIAL = '11') WHEN MVB.E5_FORNECE != ' ' THEN (SELECT A2_NOME FROM SA2010 WHERE A2_COD = MVB.E5_FORNECE AND A2_LOJA = MVB.E5_LOJA AND SA2010.D_E_L_E_T_=' ' AND A2_FILIAL = '11') ELSE MVB.E5_BENEF END FORNECEDOR,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN MVB.E5_VALOR*-1 ELSE MVB.E5_VALOR END VALOR,
  MVB.E5_AGENCIA AGENCIA,
  MVB.E5_BANCO BANCO,
  MVB.E5_CONTA CONTA,
  MVB.E5_TIPODOC TIPO_DOC,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,7,2) DIA_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,5,2) MES_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,1,4) ANO_EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_EMISSAO ELSE '' END,1,4) EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,7,2) DIA_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,5,2) MES_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,1,4) ANO_VENCIMENTO,
  	
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE '' END,1,4) VENCIMENTO,


  SUBSTR(MVB.E5_DTDISPO,7,2)||'/'||SUBSTR(MVB.E5_DTDISPO,5,2)||'/'||SUBSTR(MVB.E5_DTDISPO,1,4) BAIXA,
  SUBSTR(MVB.E5_DTDISPO,7,2) DIA_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,5,2) MES_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,1,4) ANO_BAIXA,

  MVB.E5_HISTOR HISTORICO

FROM SE5010 MVB 
  LEFT OUTER JOIN SE2010 CTP ON CTP.E2_FILIAL = MVB.E5_FILIAL
    AND CTP.E2_NUM = MVB.E5_NUMERO AND CTP.E2_PARCELA = MVB.E5_PARCELA AND CTP.E2_PREFIXO = MVB.E5_PREFIXO AND CTP.E2_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'P'
    AND CTP.E2_FORNECE = MVB.E5_FORNECE AND CTP.E2_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '

  LEFT OUTER JOIN SE1010 CTR ON CTR.E1_FILIAL = MVB.E5_FILIAL
    AND CTR.E1_NUM = MVB.E5_NUMERO AND CTR.E1_PARCELA = MVB.E5_PARCELA AND CTR.E1_PREFIXO = MVB.E5_PREFIXO AND CTR.E1_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'R'
    AND CTR.E1_CLIENTE = MVB.E5_CLIENTE AND CTR.E1_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '
    
    LEFT OUTER JOIN SE5010 SE5 ON MVB.E5_FILIAL||MVB.E5_BANCO||MVB.E5_AGENCIA||MVB.E5_CONTA||MVB.E5_NUMCHEQ||MVB.E5_LOTE||MVB.E5_DATA||MVB.E5_VALOR
    = SE5.E5_FILIAL||SE5.E5_BANCO||SE5.E5_AGENCIA||SE5.E5_CONTA||SE5.E5_NUMCHEQ||SE5.E5_LOTE||SE5.E5_DATA||SE5.E5_VALOR
    AND MVB.E5_PREFIXO||MVB.E5_NUMERO||MVB.E5_PARCELA||MVB.E5_CLIFOR||MVB.E5_LOJA = SE5.E5_PREFIXO||SE5.E5_NUMERO||SE5.E5_PARCELA||SE5.E5_CLIFOR||SE5.E5_LOJA
    AND SE5.E5_TIPODOC IN ('ES','EC') AND SE5.D_E_L_E_T_=' ' AND SE5.E5_SITUACA <> 'C'
    
 
WHERE MVB.D_E_L_E_T_=' ' AND MVB.E5_DATA BETWEEN :DATA_INICIO AND :DATA_FINAL AND MVB.E5_SITUACA <> 'C' /*AND MVB.E5_NUMERO = 'BE2017293'*/