SELECT
DISTINCT
  MVB.E5_FILIAL FILIAL,
  MVB.E5_PREFIXO PREFIXO,
  MVB.E5_NUMERO TITULO,
  MVB.E5_NUMCHEQ NUM_CHEQUE,
  MVB.E5_PARCELA PARCELA, 
  MVB.E5_TIPO TIPO_TITULO,
  MVB.E5_NATUREZ COD_NATUREZA,
  MVB.E5_HISTOR HISTORICO, 
  CASE WHEN MVB.R_E_C_N_O_ IS NOT NULL THEN MVB.R_E_C_N_O_ ELSE CASE WHEN CTR.R_E_C_N_O_ IS NULL THEN CTP.R_E_C_N_O_ ELSE CTR.R_E_C_N_O_ END END RECNO,
  
  (SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = MVB.E5_NATUREZ AND D_E_L_E_T_=' ' AND ROWNUM = 1) NATUREZA,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN 'PAGAR' WHEN MVB.E5_RECPAG = 'R' THEN 'RECEBER' ELSE ' ' END MOVIMENTO,
  
   CASE WHEN MVB.E5_RECONC != ' ' THEN 'SIM' 
    ELSE 
      CASE WHEN MVB.E5_LOTE = ' ' THEN 'NÃO' 
      ELSE 'SIM'       
    END
  END CONCILIADO,
  
  CASE WHEN MVB.E5_RECPAG = 'P' THEN (SELECT A2_NOME FROM SA2010 WHERE 
  MVB.E5_CLIFOR||MVB.E5_LOJA = A2_COD AND MVB.E5_LOJA = A2_LOJA AND SA2010.D_E_L_E_T_=' 'AND ROWNUM=1) 
  ELSE (SELECT A1_NOME FROM SA1010 WHERE
  MVB.E5_CLIFOR||MVB.E5_LOJA = A1_COD||A1_LOJA AND SA1010.D_E_L_E_T_=' ' AND ROWNUM=1) END CLIENTE_FORNECEDOR, 
  
  MVB.E5_BENEF BENEFICIARIO,
  CASE WHEN MVB.E5_RECPAG = 'P' THEN MVB.E5_VALOR*-1 ELSE MVB.E5_VALOR END VALOR,
  MVB.E5_AGENCIA AGENCIA,
  MVB.E5_BANCO BANCO,
  MVB.E5_CONTA CONTA,
  MVB.E5_TIPODOC TIPO_DOC,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2) DIA_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2) MES_EMISSAO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) ANO_EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END,1,4) EMISSAO,

  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2) DIA_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2) MES_VENCIMENTO,
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' AND CTP.E2_VENCTO IS NOT NULL THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' AND CTR.E1_VENCTO IS NOT NULL THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) ANO_VENCIMENTO,
  	
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,7,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,5,2)||'/'||
  SUBSTR(CASE WHEN MVB.E5_RECPAG = 'P' THEN CTP.E2_VENCTO WHEN MVB.E5_RECPAG = 'R' THEN CTR.E1_VENCTO ELSE MVB.E5_DTDISPO END,1,4) VENCIMENTO,


  SUBSTR(MVB.E5_DTDISPO,7,2)||'/'||SUBSTR(MVB.E5_DTDISPO,5,2)||'/'||SUBSTR(MVB.E5_DTDISPO,1,4) BAIXA,
  SUBSTR(MVB.E5_DTDISPO,7,2) DIA_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,5,2) MES_BAIXA,
  SUBSTR(MVB.E5_DTDISPO,1,4) ANO_BAIXA,
	1 CONTADOR,
	MVB.E5_LOTE LOTE,

CASE WHEN MVB.E5_HISTOR LIKE 'Baixa Automatica%' THEN 'SIM' ELSE 'NAO' END BAIXA_AUTOMATICA,
CASE WHEN MVB.E5_HISTOR LIKE '%Fatura%' THEN 'SIM' ELSE 'NAO' END FATURA

 
FROM SE5010 MVB 
  LEFT OUTER JOIN SE2010 CTP ON CTP.E2_FILIAL = MVB.E5_FILIAL
    AND CTP.E2_NUM = MVB.E5_NUMERO AND CTP.E2_PARCELA = MVB.E5_PARCELA AND CTP.E2_PREFIXO = MVB.E5_PREFIXO AND CTP.E2_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'P'
    AND CTP.E2_FORNECE = MVB.E5_FORNECE AND CTP.E2_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '

  LEFT OUTER JOIN SE1010 CTR ON CTR.E1_FILIAL = MVB.E5_FILIAL
    AND CTR.E1_NUM = MVB.E5_NUMERO AND CTR.E1_PARCELA = MVB.E5_PARCELA AND CTR.E1_PREFIXO = MVB.E5_PREFIXO AND CTR.E1_TIPO = MVB.E5_TIPO AND MVB.E5_RECPAG = 'R'
    AND CTR.E1_CLIENTE = MVB.E5_CLIENTE AND CTR.E1_LOJA = MVB.E5_LOJA AND CTP.D_E_L_E_T_=' '
    
  WHERE MVB.D_E_L_E_T_=' ' AND 
  
	   (CASE WHEN (SELECT E5_TIPODOC FROM SE5010 WHERE E5_NUMERO = MVB.E5_NUMERO AND E5_PREFIXO = MVB.E5_PREFIXO AND MVB.E5_NUMCHEQ = E5_NUMCHEQ AND MVB.E5_SEQ = E5_SEQ
    			  AND D_E_L_E_T_=' ' AND E5_FILIAL = MVB.E5_FILIAL AND MVB.E5_FORNECE = E5_FORNECE AND E5_LOJA = MVB.E5_LOJA AND E5_BANCO = MVB.E5_BANCO AND E5_AGENCIA = MVB.E5_AGENCIA
        		  AND E5_CONTA = MVB.E5_CONTA AND E5_RECPAG != MVB.E5_RECPAG AND E5_DATA = MVB.E5_DATA AND E5_PARCELA = MVB.E5_PARCELA AND E5_VALOR = MVB.E5_VALOR AND MVB.E5_DTDIGIT = E5_DTDIGIT AND E5_TIPODOC IN('ES','EC','CA') AND ROWNUM=1) != ' ' 
  	   THEN 'SIM'
  	   ELSE 'NÃO'
       END) = 'NÃO' 
       
   AND CASE WHEN CTP.E2_EMISSAO IS NOT NULL THEN CTP.E2_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND CASE WHEN CTR.E1_EMISSAO IS NOT NULL THEN CTR.E1_EMISSAO ELSE MVB.E5_DATA END BETWEEN :DATA_INICIAL AND :DATA_FINAL
   AND MVB.E5_DATA BETWEEN :DATA_INICIAL AND :DATA_FINAL
;

SELECT * FROM SE5010 WHERE E5_CONTA = '00000456' AND E5_VALOR = 342;
SELECT * FROM SE5010 WHERE E5_CONTA = '00000456' AND E5_LOTE = '00001180';

SELECT * FROM SE5010 WHERE E5_VALOR = 2079.88;

