SELECT C7_FILIAL FILIAL_
	,COALESCE(AJ7_PROJET, AFN_PROJET) PROJETO
	,COALESCE(AJ7_TAREFA, AFN_TAREFA) TAREFA
	,C7_EMISSAO
	,C7_NUM
	,D1_DOC
	,D1_EMISSAO
	,SUM(C7_TOTAL) VALPED
	,SUM(D1_TOTAL - D1_VALDESC) VALNOT
	,SE2.R_E_C_N_O_ RECSE2
	,E2_PARCELA
	,E2_TIPO
	,E2_PREFIXO
	,E2_FORNECE
	,E2_LOJA
	,A2_NOME
	,CASE 
		WHEN SUM(DISTINCT EV_PERC) > 0
			THEN MAX(E2_VALOR) * SUM(DISTINCT EV_PERC)
		ELSE MAX(E2_VALOR)
		END E2_VALOR
	,SUM(DISTINCT EV_PERC) EV_PERC
	,AF8_DESCRI
	,AF9_DESCRI
	,COALESCE((
			SELECT B.C7_RESIDUO
			FROM SC7010 B
			WHERE B.C7_FILIAL = SC7.C7_FILIAL
				AND B.C7_NUM = SC7.C7_NUM
				AND B.D_E_L_E_T_ = ' '
				AND B.C7_RESIDUO = 'S'
				AND ROWNUM = 1
			), ' ') RESIDUO
	,CASE 
		WHEN SUM(D1_VALDESC) > 0
			THEN 'S'
		ELSE ' '
		END DESCONTO
FROM SC7010 SC7
JOIN SA2010 SA2 ON A2_FILIAL = '     '
	AND SA2.D_E_L_E_T_ <> '*'
	AND C7_FORNECE = A2_COD
	AND C7_LOJA = A2_LOJA
LEFT JOIN AJ7010 AJ7 ON C7_FILIAL = AJ7_FILIAL
	AND AJ7.D_E_L_E_T_ <> '*'
	AND C7_NUM = AJ7_NUMPC
	AND C7_ITEM = AJ7_ITEMPC
	AND AJ7.AJ7_PROJET BETWEEN '000015    '
		AND '000015    '
LEFT JOIN SD1010 SD1 ON C7_FILIAL = D1_FILIAL
	AND SD1.D_E_L_E_T_ <> '*'
	AND C7_NUM = D1_PEDIDO
	AND C7_ITEM = D1_ITEMPC
LEFT JOIN AFN010 AFN ON AFN_FILIAL = D1_FILIAL
	AND AFN.D_E_L_E_T_ <> '*'
	AND AFN_DOC = D1_DOC
	AND AFN_ITEM = D1_ITEM
	AND AFN_SERIE = D1_SERIE
	AND AFN_FORNEC = D1_FORNECE
	AND AFN_LOJA = D1_LOJA
	AND AFN_PROJET BETWEEN '000015    '
		AND '000015    '
JOIN AF8010 AF8 ON COALESCE(AJ7_FILIAL, AFN_FILIAL) = AF8_FILIAL
	AND AF8.D_E_L_E_T_ <> '*'
	AND COALESCE(AJ7_PROJET, AFN_PROJET) = AF8_PROJET
JOIN AF9010 AF9 ON COALESCE(AJ7_FILIAL, AFN_FILIAL) = AF9_FILIAL
	AND AF9.D_E_L_E_T_ <> '*'
	AND COALESCE(AJ7_PROJET, AFN_PROJET) = AF9_PROJET
	AND COALESCE(AJ7_TAREFA, AFN_TAREFA) = AF9_TAREFA
	AND AF9_REVISA = AF8_REVISA
LEFT JOIN SE2010 SE2 ON E2_FILIAL = D1_FILIAL
	AND SE2.D_E_L_E_T_ <> '*'
	AND (
		(
			D1_SERIE = E2_PREFIXO
			AND D1_DOC = E2_NUM
			AND D1_FORNECE = E2_FORNECE
			AND D1_LOJA = E2_LOJA
			)
		OR (
			E2_TIPO IN (
				'TX'
				,'INS'
				,'ISS'
				)
			AND E2_TITPAI LIKE '%' || D1_SERIE || D1_DOC || '%'
			AND E2_TITPAI LIKE '%' || D1_FORNECE || D1_LOJA || '%'
			)
		)
LEFT JOIN SZ9010 SZ9 ON Z9_FILIAL = D1_FILIAL
	AND SZ9.D_E_L_E_T_ <> '*'
	AND D1__NATURE = Z9_NATUREZ
	AND COALESCE(AJ7_PROJET, AFN_PROJET) = Z9_PROJETO
LEFT JOIN SEV010 SEV ON EV_FILIAL = D1_FILIAL
	AND SEV.D_E_L_E_T_ <> '*'
	AND SEV.EV_PREFIXO = SD1.D1_SERIE
	AND SEV.EV_NUM = SD1.D1_DOC
	AND SEV.EV_CLIFOR = SD1.D1_FORNECE
	AND SEV.EV_LOJA = SD1.D1_LOJA
	AND SE2.E2_PARCELA = SEV.EV_PARCELA
	AND SEV.EV_NATUREZ = Z9_NATUREZ
WHERE SC7.D_E_L_E_T_ <> '*'
	AND SC7.C7_FILIAL BETWEEN '11002'
		AND '11002'
	AND SC7.C7_EMISSAO BETWEEN '20200701'
		AND '20200731'
        AND C7_NUM = '909951'
GROUP BY C7_FILIAL
	,COALESCE(AJ7_PROJET, AFN_PROJET)
	,AF8_DESCRI
	,COALESCE(AJ7_TAREFA, AFN_TAREFA)
	,AF9_DESCRI
	,C7_EMISSAO
	,C7_NUM
	,D1_DOC
	,D1_EMISSAO
	,E2_PREFIXO
	,SE2.R_E_C_N_O_
	,E2_PARCELA
	,E2_TIPO
	,E2_PREFIXO
	,E2_FORNECE
	,E2_LOJA
	,A2_NOME
ORDER BY C7_FILIAL
	,PROJETO
	,TAREFA
	,C7_EMISSAO
	,C7_NUM
	,D1_DOC
;

SELECT * FROM SC7010 WHERE C7_NUM = '909951';
SELECT * FROM SD2010;