
SELECT C7_FILIAL FILIAL,
C7_PRODUTO COD_PRODUTO,
B1_DESC PRODUTO,
C7_QUANT QUANTIDADE,
C7_PRECO PRECO_UNIT, 
C7_TOTAL TOTAL,
C7_NUMSC SOLICITACAO,
C7_FORNECE COD_FORNECEDOR,
C7_CC CENTRO_CUSTO, 
TO_DATE(C7_EMISSAO,'YYYYMMDD') EMISSAO ,
B1__NATURE COD_NATUREZ,
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = B1__NATURE AND ED_FILIAL = '11' AND SED010.D_E_L_E_T_=' ') NATUREZA,
AJ7_PROJET PROJETO,
AJ7_TAREFA TAREFA,
(SELECT AF8_DESCRI FROM AF8010 WHERE AF8_PROJET = AJ7_PROJET AND AF8_FILIAL = AJ7_FILIAL AND AF8010.D_E_L_E_T_=' ') DESCRICAO_PROJETO

FROM SC7010 JOIN SB1010 ON B1_COD = C7_PRODUTO AND SB1010.D_E_L_E_T_=' ' 
JOIN AJ7010 ON AJ7_NUMPC = C7_NUM AND AJ7_FILIAL = C7_FILIAL AND AJ7_ITEMPC = C7_ITEM AND AJ7010.D_E_L_E_T_=' ' 
WHERE SC7010.D_E_L_E_T_=' ' AND C7_EMISSAO > '20160101'
ORDER BY C7_FILIAL, C7_NUM, C7_ITEM
;