SELECT 
RQ.RQ_FILIAL,
RQ.RQ_MAT,
(SELECT RA_NOMECMP FROM SRA010 WHERE RA_MAT = RQ.RQ_MAT AND RA_FILIAL = RQ.RQ_FILIAL AND D_E_L_E_T_=' ') FUNC,
RQ.RQ_ORDEM,
RQ.RQ_NOME,
SUBSTR(RQ.RQ_BCDEPBE,1,3) BANCO,
SUBSTR(RQ.RQ_BCDEPBE,4,7) AGENCIA,
RQ.RQ_CTDEPBE CONTA,
RQ.RQ_VALFIXO,
RQ.RQ_PERCENT,
RQ.RQ_NRSLMIN,

SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC,
RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,

ROUND(CASE 
WHEN RQ.RQ_VALFIXO = 0 AND (SELECT COUNT(RD_PD) FROM SRD010 WHERE RD_DATARQ = :DATA_ARQUIVO AND (RD_PD IN ('450','453') OR RD_PD IN ('454','455') OR RD_PD IN ('492','493')) AND D_E_L_E_T_=' ' AND RD_MAT = RQ.RQ_MAT) =1
      THEN (SUM(RD_VALOR)*RQ.RQ_PERCENT)/(SELECT SUM(RQ_PERCENT) FROM SRQ010 WHERE RQ_MAT = RQ.RQ_MAT AND RQ_FILIAL = RQ.RQ_FILIAL AND D_E_L_E_T_=' ' GROUP BY RQ_MAT)
      
WHEN RQ.RQ_VALFIXO = 0 AND RQ.RQ_NRSLMIN != 0 AND (SELECT COUNT(RD_PD) FROM SRD010 WHERE RD_DATARQ = :DATA_ARQUIVO AND (RD_PD IN ('450','453') OR RD_PD IN ('454','455') OR RD_PD IN ('492','493')) AND D_E_L_E_T_=' ' AND RD_MAT = RQ.RQ_MAT) =1
      THEN (SUM(RD_VALOR)*(RQ.RQ_NRSLMIN*100))/RQ.RQ_PERCENT    
      
WHEN RQ.RQ_VALFIXO = 0 AND RQ.RQ_NRSLMIN != 0 AND (SELECT COUNT(RD_PD) FROM SRD010 WHERE RD_DATARQ = :DATA_ARQUIVO AND (RD_PD IN ('450','453') OR RD_PD IN ('454','455') OR RD_PD IN ('492','493')) AND D_E_L_E_T_=' ' AND RD_MAT = RQ.RQ_MAT) >1
      THEN (SELECT (RD_VALOR) FROM SRD010 WHERE RD_MAT = RQ.RQ_MAT AND RD_DATARQ = :DATA_ARQUIVO AND (RD_PD  ='454' OR RD_PD = '455' OR  RD_PD = '493') AND D_E_L_E_T_=' ' AND RQ.RQ_ORDEM = '02')
      
WHEN RQ.RQ_VALFIXO = 0 AND (SELECT COUNT(RD_PD) FROM SRD010 WHERE RD_DATARQ = :DATA_ARQUIVO AND (RD_PD IN ('450','453') OR RD_PD IN ('454','455') OR RD_PD IN ('492','493')) AND D_E_L_E_T_=' ' AND RD_MAT = RQ.RQ_MAT) >1
      THEN (SUM(RD_VALOR)*RQ.RQ_PERCENT)/(SELECT SUM(RQ_PERCENT) FROM SRQ010 WHERE RQ_MAT = RQ.RQ_MAT AND RQ_FILIAL = RQ.RQ_FILIAL AND D_E_L_E_T_=' ' GROUP BY RQ_MAT)
      

WHEN RQ.RQ_VALFIXO = 0 AND (SELECT COUNT(RD_PD) FROM SRD010 WHERE RD_DATARQ = :DATA_ARQUIVO AND D_E_L_E_T_=' ' AND RD_MAT = RQ.RQ_MAT AND RD_PD = '530') = 1
      THEN (SUM(RD_VALOR)*RQ.RQ_PERCENT)/(SELECT SUM(RQ_PERCENT) FROM SRQ010 WHERE RQ_MAT = RQ.RQ_MAT AND RQ_FILIAL = RQ.RQ_FILIAL AND D_E_L_E_T_=' ' GROUP BY RQ_MAT)
      
      
ELSE RQ.RQ_VALFIXO END,2) VALOR

FROM SRQ010 RQ

LEFT JOIN SRD010 RD ON RQ.RQ_MAT = RD.RD_MAT
AND RQ.D_E_L_E_T_=' ' AND RQ.RQ_SEQUENC='01'
AND RD.RD_FILIAL = RQ.RQ_FILIAL
AND RD.RD_DATARQ = :DATA_ARQUIVO
AND RD.RD_PD IN ('450','453','454','455','492','493','530')
AND RQ.RQ_VALFIXO = 0
AND RD.D_E_L_E_T_=' '

JOIN SRA010 RA ON RA.RA_MAT = RQ.RQ_MAT AND RA.RA_FILIAL = RQ.RQ_FILIAL AND RA.D_E_L_E_T_=' '

WHERE RQ.D_E_L_E_T_=' ' AND RQ.RQ_NOME != ' ' 

GROUP BY RQ.RQ_FILIAL,
RA.RA_CC,
RQ.RQ_MAT,
RQ.RQ_ORDEM,
RQ.RQ_NRSLMIN,
RQ.RQ_NOME,
RQ.RQ_VALFIXO,
RQ.RQ_PERCENT,
RQ.RQ_BCDEPBE,
RQ.RQ_CTDEPBE

