SELECT * FROM RHK010 WHERE D_E_L_E_T_=' ';

SELECT RHL_FILIAL FILIAL,
RHL_MAT MATRICULA,
RA.RA_NOMECMP FUNCIONARIO,
RA.RA_CIC CPF_FUNCIONARIO,
RHL_CODIGO COD_DEPENDENTE,
RB.RB_NOME DEPENDENTE,
RB.RB_CIC CPF_DEPENDENTE,
RHL_PLANO COD_PLANO,
(SELECT SUBSTR(RCC_CONTEU,3,20) FROM RCC010 WHERE RCC_CODIGO = 'S009' AND RHL_PLANO = SUBSTR(RCC_CONTEU,1,2) AND ROWNUM=1) PLANO,
SUBSTR(RHL_PERINI,1,2)||'/'||SUBSTR(RHL_PERINI,3,4) PERIODO_INICIAL,
SUBSTR(RHL_PERFIM,1,2)||'/'||SUBSTR(RHL_PERFIM,3,4) PERIODO_FINAL,

RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ') CENTRO_CUSTO,
SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ') LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ') DEPTO_CC

FROM RHL010 JOIN SRA010 RA ON RA.RA_MAT = RHL_MAT AND RHL_FILIAL = RA.RA_FILIAL AND RA.D_E_L_E_T_=' '
JOIN SRB010 RB ON RB.RB_MAT = RHL_MAT AND RHL_FILIAL = RB.RB_FILIAL AND RB.RB_COD = RHL_CODIGO AND RB.D_E_L_E_T_=' '
WHERE RHL010.D_E_L_E_T_=' ';

SELECT * FROM SRB010 WHERE D_E_L_E_T_=' ';

SELECT * FROM RHM010 WHERE D_E_L_E_T_=' ';

SELECT SUBSTR(RCC_CONTEU,3,20) FROM RCC010 WHERE RCC_CODIGO = 'S009';


SELECT * FROM CN9010 WHERE D_E_L_E_T_=' ';