SELECT * FROM SZ3010 WHERE D_E_L_E_T_=' ';

SELECT * FROM SRA010 WHERE D_E_L_E_T_=' ' AND RA_FILIAL = '11032';

UPDATE SRA010 SET RA_X_DPLAN = (SELECT Z3_X_DESC FROM SZ3010 WHERE Z3_X_COD = RA_X_CPLAN AND Z3_FILIAL = RA_FILIAL AND SRA010.D_E_L_E_T_=' ' AND SZ3010.D_E_L_E_T_=' ')
WHERE RA_X_CPLAN = (SELECT Z3_X_COD FROM SZ3010 WHERE Z3_X_COD = RA_X_CPLAN AND RA_FILIAL = Z3_FILIAL AND SRA010.D_E_L_E_T_=' ' AND SZ3010.D_E_L_E_T_=' ') AND RA_FILIAL = '11032';

SELECT RA_FILIAL, RA_MAT, RA_X_CPLAN,RA_X_DPLAN, Z3_X_DESC FROM SRA010 JOIN SZ3010 ON Z3_X_COD = RA_X_CPLAN AND RA_FILIAL = Z3_FILIAL AND SRA010.D_E_L_E_T_=' ' AND SZ3010.D_E_L_E_T_=' '
WHERE RA_X_DPLAN != Z3_X_DESC;