
SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF8
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF8.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN TO_DATE(AF8.AF8_START,'YYYYMMDD') AND LAST_DAY(to_date(AF8.AF8_START, 'YYYYMMDD'))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL


SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF82
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF82.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD')) AND LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI



UNION ALL



SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF83
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF83.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'),1)) AND LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI



UNION ALL



SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF84
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF84.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'),2)) AND LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'),3))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI



UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF85
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF85.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'),3)) AND LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI



UNION ALL






SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF86
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF86.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'),4)) AND LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI



UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF87
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF87.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'),5)) AND LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF88
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF88.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'),6)) AND LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF89
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF89.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'),7)) AND LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF810
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF810.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'),8)) AND LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF811
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF811.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') BETWEEN LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'),9)) AND LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI


UNION ALL





SELECT
NVL(C7_FILIAL,D1_FILIAL) FILIAL, 
COALESCE(AFN_PROJET,AJ7_PROJET) COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
COALESCE(AFN_TAREFA,AJ7_TAREFA) COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
NVL(D1_DOC,' ') NOTA,
NVL(D1_SERIE,' ') SERIE,
COALESCE(C7_NUM,D1_PEDIDO,' ') PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD')) DATA,
ROUND(SUM(D1_TOTAL),2) TOTAL

FROM SD1010

LEFT JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN010.D_E_L_E_T_=' '

JOIN SC7010 
ON C7_NUM = D1_PEDIDO 
AND C7_ITEM = D1_ITEMPC 
AND C7_FILIAL = D1_FILIAL 
AND SC7010.D_E_L_E_T_=' '

LEFT JOIN AJ7010 
ON AJ7_FILIAL = C7_FILIAL
AND AJ7_NUMPC = C7_NUM
AND AJ7_ITEMPC = C7_ITEM
AND AJ7010.D_E_L_E_T_=' '

LEFT JOIN AF8010 AF812
ON AF8_PROJET = NVL(AFN_PROJET,AJ7_PROJET) 
AND AF8_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF812.D_E_L_E_T_=' '

LEFT JOIN AF9010 
ON AF9_TAREFA = NVL(AFN_TAREFA,AJ7_TAREFA) 
AND AF9_FILIAL = NVL(AFN_FILIAL,AJ7_FILIAL) 
AND AF9010.D_E_L_E_T_=' '
AND AF9_PROJET = NVL(AFN_PROJET,AJ7_PROJET)
AND AF8_REVISA = AF9_REVISA

LEFT JOIN SA2010
ON A2_COD = NVL(C7_FORNECE,D1_FORNECE) 
AND A2_LOJA = NVL(C7_LOJA,D1_LOJA) 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),NULLIF(D1_DTDIGIT,' '),C7_EMISSAO),'YYYYMMDD') > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'),10))
AND SD1010.D_E_L_E_T_=' '
AND (AFN_DOC IS NOT NULL OR AJ7_NUMPC IS NOT NULL) 


GROUP BY 
 
C7_FILIAL, 
D1_FILIAL,
AFN_PROJET,
AJ7_PROJET,
AJ7_TAREFA,
AFN_TAREFA,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
C7_NUM,
C7_ENCER,
A2_NOME,
C7_EMISSAO,
D1_DTDIGIT,
D1_X_DTPMS,
C7_X_DTCON,
AF9_DESCRI,
AF8_DESCRI