SELECT AJ7.AJ7_FILIAL FILIAL
	,AJ7.AJ7_PROJET PROJETO
	,AF8.AF8_DESCRI DESC_PROJETO
	,AJ7.AJ7_TAREFA TAREFA
	,LAST_DAY(TO_DATE(coalesce(NULLIF(C7_X_DTCON,' '), C7_EMISSAO), 'YYYYMMDD')) EMISSAO_PEDIDO
	,C7_NUM PEDIDO
  ,F.A2_NOME FORNECEDOR
	,AF9.AF9_DESCRI DESC_TAREFA
	,LAST_DAY(TO_DATE(coalesce(NULLIF(C7_X_DTCON,' '), C7_EMISSAO), 'YYYYMMDD')) MES
	,SUM(NVL(SC7.C7_QUANT * SC7.C7_PRECO, 0)) TOTAL_PEDIDO
FROM AJ7010 AJ7
LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
	AND SC7.C7_NUM = AJ7.AJ7_NUMPC
	AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
	AND SC7.C7_PRODUTO = AJ7.AJ7_COD
	AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
	AND SC7.D_E_L_E_T_ = ' ' 
JOIN AF8010 AF8 ON AJ7.AJ7_FILIAL = AF8.AF8_FILIAL
	AND AJ7.AJ7_PROJET = AF8.AF8_PROJET
	AND AJ7.AJ7_REVISA = AF8.AF8_REVISA
  AND AF8.D_E_L_E_T_ = ' '
JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AF8.AF8_FILIAL
	AND AF9.AF9_PROJET = AF8.AF8_PROJET
	AND AF9.AF9_REVISA = AF8.AF8_REVISA
  AND AJ7.AJ7_TAREFA = AF9.AF9_TAREFA
	AND AF9.D_E_L_E_T_ = ' '
JOIN SA2010 F ON F.D_E_L_E_T_ = ' '
  AND F.A2_COD = SC7.C7_FORNECE 
  AND F.A2_LOJA = SC7.C7_LOJA
  and substr(F.A2_FILIAL,1,2) = substr(C7_FILIAL,1,2)
WHERE AJ7.D_E_L_E_T_ = ' '
AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0

GROUP BY AJ7.AJ7_FILIAL
	,AJ7.AJ7_PROJET
	,AF8.AF8_DESCRI
	,AJ7.AJ7_TAREFA
	,LAST_DAY(TO_DATE(coalesce(NULLIF(C7_X_DTCON,' '), C7_EMISSAO), 'YYYYMMDD'))
  ,C7_NUM
	,AF9.AF9_DESCRI
	,LAST_DAY(to_date(AF8_START, 'YYYYMMDD'))
	,AF8.AF8_START
	,AF8.AF8_REVISA
,F.A2_NOME 


