SELECT 
C7_FILIAL,
C7_NUM,
C7_TOTAL,
AJ7_PROJET,
AJ7_TAREFA,
D1_DOC,
D1_FORNECE,
D1_LOJA,
D1_TOTAL,
AFN_PROJET,
AFN_TAREFA,
E2_NUM,
E2_VENCTO,
E2_VALOR,
EV_PERC,
EV_VALOR,
E2_X_CPMS
FROM SC7010
LEFT JOIN AJ7010 ON AJ7_FILIAL = C7_FILIAL AND AJ7_NUMPC = C7_NUM AND AJ7_ITEMPC = C7_ITEM AND AJ7010.D_E_L_E_T_=' '
LEFT JOIN SD1010 ON D1_FILIAL = C7_FILIAL AND D1_PEDIDO = C7_NUM AND D1_ITEMPC = C7_ITEM AND SD1010.D_E_L_E_T_=' '
LEFT JOIN AFN010 ON AFN_FILIAL = D1_FILIAL AND AFN_SERIE = D1_SERIE AND AFN_DOC = D1_DOC AND AFN_FORNEC = D1_FORNECE AND AFN_ITEM = D1_ITEM AND AFN010.D_E_L_E_T_=' '
LEFT JOIN SE2010 ON E2_FILIAL = D1_FILIAL AND E2_PREFIXO = D1_SERIE AND E2_NUM = D1_DOC AND E2_FORNECE = D1_FORNECE AND E2_LOJA = D1_LOJA AND SE2010.D_E_L_E_T_=' '
LEFT JOIN SEV010 ON EV_FILIAL = E2_FILIAL AND EV_CLIFOR = E2_FORNECE AND EV_LOJA = E2_LOJA AND E2_PREFIXO = EV_PREFIXO AND EV_NUM = E2_NUM AND EV_PARCELA = E2_PARCELA AND EV_PERC <> 1 AND SEV010.D_E_L_E_T_=' '
WHERE SC7010.D_E_L_E_T_=' ';