SELECT AF8.AF8_FILIAL FILIAL
	,AF8.AF8_PROJET PROJETO
	,AF8.AF8_DESCRI DESC_PROJETO
	,AF9.AF9_TAREFA TAREFA
	,AF9.AF9_DESCRI DESC_TAREFA
	,AF8.AF8_REVISA
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END MES
	,MAX(AF9.AF9_X_PC01) + MAX(AF9.AF9_X_TR01) + MAX(AF9.AF9_X_AP01) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
    WHERE AJ7.AJ7_FILIAL = AF8.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF8.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF9.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF8.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF8.AF8_FILIAL
			AND AFN.AFN_PROJET = AF8.AF8_PROJET
			AND AFN.AFN_TAREFA = AF9.AF9_TAREFA
			AND AFN.AFN_REVISA = AF8.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
      /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF8.AF8_FILIAL
			AND AFR.AFR_PROJET = AF8.AF8_PROJET
			AND AFR.AFR_TAREFA = AF9.AF9_TAREFA
			AND AFR.AFR_REVISA = AF8.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
		) TOTAL_TITULO
	,MAX(AF9.AF9_X_PC01) + MAX(AF9.AF9_X_TR01) + MAX(AF9.AF9_X_AP01) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF8.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF8.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF9.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF8.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)))
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF8.AF8_FILIAL
					AND AFN.AFN_PROJET = AF8.AF8_PROJET
					AND AFN.AFN_TAREFA = AF9.AF9_TAREFA
					AND AFN.AFN_REVISA = AF8.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF8.AF8_FILIAL
			AND AFR.AFR_PROJET = AF8.AF8_PROJET
			AND AFR.AFR_TAREFA = AF9.AF9_TAREFA
			AND AFR.AFR_REVISA = AF8.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
		),0)
		) SALDO_ATUAL
FROM AF8010 AF8
INNER JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AF8.AF8_FILIAL
	AND AF9.AF9_PROJET = AF8.AF8_PROJET
	AND AF9.AF9_REVISA = AF8.AF8_REVISA
	AND AF9.D_E_L_E_T_ = ' '
WHERE AF8.D_E_L_E_T_ = ' '
GROUP BY AF8.AF8_FILIAL
	,AF8.AF8_PROJET
	,AF8.AF8_DESCRI
	,AF9.AF9_TAREFA
	,AF9.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF8.AF8_START
	,AF8.AF8_REVISA

UNION ALL

SELECT AF82.AF8_FILIAL FILIAL
	,AF82.AF8_PROJET PROJETO
	,AF82.AF8_DESCRI DESC_PROJETO
	,AF92.AF9_TAREFA TAREFA
	,AF92.AF9_DESCRI DESC_TAREFA
	,AF82.AF8_REVISA
	,CASE WHEN AF82.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1)) END MES
	,MAX(AF92.AF9_X_PC02)  + MAX(AF92.AF9_X_TR02) + MAX(AF92.AF9_X_AP02)  ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF82.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF82.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF92.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF82.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF82.AF8_FILIAL
			AND AFN.AFN_PROJET = AF82.AF8_PROJET
			AND AFN.AFN_TAREFA = AF92.AF9_TAREFA
			AND AFN.AFN_REVISA = AF82.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF82.AF8_FILIAL
			AND AFR.AFR_PROJET = AF82.AF8_PROJET
			AND AFR.AFR_TAREFA = AF92.AF9_TAREFA
			AND AFR.AFR_REVISA = AF82.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
		) TOTAL_TITULO
	,MAX(AF92.AF9_X_PC02) + MAX(AF92.AF9_X_TR02) + MAX(AF92.AF9_X_AP02) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF82.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF82.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF92.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF82.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF82.AF8_FILIAL
					AND AFN.AFN_PROJET = AF82.AF8_PROJET
					AND AFN.AFN_TAREFA = AF92.AF9_TAREFA
					AND AFN.AFN_REVISA = AF82.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF82.AF8_FILIAL
			AND AFR.AFR_PROJET = AF82.AF8_PROJET
			AND AFR.AFR_TAREFA = AF92.AF9_TAREFA
			AND AFR.AFR_REVISA = AF82.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(to_date(AF82.AF8_START, 'YYYYMMDD'))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF82.AF8_START, 'YYYYMMDD'), 1))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF82
INNER JOIN AF9010 AF92 ON AF92.AF9_FILIAL = AF82.AF8_FILIAL
	AND AF92.AF9_PROJET = AF82.AF8_PROJET
	AND AF92.AF9_REVISA = AF82.AF8_REVISA
	AND AF92.D_E_L_E_T_ = ' '
WHERE AF82.D_E_L_E_T_ = ' '
GROUP BY AF82.AF8_FILIAL
	,AF82.AF8_PROJET
	,AF82.AF8_DESCRI
	,AF92.AF9_TAREFA
	,AF92.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF82.AF8_START
	,AF82.AF8_REVISA

UNION ALL

SELECT AF83.AF8_FILIAL FILIAL
	,AF83.AF8_PROJET PROJETO
	,AF83.AF8_DESCRI DESC_PROJETO
	,AF93.AF9_TAREFA TAREFA
	,AF93.AF9_DESCRI DESC_TAREFA
	,AF83.AF8_REVISA
	,CASE WHEN AF83.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2)) END MES
	,MAX(AF93.AF9_X_PC03)  + MAX(AF93.AF9_X_TR03) + MAX(AF93.AF9_X_AP03) ORÇADO
	,(
		SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF83.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF83.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF93.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF83.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF83.AF8_FILIAL
			AND AFN.AFN_PROJET = AF83.AF8_PROJET
			AND AFN.AFN_TAREFA = AF93.AF9_TAREFA
			AND AFN.AFN_REVISA = AF83.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF83.AF8_FILIAL
			AND AFR.AFR_PROJET = AF83.AF8_PROJET
			AND AFR.AFR_TAREFA = AF93.AF9_TAREFA
			AND AFR.AFR_REVISA = AF83.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
		) TOTAL_TITULO
	,MAX(AF93.AF9_X_PC03) + MAX(AF93.AF9_X_TR03) + MAX(AF93.AF9_X_AP03) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF83.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF83.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF93.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF83.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF83.AF8_FILIAL
					AND AFN.AFN_PROJET = AF83.AF8_PROJET
					AND AFN.AFN_TAREFA = AF93.AF9_TAREFA
					AND AFN.AFN_REVISA = AF83.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF83.AF8_FILIAL
			AND AFR.AFR_PROJET = AF83.AF8_PROJET
			AND AFR.AFR_TAREFA = AF93.AF9_TAREFA
			AND AFR.AFR_REVISA = AF83.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 1))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF83.AF8_START, 'YYYYMMDD'), 2))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF83
INNER JOIN AF9010 AF93 ON AF93.AF9_FILIAL = AF83.AF8_FILIAL
	AND AF93.AF9_PROJET = AF83.AF8_PROJET
	AND AF93.AF9_REVISA = AF83.AF8_REVISA
	AND AF93.D_E_L_E_T_ = ' '
WHERE AF83.D_E_L_E_T_ = ' '
GROUP BY AF83.AF8_FILIAL
	,AF83.AF8_PROJET
	,AF83.AF8_DESCRI
	,AF93.AF9_TAREFA
	,AF93.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF83.AF8_START
	,AF83.AF8_REVISA

UNION ALL

SELECT AF84.AF8_FILIAL FILIAL
	,AF84.AF8_PROJET PROJETO
	,AF84.AF8_DESCRI DESC_PROJETO
	,AF94.AF9_TAREFA TAREFA
	,AF94.AF9_DESCRI DESC_TAREFA
	,AF84.AF8_REVISA
	,LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3)) MES
	,MAX(AF94.AF9_X_PC04) + MAX(AF94.AF9_X_TR04) + MAX(AF94.AF9_X_AP04) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF84.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF84.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF94.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF84.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF84.AF8_FILIAL
			AND AFN.AFN_PROJET = AF84.AF8_PROJET
			AND AFN.AFN_TAREFA = AF94.AF9_TAREFA
			AND AFN.AFN_REVISA = AF84.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF84.AF8_FILIAL
			AND AFR.AFR_PROJET = AF84.AF8_PROJET
			AND AFR.AFR_TAREFA = AF94.AF9_TAREFA
			AND AFR.AFR_REVISA = AF84.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
		) TOTAL_TITULO
	,MAX(AF94.AF9_X_PC04)+ MAX(AF94.AF9_X_TR04) + MAX(AF94.AF9_X_AP04) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF84.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF84.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF94.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF84.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF84.AF8_FILIAL
					AND AFN.AFN_PROJET = AF84.AF8_PROJET
					AND AFN.AFN_TAREFA = AF94.AF9_TAREFA
					AND AFN.AFN_REVISA = AF84.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF84.AF8_FILIAL
			AND AFR.AFR_PROJET = AF84.AF8_PROJET
			AND AFR.AFR_TAREFA = AF94.AF9_TAREFA
			AND AFR.AFR_REVISA = AF84.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 2))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF84.AF8_START, 'YYYYMMDD'), 3))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF84
INNER JOIN AF9010 AF94 ON AF94.AF9_FILIAL = AF84.AF8_FILIAL
	AND AF94.AF9_PROJET = AF84.AF8_PROJET
	AND AF94.AF9_REVISA = AF84.AF8_REVISA
	AND AF94.D_E_L_E_T_ = ' '
WHERE AF84.D_E_L_E_T_ = ' '
GROUP BY AF84.AF8_FILIAL
	,AF84.AF8_PROJET
	,AF84.AF8_DESCRI
	,AF94.AF9_TAREFA
	,AF94.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF84.AF8_START
	,AF84.AF8_REVISA

UNION ALL

SELECT AF85.AF8_FILIAL FILIAL
	,AF85.AF8_PROJET PROJETO
	,AF85.AF8_DESCRI DESC_PROJETO
	,AF95.AF9_TAREFA TAREFA
	,AF95.AF9_DESCRI DESC_TAREFA
	,AF85.AF8_REVISA
	,CASE WHEN AF85.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4)) END MES
	,MAX(AF95.AF9_X_PC05) + MAX(AF95.AF9_X_TR05) + MAX(AF95.AF9_X_AP05) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF85.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF85.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF95.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF85.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF85.AF8_FILIAL
			AND AFN.AFN_PROJET = AF85.AF8_PROJET
			AND AFN.AFN_TAREFA = AF95.AF9_TAREFA
			AND AFN.AFN_REVISA = AF85.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF85.AF8_FILIAL
			AND AFR.AFR_PROJET = AF85.AF8_PROJET
			AND AFR.AFR_TAREFA = AF95.AF9_TAREFA
			AND AFR.AFR_REVISA = AF85.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
		) TOTAL_TITULO
	,MAX(AF95.AF9_X_PC05)+ MAX(AF95.AF9_X_TR05) + MAX(AF95.AF9_X_AP05) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF85.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF85.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF95.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF85.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF85.AF8_FILIAL
					AND AFN.AFN_PROJET = AF85.AF8_PROJET
					AND AFN.AFN_TAREFA = AF95.AF9_TAREFA
					AND AFN.AFN_REVISA = AF85.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF85.AF8_FILIAL
			AND AFR.AFR_PROJET = AF85.AF8_PROJET
			AND AFR.AFR_TAREFA = AF95.AF9_TAREFA
			AND AFR.AFR_REVISA = AF85.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 3))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF85.AF8_START, 'YYYYMMDD'), 4))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF85
INNER JOIN AF9010 AF95 ON AF95.AF9_FILIAL = AF85.AF8_FILIAL
	AND AF95.AF9_PROJET = AF85.AF8_PROJET
	AND AF95.AF9_REVISA = AF85.AF8_REVISA
	AND AF95.D_E_L_E_T_ = ' '
WHERE AF85.D_E_L_E_T_ = ' '
GROUP BY AF85.AF8_FILIAL
	,AF85.AF8_PROJET
	,AF85.AF8_DESCRI
	,AF95.AF9_TAREFA
	,AF95.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF85.AF8_START
	,AF85.AF8_REVISA

UNION ALL

SELECT AF86.AF8_FILIAL FILIAL
	,AF86.AF8_PROJET PROJETO
	,AF86.AF8_DESCRI DESC_PROJETO
	,AF96.AF9_TAREFA TAREFA
	,AF96.AF9_DESCRI DESC_TAREFA
	,AF86.AF8_REVISA
	,CASE WHEN AF86.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5)) END MES
	,MAX(AF96.AF9_X_PC06)+ MAX(AF96.AF9_X_TR06) + MAX(AF96.AF9_X_AP06) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF86.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF86.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF96.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF86.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF86.AF8_FILIAL
			AND AFN.AFN_PROJET = AF86.AF8_PROJET
			AND AFN.AFN_TAREFA = AF96.AF9_TAREFA
			AND AFN.AFN_REVISA = AF86.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF86.AF8_FILIAL
			AND AFR.AFR_PROJET = AF86.AF8_PROJET
			AND AFR.AFR_TAREFA = AF96.AF9_TAREFA
			AND AFR.AFR_REVISA = AF86.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
		) TOTAL_TITULO
	,MAX(AF96.AF9_X_PC06)+ MAX(AF96.AF9_X_TR06) + MAX(AF96.AF9_X_AP06) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF86.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF86.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF96.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF86.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF86.AF8_FILIAL
					AND AFN.AFN_PROJET = AF86.AF8_PROJET
					AND AFN.AFN_TAREFA = AF96.AF9_TAREFA
					AND AFN.AFN_REVISA = AF86.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF86.AF8_FILIAL
			AND AFR.AFR_PROJET = AF86.AF8_PROJET
			AND AFR.AFR_TAREFA = AF96.AF9_TAREFA
			AND AFR.AFR_REVISA = AF86.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 4))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF86.AF8_START, 'YYYYMMDD'), 5))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF86
INNER JOIN AF9010 AF96 ON AF96.AF9_FILIAL = AF86.AF8_FILIAL
	AND AF96.AF9_PROJET = AF86.AF8_PROJET
	AND AF96.AF9_REVISA = AF86.AF8_REVISA
	AND AF96.D_E_L_E_T_ = ' '
WHERE AF86.D_E_L_E_T_ = ' '
GROUP BY AF86.AF8_FILIAL
	,AF86.AF8_PROJET
	,AF86.AF8_DESCRI
	,AF96.AF9_TAREFA
	,AF96.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF86.AF8_START
	,AF86.AF8_REVISA

UNION ALL

SELECT AF87.AF8_FILIAL FILIAL
	,AF87.AF8_PROJET PROJETO
	,AF87.AF8_DESCRI DESC_PROJETO
	,AF97.AF9_TAREFA TAREFA
	,AF97.AF9_DESCRI DESC_TAREFA
	,AF87.AF8_REVISA
	,CASE WHEN AF87.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6)) END MES
	,MAX(AF97.AF9_X_PC07)+ MAX(AF97.AF9_X_TR07) + MAX(AF97.AF9_X_AP07) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF87.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF87.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF97.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF87.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF87.AF8_FILIAL
			AND AFN.AFN_PROJET = AF87.AF8_PROJET
			AND AFN.AFN_TAREFA = AF97.AF9_TAREFA
			AND AFN.AFN_REVISA = AF87.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF87.AF8_FILIAL
			AND AFR.AFR_PROJET = AF87.AF8_PROJET
			AND AFR.AFR_TAREFA = AF97.AF9_TAREFA
			AND AFR.AFR_REVISA = AF87.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
		) TOTAL_TITULO
	,MAX(AF97.AF9_X_PC07)+ MAX(AF97.AF9_X_TR07) + MAX(AF97.AF9_X_AP07) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF87.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF87.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF97.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF87.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF87.AF8_FILIAL
					AND AFN.AFN_PROJET = AF87.AF8_PROJET
					AND AFN.AFN_TAREFA = AF97.AF9_TAREFA
					AND AFN.AFN_REVISA = AF87.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF87.AF8_FILIAL
			AND AFR.AFR_PROJET = AF87.AF8_PROJET
			AND AFR.AFR_TAREFA = AF97.AF9_TAREFA
			AND AFR.AFR_REVISA = AF87.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 5))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF87.AF8_START, 'YYYYMMDD'), 6))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF87
INNER JOIN AF9010 AF97 ON AF97.AF9_FILIAL = AF87.AF8_FILIAL
	AND AF97.AF9_PROJET = AF87.AF8_PROJET
	AND AF97.AF9_REVISA = AF87.AF8_REVISA
	AND AF97.D_E_L_E_T_ = ' '
WHERE AF87.D_E_L_E_T_ = ' '
GROUP BY AF87.AF8_FILIAL
	,AF87.AF8_PROJET
	,AF87.AF8_DESCRI
	,AF97.AF9_TAREFA
	,AF97.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF87.AF8_START
	,AF87.AF8_REVISA

UNION ALL

SELECT AF88.AF8_FILIAL FILIAL
	,AF88.AF8_PROJET PROJETO
	,AF88.AF8_DESCRI DESC_PROJETO
	,AF98.AF9_TAREFA TAREFA
	,AF98.AF9_DESCRI DESC_TAREFA
	,AF88.AF8_REVISA
	,CASE WHEN AF88.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7)) END MES
	,MAX(AF98.AF9_X_PC08)+ MAX(AF98.AF9_X_TR08) + MAX(AF98.AF9_X_AP08) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF88.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF88.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF98.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF88.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF88.AF8_FILIAL
			AND AFN.AFN_PROJET = AF88.AF8_PROJET
			AND AFN.AFN_TAREFA = AF98.AF9_TAREFA
			AND AFN.AFN_REVISA = AF88.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF88.AF8_FILIAL
			AND AFR.AFR_PROJET = AF88.AF8_PROJET
			AND AFR.AFR_TAREFA = AF98.AF9_TAREFA
			AND AFR.AFR_REVISA = AF88.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
		) TOTAL_TITULO
	,MAX(AF98.AF9_X_PC08)+ MAX(AF98.AF9_X_TR08) + MAX(AF98.AF9_X_AP08) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF88.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF88.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF98.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF88.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF88.AF8_FILIAL
					AND AFN.AFN_PROJET = AF88.AF8_PROJET
					AND AFN.AFN_TAREFA = AF98.AF9_TAREFA
					AND AFN.AFN_REVISA = AF88.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF88.AF8_FILIAL
			AND AFR.AFR_PROJET = AF88.AF8_PROJET
			AND AFR.AFR_TAREFA = AF98.AF9_TAREFA
			AND AFR.AFR_REVISA = AF88.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 6))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF88.AF8_START, 'YYYYMMDD'), 7))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF88
INNER JOIN AF9010 AF98 ON AF98.AF9_FILIAL = AF88.AF8_FILIAL
	AND AF98.AF9_PROJET = AF88.AF8_PROJET
	AND AF98.AF9_REVISA = AF88.AF8_REVISA
	AND AF98.D_E_L_E_T_ = ' '
WHERE AF88.D_E_L_E_T_ = ' '
GROUP BY AF88.AF8_FILIAL
	,AF88.AF8_PROJET
	,AF88.AF8_DESCRI
	,AF98.AF9_TAREFA
	,AF98.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF88.AF8_START
	,AF88.AF8_REVISA

UNION ALL

SELECT AF89.AF8_FILIAL FILIAL
	,AF89.AF8_PROJET PROJETO
	,AF89.AF8_DESCRI DESC_PROJETO
	,AF99.AF9_TAREFA TAREFA
	,AF99.AF9_DESCRI DESC_TAREFA
	,AF89.AF8_REVISA
	,CASE WHEN AF89.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8)) END MES
	,MAX(AF99.AF9_X_PC09)+ MAX(AF99.AF9_X_TR09) + MAX(AF99.AF9_X_AP09) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF89.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF89.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF99.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF89.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF89.AF8_FILIAL
			AND AFN.AFN_PROJET = AF89.AF8_PROJET
			AND AFN.AFN_TAREFA = AF99.AF9_TAREFA
			AND AFN.AFN_REVISA = AF89.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF89.AF8_FILIAL
			AND AFR.AFR_PROJET = AF89.AF8_PROJET
			AND AFR.AFR_TAREFA = AF99.AF9_TAREFA
			AND AFR.AFR_REVISA = AF89.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
		) TOTAL_TITULO
	,MAX(AF99.AF9_X_PC09)+ MAX(AF99.AF9_X_TR09) + MAX(AF99.AF9_X_AP09) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF89.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF89.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF99.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF89.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF89.AF8_FILIAL
					AND AFN.AFN_PROJET = AF89.AF8_PROJET
					AND AFN.AFN_TAREFA = AF99.AF9_TAREFA
					AND AFN.AFN_REVISA = AF89.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF89.AF8_FILIAL
			AND AFR.AFR_PROJET = AF89.AF8_PROJET
			AND AFR.AFR_TAREFA = AF99.AF9_TAREFA
			AND AFR.AFR_REVISA = AF89.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 7))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF89.AF8_START, 'YYYYMMDD'), 8))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF89
INNER JOIN AF9010 AF99 ON AF99.AF9_FILIAL = AF89.AF8_FILIAL
	AND AF99.AF9_PROJET = AF89.AF8_PROJET
	AND AF99.AF9_REVISA = AF89.AF8_REVISA
	AND AF99.D_E_L_E_T_ = ' '
WHERE AF89.D_E_L_E_T_ = ' '
GROUP BY AF89.AF8_FILIAL
	,AF89.AF8_PROJET
	,AF89.AF8_DESCRI
	,AF99.AF9_TAREFA
	,AF99.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF89.AF8_START
	,AF89.AF8_REVISA

UNION ALL

SELECT AF810.AF8_FILIAL FILIAL
	,AF810.AF8_PROJET PROJETO
	,AF810.AF8_DESCRI DESC_PROJETO
	,AF910.AF9_TAREFA TAREFA
	,AF910.AF9_DESCRI DESC_TAREFA
	,AF810.AF8_REVISA
	,CASE WHEN AF810.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9)) END MES
	,MAX(AF910.AF9_X_PC10)+ MAX(AF910.AF9_X_TR10) + MAX(AF910.AF9_X_AP10) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF810.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF810.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF910.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF810.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF810.AF8_FILIAL
			AND AFN.AFN_PROJET = AF810.AF8_PROJET
			AND AFN.AFN_TAREFA = AF910.AF9_TAREFA
			AND AFN.AFN_REVISA = AF810.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF810.AF8_FILIAL
			AND AFR.AFR_PROJET = AF810.AF8_PROJET
			AND AFR.AFR_TAREFA = AF910.AF9_TAREFA
			AND AFR.AFR_REVISA = AF810.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
		) TOTAL_TITULO
	,MAX(AF910.AF9_X_PC10)+ MAX(AF910.AF9_X_TR10) + MAX(AF910.AF9_X_AP10) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF810.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF810.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF910.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF810.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF810.AF8_FILIAL
					AND AFN.AFN_PROJET = AF810.AF8_PROJET
					AND AFN.AFN_TAREFA = AF910.AF9_TAREFA
					AND AFN.AFN_REVISA = AF810.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF810.AF8_FILIAL
			AND AFR.AFR_PROJET = AF810.AF8_PROJET
			AND AFR.AFR_TAREFA = AF910.AF9_TAREFA
			AND AFR.AFR_REVISA = AF810.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 8))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF810.AF8_START, 'YYYYMMDD'), 9))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF810
INNER JOIN AF9010 AF910 ON AF910.AF9_FILIAL = AF810.AF8_FILIAL
	AND AF910.AF9_PROJET = AF810.AF8_PROJET
	AND AF910.AF9_REVISA = AF810.AF8_REVISA
	AND AF910.D_E_L_E_T_ = ' '
WHERE AF810.D_E_L_E_T_ = ' '
GROUP BY AF810.AF8_FILIAL
	,AF810.AF8_PROJET
	,AF810.AF8_DESCRI
	,AF910.AF9_TAREFA
	,AF910.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF810.AF8_START
	,AF810.AF8_REVISA

UNION ALL

SELECT AF811.AF8_FILIAL FILIAL
	,AF811.AF8_PROJET PROJETO
	,AF811.AF8_DESCRI DESC_PROJETO
	,AF911.AF9_TAREFA TAREFA
	,AF911.AF9_DESCRI DESC_TAREFA
	,AF811.AF8_REVISA
	,CASE WHEN AF811.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10)) END MES
	,MAX(AF911.AF9_X_PC11)+ MAX(AF911.AF9_X_TR11) + MAX(AF911.AF9_X_AP11) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF811.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF811.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF911.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF811.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF811.AF8_FILIAL
			AND AFN.AFN_PROJET = AF811.AF8_PROJET
			AND AFN.AFN_TAREFA = AF911.AF9_TAREFA
			AND AFN.AFN_REVISA = AF811.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF811.AF8_FILIAL
			AND AFR.AFR_PROJET = AF811.AF8_PROJET
			AND AFR.AFR_TAREFA = AF911.AF9_TAREFA
			AND AFR.AFR_REVISA = AF811.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
		) TOTAL_TITULO
	,MAX(AF911.AF9_X_PC11)+ MAX(AF911.AF9_X_TR11) + MAX(AF911.AF9_X_AP11) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF811.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF811.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF911.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF811.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF811.AF8_FILIAL
					AND AFN.AFN_PROJET = AF811.AF8_PROJET
					AND AFN.AFN_TAREFA = AF911.AF9_TAREFA
					AND AFN.AFN_REVISA = AF811.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF811.AF8_FILIAL
			AND AFR.AFR_PROJET = AF811.AF8_PROJET
			AND AFR.AFR_TAREFA = AF911.AF9_TAREFA
			AND AFR.AFR_REVISA = AF811.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 9))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF811.AF8_START, 'YYYYMMDD'), 10))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF811
INNER JOIN AF9010 AF911 ON AF911.AF9_FILIAL = AF811.AF8_FILIAL
	AND AF911.AF9_PROJET = AF811.AF8_PROJET
	AND AF911.AF9_REVISA = AF811.AF8_REVISA
	AND AF911.D_E_L_E_T_ = ' '
WHERE AF811.D_E_L_E_T_ = ' '
GROUP BY AF811.AF8_FILIAL
	,AF811.AF8_PROJET
	,AF811.AF8_DESCRI
	,AF911.AF9_TAREFA
	,AF911.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF811.AF8_START
	,AF811.AF8_REVISA

UNION ALL

SELECT AF812.AF8_FILIAL FILIAL
	,AF812.AF8_PROJET PROJETO
	,AF812.AF8_DESCRI DESC_PROJETO
	,AF912.AF9_TAREFA TAREFA
	,AF912.AF9_DESCRI DESC_TAREFA
	,AF812.AF8_REVISA
	,CASE WHEN AF812.AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11)) END MES
	,MAX(AF912.AF9_X_PC12)+ MAX(AF912.AF9_X_TR12) + MAX(AF912.AF9_X_AP12) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
		WHERE AJ7.AJ7_FILIAL = AF812.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF812.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF912.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF812.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
			/*AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))*/
			AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF812.AF8_FILIAL
			AND AFN.AFN_PROJET = AF812.AF8_PROJET
			AND AFN.AFN_TAREFA = AF912.AF9_TAREFA
			AND AFN.AFN_REVISA = AF812.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
			/*AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') cast(null as date) ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))*/
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF812.AF8_FILIAL
			AND AFR.AFR_PROJET = AF812.AF8_PROJET
			AND AFR.AFR_TAREFA = AF912.AF9_TAREFA
			AND AFR.AFR_REVISA = AF812.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))
		) TOTAL_TITULO
	,MAX(AF912.AF9_X_PC12)+ MAX(AF912.AF9_X_TR12) + MAX(AF912.AF9_X_AP12) - (
		NVL((
				SELECT Round(SUM(NVL(CASE WHEN SC7.C7_RESIDUO <> 'S' THEN SC7.C7_QUANT ELSE SC7.C7_QUJE END * SC7.C7_PRECO, 0)),2)
				FROM AJ7010 AJ7
				LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
					AND SC7.C7_NUM = AJ7.AJ7_NUMPC
					AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
					AND SC7.C7_PRODUTO = AJ7.AJ7_COD
					AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
				WHERE AJ7.AJ7_FILIAL = AF812.AF8_FILIAL
					AND AJ7.AJ7_PROJET = AF812.AF8_PROJET
					AND AJ7.AJ7_TAREFA = AF912.AF9_TAREFA
					AND AJ7.AJ7_REVISA = AF812.AF8_REVISA
					AND AJ7.D_E_L_E_T_ = ' '
					AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
					/*AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))*/
					AND (
						SELECT count(*)
						FROM SD1010 SD1
						WHERE D1_FILIAL = SC7.C7_FILIAL
							AND D1_COD = C7_PRODUTO
							AND D1_PEDIDO = SC7.C7_NUM
							AND SD1.D1_ITEMPC = SC7.C7_ITEM
							AND SD1.D_E_L_E_T_ = ' '
							AND TRIM(SD1.D1_X_DTPMS) <> ' '
						) = 0
				), 0) + NVL((
				SELECT Round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
				FROM AFN010 AFN
				LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
					AND SD1.D1_DOC = AFN.AFN_DOC
					AND SD1.D1_SERIE = AFN.AFN_SERIE
					AND SD1.D1_ITEM = AFN.AFN_ITEM
					AND SD1.D1_FORNECE = AFN.AFN_FORNEC
					AND SD1.D1_LOJA = AFN.AFN_LOJA
					AND SD1.D1_COD = AFN.AFN_COD
					AND SD1.D_E_L_E_T_ = ' '
				WHERE AFN.AFN_FILIAL = AF812.AF8_FILIAL
					AND AFN.AFN_PROJET = AF812.AF8_PROJET
					AND AFN.AFN_TAREFA = AF912.AF9_TAREFA
					AND AFN.AFN_REVISA = AF812.AF8_REVISA
					AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
					AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
					/*AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') cast(null as date) ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))*/
				), 0)+NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF812.AF8_FILIAL
			AND AFR.AFR_PROJET = AF812.AF8_PROJET
			AND AFR.AFR_TAREFA = AF912.AF9_TAREFA
			AND AFR.AFR_REVISA = AF812.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END > LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 10))
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= LAST_DAY(ADD_MONTHS(to_date(AF812.AF8_START, 'YYYYMMDD'), 11))
		),0)
		) SALDO_ATUAL
FROM AF8010 AF812
INNER JOIN AF9010 AF912 ON AF912.AF9_FILIAL = AF812.AF8_FILIAL
	AND AF912.AF9_PROJET = AF812.AF8_PROJET
	AND AF912.AF9_REVISA = AF812.AF8_REVISA
	AND AF912.D_E_L_E_T_ = ' '
WHERE AF812.D_E_L_E_T_ = ' '
GROUP BY AF812.AF8_FILIAL
	,AF812.AF8_PROJET
	,AF812.AF8_DESCRI
	,AF912.AF9_TAREFA
	,AF912.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF812.AF8_START
	,AF812.AF8_REVISA