SELECT 
	AF8.AF8_FILIAL FILIAL
	,AF8.AF8_PROJET PROJETO
	,AF8.AF8_DESCRI DESC_PROJETO
	,AF9.AF9_TAREFA TAREFA
	,AF9.AF9_DESCRI DESC_TAREFA
	,AF8.AF8_REVISA
	,/*CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END*/ ZC_PERIODO MES
	,/*MAX(AF9.AF9_X_PC01) + MAX(AF9.AF9_X_TR01) + MAX(AF9.AF9_X_AP01)*/MAX(ZC_VALOR)+MAX(ZC_APLICA)+MAX(ZC_TRANSF) ORÇADO
	,(
		SELECT round(SUM(NVL(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
    WHERE AJ7.AJ7_FILIAL = AF8.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF8.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF9.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF8.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= to_date(ZC_DTFIM, 'YYYYMMDD')
      		AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END >= to_date(ZC_DTINI, 'YYYYMMDD')
      AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
		) TOTAL_PEDIDO
	,(
		SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF8.AF8_FILIAL
			AND AFN.AFN_PROJET = AF8.AF8_PROJET
			AND AFN.AFN_TAREFA = AF9.AF9_TAREFA
			AND AFN.AFN_REVISA = AF8.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
      /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTFIM, 'YYYYMMDD')) END
      		AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END >= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTINI, 'YYYYMMDD')) END
		) TOTAL_NOTA
	,(
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF8.AF8_FILIAL
			AND AFR.AFR_PROJET = AF8.AF8_PROJET
			AND AFR.AFR_TAREFA = AF9.AF9_TAREFA
			AND AFR.AFR_REVISA = AF8.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTFIM, 'YYYYMMDD')) END
    		AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END >= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTINI, 'YYYYMMDD')) END
		) TOTAL_TITULO
	, MAX(ZC_VALOR)+MAX(ZC_APLICA)+MAX(ZC_TRANSF) /*MAX(AF9.AF9_X_PC01) + MAX(AF9.AF9_X_TR01) + MAX(AF9.AF9_X_AP01)*/ - (
		NVL((
				SELECT round(SUM(NVL(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO, 0)),2)
		FROM AJ7010 AJ7
		LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL
			AND SC7.C7_NUM = AJ7.AJ7_NUMPC
			AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC
			AND SC7.C7_PRODUTO = AJ7.AJ7_COD
			AND SC7.D_E_L_E_T_ = ' ' AND C7_NUM IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = C7_FILIAL)
    WHERE AJ7.AJ7_FILIAL = AF8.AF8_FILIAL
			AND AJ7.AJ7_PROJET = AF8.AF8_PROJET
			AND AJ7.AJ7_TAREFA = AF9.AF9_TAREFA
			AND AJ7.AJ7_REVISA = AF8.AF8_REVISA
			AND AJ7.D_E_L_E_T_ = ' '
			AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END <= to_date(ZC_DTFIM, 'YYYYMMDD')
      		AND CASE WHEN C7_X_DTCON = ' ' THEN cast(null as date) ELSE to_date( C7_X_DTCON, 'yyyymmdd' ) END >= to_date(ZC_DTINI, 'YYYYMMDD')
      AND (
				SELECT count(*)
				FROM SD1010 SD1
				WHERE D1_FILIAL = SC7.C7_FILIAL
					AND D1_COD = C7_PRODUTO
					AND D1_PEDIDO = SC7.C7_NUM
					AND SD1.D1_ITEMPC = SC7.C7_ITEM
					AND SD1.D_E_L_E_T_ = ' '
					AND TRIM(SD1.D1_X_DTPMS) <> ' '
				) = 0
      ), 0) + NVL((
				SELECT round(SUM(NVL(SD1.D1_QUANT * SD1.D1_VUNIT, 0)),2)
		FROM AFN010 AFN
		LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL
			AND SD1.D1_DOC = AFN.AFN_DOC
			AND SD1.D1_SERIE = AFN.AFN_SERIE
			AND SD1.D1_ITEM = AFN.AFN_ITEM
			AND SD1.D1_FORNECE = AFN.AFN_FORNEC
			AND SD1.D1_LOJA = AFN.AFN_LOJA
			AND SD1.D1_COD = AFN.AFN_COD
			AND SD1.D_E_L_E_T_ = ' '
		WHERE AFN.AFN_FILIAL = AF8.AF8_FILIAL
			AND AFN.AFN_PROJET = AF8.AF8_PROJET
			AND AFN.AFN_TAREFA = AF9.AF9_TAREFA
			AND AFN.AFN_REVISA = AF8.AF8_REVISA
			AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = SD1.D1_FILIAL) /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
      /*AND SD1.D1_PEDIDO NOT IN (SELECT AJ7_NUMPC FROM AJ7010 WHERE AJ7010.D_E_L_E_T_=' ' AND AJ7_FILIAL = SD1.D1_FILIAL)*/
			AND TRIM(SD1.D1_X_DTPMS) <> ' '
			AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTFIM, 'YYYYMMDD')) END
      AND CASE WHEN SD1.D1_X_DTPMS = ' ' THEN TO_DATE(SD1.D1_DTDIGIT, 'YYYYMMDD') /*cast(null as date)*/ ELSE to_date(SD1.D1_X_DTPMS, 'YYYYMMDD') END >= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTINI, 'YYYYMMDD')) END), 0)
      +NVL((
		SELECT SUM(AFR.AFR_VALOR1)
		FROM AFR010 AFR
		WHERE AFR.AFR_FILIAL = AF8.AF8_FILIAL
			AND AFR.AFR_PROJET = AF8.AF8_PROJET
			AND AFR.AFR_TAREFA = AF9.AF9_TAREFA
			AND AFR.AFR_REVISA = AF8.AF8_REVISA
			AND AFR.D_E_L_E_T_ = ' '
			AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END <= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTFIM, 'YYYYMMDD')) END
      AND CASE WHEN AFR.AFR_DATA = ' ' THEN cast(null as date) ELSE to_date(AFR.AFR_DATA, 'YYYYMMDD') END >= CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(ZC_DTINI, 'YYYYMMDD')) END
		),0)
		) SALDO_ATUAL
FROM AF8010 AF8
INNER JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AF8.AF8_FILIAL
	AND AF9.AF9_PROJET = AF8.AF8_PROJET
	AND AF9.AF9_REVISA = AF8.AF8_REVISA
	AND AF9.D_E_L_E_T_ = ' '
  
INNER JOIN SZC010 SZC ON SZC.ZC_FILIAL = AF9_FILIAL
  AND ZC_PROJETO = AF9_PROJET
  AND ZC_TAREFA = AF9_TAREFA
  AND SZC.D_E_L_E_T_=' '
WHERE AF8.D_E_L_E_T_ = ' '
GROUP BY AF8.AF8_FILIAL
	,AF8.AF8_PROJET
	,AF8.AF8_DESCRI
	,AF9.AF9_TAREFA
	,AF9.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF8.AF8_START
	,AF8.AF8_REVISA
  ,ZC_PERIODO
  ,ZC_DTINI
  ,ZC_DTFIM
  
  ORDER BY AF8.AF8_FILIAL
	,AF8.AF8_PROJET
	,AF8.AF8_DESCRI	,AF9.AF9_TAREFA
	,AF9.AF9_DESCRI
	,CASE WHEN AF8_START = ' ' THEN cast(null as date) ELSE LAST_DAY(to_date(AF8_START, 'YYYYMMDD')) END
	,AF8.AF8_START
	,AF8.AF8_REVISA
  ,ZC_PERIODO
  ,ZC_DTINI
  ,ZC_DTFIM
  
  ;
  
