SELECT DISTINCT

D1_FILIAL FILIAL, 
AFN_PROJET COD_PROJETO,
SUBSTR(AF8_DESCRI,1,50) PROJETO,
AFN_TAREFA COD_TAREFA,
SUBSTR(AF9_DESCRI,1,50) TAREFA,
D1_DOC NOTA,
D1_SERIE SERIE,
D1_PEDIDO PEDIDO,
A2_NOME FORNECEDOR,
LAST_DAY(TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),D1_DTDIGIT),'YYYYMMDD')) DATA,
ROUND(SUM(D1_QUANT * D1_VUNIT),2) TOTAL

FROM SD1010

JOIN AFN010 
ON AFN_FILIAL  = D1_FILIAL 
AND AFN_DOC = D1_DOC 
AND AFN_SERIE = D1_SERIE 
AND AFN_FORNEC = D1_FORNECE 
AND AFN_LOJA = D1_LOJA 
AND AFN_ITEM = D1_ITEM 
AND AFN_COD = D1_COD
AND AFN_REVISA = (SELECT DISTINCT AF8_REVISA FROM AF8010 WHERE AF8_FILIAL = AFN_FILIAL AND AF8_PROJET = AFN_PROJET AND AF8010.D_E_L_E_T_=' ')
AND AFN010.D_E_L_E_T_=' '

JOIN AF8010 AF8
ON AF8_PROJET = AFN_PROJET
AND AF8_FILIAL = AFN_FILIAL
AND AF8_REVISA = AFN_REVISA
AND AF8.D_E_L_E_T_=' '

JOIN AF9010 
ON AF9_TAREFA = AFN_TAREFA 
AND AF9_FILIAL = AFN_FILIAL 
AND AF9_PROJET = AFN_PROJET
AND AF8_REVISA = AF9_REVISA
AND AF9010.D_E_L_E_T_=' '

JOIN SA2010
ON A2_COD = D1_FORNECE 
AND A2_LOJA = D1_LOJA 
AND A2_FILIAL = '11' 
AND SA2010.D_E_L_E_T_=' '

WHERE /*TO_DATE(COALESCE(NULLIF(D1_X_DTPMS,' '),NULLIF(C7_X_DTCON,' '),D1_DTDIGIT,C7_EMISSAO),'YYYYMMDD') BETWEEN TO_DATE(AF8.AF8_START,'YYYYMMDD') AND LAST_DAY(to_date(AF8.AF8_START, 'YYYYMMDD'))
AND*/ SD1010.D_E_L_E_T_=' '
AND D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ' AND AFN_FILIAL = D1_FILIAL) 
AND TRIM(D1_X_DTPMS) <> ' '

GROUP BY 

D1_FILIAL, 
AFN_PROJET,
AF8_DESCRI,
AFN_TAREFA,
AF9_DESCRI,
D1_DOC,
D1_SERIE,
D1_PEDIDO,
A2_NOME,
D1_X_DTPMS,
D1_DTDIGIT
