SELECT 
RF_FILIAL FILIAL,
RF_MAT MATRICULA,
RA_NOMECMP FUNCIONARIO,
SUBSTR(RF_DATAINI,7,2)||'/'||SUBSTR(RF_DATAINI,5,2)||'/'||SUBSTR(RF_DATAINI,1,4) DATA_INICIO,
SUBSTR(RF_DATAINI,7,2) DIA_INICIO,
SUBSTR(RF_DATAINI,5,2) MES_INICIO,
SUBSTR(RF_DATAINI,1,4) ANO_INICIO,
RF_DFERVAT FERIAS_VENCIDAS,
RF_DFERAAT FERIAS_PROPORCIONAIS,
1 CONTADOR,
SUBSTR(COALESCE(NULLIF(RF_DATINI3,' '),NULLIF(RF_DATINI2,' '),NULLIF(RF_DATAINI,' ')),1,6) DATA,

RA.RA_CC COD_CENTRO_CUSTO,
RA.RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA.RA_CC AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(RA_FILIAL,1,2) = SUBSTR(CTT_FILIAL,1,2)) CENTRO_CUSTO,
SUBSTR(RA.RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,5)||'       ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(RA_FILIAL,1,2) = SUBSTR(CTT_FILIAL,1,2)) LOCAL_CC,
SUBSTR(RA.RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA.RA_CC,1,8)||'    ' AND CTT010.D_E_L_E_T_=' ' AND SUBSTR(RA_FILIAL,1,2) = SUBSTR(CTT_FILIAL,1,2)) DEPTO_CC,

(SELECT RA_SITFOLH FROM SRA010 WHERE RA_MAT = RF_MAT AND SRA010.D_E_L_E_T_=' ' AND RA_FILIAL = RF_FILIAL)  SITUACAO_FOLHA,
(SELECT SUBSTR(RH_DATABAS,7,2)||'/'||SUBSTR(RH_DATABAS,5,2)||'/'||SUBSTR(RH_DATABAS,1,4) FROM SRH010 WHERE D_E_L_E_T_=' ' AND RH_DATABAS = RF_DATABAS AND RH_FILIAL = RF_FILIAL AND RH_MAT = RF_MAT AND ROWNUM = 1) BASE_INICIAL,
(SELECT SUBSTR(RH_DBASEAT,7,2)||'/'||SUBSTR(RH_DBASEAT,5,2)||'/'||SUBSTR(RH_DBASEAT,1,4) FROM SRH010 WHERE D_E_L_E_T_=' ' AND RH_DATABAS = RF_DATABAS AND RH_FILIAL = RF_FILIAL AND RH_MAT = RF_MAT AND ROWNUM = 1) BASE_FINAL

FROM SRF010 

JOIN SRA010 RA
ON RA.D_E_L_E_T_=' '
AND RA_MAT = RF_MAT
AND RA_FILIAL = RF_FILIAL

WHERE SRF010.D_E_L_E_T_=' '

AND COALESCE(NULLIF(RF_DATINI3,' '),NULLIF(RF_DATINI2,' '),NULLIF(RF_DATAINI,' ')) BETWEEN :DATA_INICIO AND :DATA_FIM

;