/*SELECT 
'FILIAL' FILIAL,
'NATUREZA' NATUREZA,
'VALOR' VALOR,
LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')) MES_1,
ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),1) MES_2,
ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),2) MES_3,
ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),3) MES_4,
ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),4) MES_5,
ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),5) MES_6

FROM SE1010

UNION
*/
SELECT E1_FILIAL FILIAL,
(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = E1_NATUREZ AND SUBSTR(ED_FILIAL,1,2) = SUBSTR(E1_FILIAL,1,2) AND SED010.D_E_L_E_T_=' ') NATUREZA, 
/*LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) DATA, */
SUM(E1_VALOR) VALOR ,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')) THEN E1_VALOR ELSE 0 END ) MES_1,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),1) THEN E1_VALOR ELSE 0 END ) MES_2,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),2) THEN E1_VALOR ELSE 0 END ) MES_3,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),3) THEN E1_VALOR ELSE 0 END ) MES_4,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),4) THEN E1_VALOR ELSE 0 END ) MES_5,
SUM(CASE WHEN LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD')) = ADD_MONTHS(LAST_DAY(TO_DATE(:DATA_INICIO,'YYYYMMDD')),5) THEN E1_VALOR ELSE 0 END ) MES_6

FROM SE1010 

WHERE E1_EMISSAO BETWEEN :DATA_INICIO AND :DATA_FIM 
AND E1_NATUREZ BETWEEN ' ' AND 'ZZZZZZZZZZ'
AND E1_FILIAL BETWEEN ' ' AND 'ZZZZZ'
AND E1_ORIGEM <> 'FINA280'
AND E1_TIPO NOT IN ('PR','RA')
AND E1_PARCELA NOT IN ('0','00')
AND D_E_L_E_T_=' ' 

GROUP BY E1_FILIAL, E1_NATUREZ /*, LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD'))*/
ORDER BY E1_FILIAL, E1_NATUREZ /*, LAST_DAY(TO_DATE(E1_EMISSAO,'YYYYMMDD'));*/;