SELECT CN9_FILIAL, 

CN9_NUMERO, 

SUBSTR(CN9_DTINIC,7,2)||'/'||SUBSTR(CN9_DTINIC,5,2)||'/'||SUBSTR(CN9_DTINIC,1,4) INICIO, 

SUBSTR(CN9_DTASSI,7,2)||'/'||SUBSTR(CN9_DTASSI,5,2)||'/'||SUBSTR(CN9_DTASSI,1,4) ASSINATURA,

CASE WHEN CN9_UNVIGE = '1' THEN 'DIAS'
WHEN CN9_UNVIGE = '2' THEN 'MESES'
WHEN CN9_UNVIGE = '3' THEN 'ANOS'
ELSE 'INDETERMINADO' END VIGENCIA, 

CN9_VIGE QTD_VIGENCIA,

CASE WHEN CN9_UNVIGE = '4' THEN 'INDETERMINADO' ELSE SUBSTR(CN9_DTFIM,7,2)||'/'||SUBSTR(CN9_DTFIM,5,2)||'/'||SUBSTR(CN9_DTFIM,1,4) END FIM,

TRIM(
REPLACE(
NVL(
(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '001' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '002' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '003' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '004' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '005' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '006' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '007' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '008' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '009' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '010' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
,
(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '001' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '002' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '003' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '004' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '005' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '006' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '007' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '008' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '009' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '010' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))
)
,'\13\10',' ')
)
COD_OBJETO,

(SELECT ED_DESCRIC FROM SED010 WHERE ED_CODIGO = CN9_X_NAT AND SUBSTR(ED_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2) AND SED010.D_E_L_E_T_=' ') NATUREZA,

CASE WHEN CN9_SITUAC = '01' THEN 'Cancelado'
     WHEN CN9_SITUAC = '02' THEN 'Elaboracao'
     WHEN CN9_SITUAC = '03' THEN 'Emitido'
     WHEN CN9_SITUAC = '04' THEN 'Aprovacao'
     WHEN CN9_SITUAC = '05' THEN 'Vigente'
     WHEN CN9_SITUAC = '06' THEN 'Paralisa'
     WHEN CN9_SITUAC = '07' THEN 'Sol. Finalizacao'
     WHEN CN9_SITUAC = '08' THEN 'Finalizado'
     WHEN CN9_SITUAC = '09' THEN 'Revisao'
     WHEN CN9_SITUAC = '10' THEN 'Revisado'
ELSE ' ' END SITUACAO,


CASE WHEN CNC_CODIGO||CNC_LOJA IS NOT NULL THEN (SELECT A2_NOME FROM SA2010 WHERE A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(A2_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2) AND SA2010.D_E_L_E_T_=' ') 
ELSE (SELECT A1_NOME FROM SA1010 WHERE A1_COD||A1_LOJA = CN9_CLIENT||CN9_LOJACL AND SUBSTR(A1_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2) AND SA1010.D_E_L_E_T_=' ') END CLI_FOR ,

(SELECT /*CASE WHEN E4_TIPO = '1' THEN E4_COND ELSE */E4_DESCRI/* END*/ FROM SE4010 WHERE E4_CODIGO = CN9_CONDPG AND SE4010.D_E_L_E_T_=' ' AND SUBSTR(E4_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2)) COND_PAG,
CN9_VLINI,
CN9_VLATU,
NVL(TRIM(ACB_OBJETO),' ') DIGITALIZADO

FROM CN9010 LEFT JOIN CNC010 ON CNC_FILIAL = CN9_FILIAL AND CNC_NUMERO = CN9_NUMERO AND CNC010.D_E_L_E_T_=' '
LEFT JOIN AC9010 ON AC9_FILENT = CN9_FILIAL AND AC9_ENTIDA = 'CN9' AND TRIM(AC9_CODENT) = TRIM(CN9_NUMERO) AND AC9010.D_E_L_E_T_=' '
LEFT JOIN ACB010 ON AC9_CODOBJ = ACB_CODOBJ AND ACB_FILIAL = AC9_FILIAL AND ACB010.D_E_L_E_T_=' '
WHERE CN9010.D_E_L_E_T_=' ' AND CN9_FILIAL = '11001' AND CN9_SITUAC = '05' ORDER BY CN9_FILIAL, CN9_NUMERO;


SELECT * FROM CNC010 WHERE D_E_L_E_T_=' ';
SELECT * FROM CN9010 WHERE D_E_L_E_T_=' ' ORDER BY CN9_FILIAL;

SELECT * FROM RDY010 WHERE D_E_L_E_T_=' ' AND RDY_CHAVE = '203401' ORDER BY RDY_FILIAL, RDY_CHAVE, RDY_SEQ DESC;
SELECT */*RDY_TEXTO*/ FROM RDY010 WHERE RDY_CAMPO = 'CN9_CODOBJ' AND RDY_TEXTO LIKE '%SERVIÇOS MEDICOS NA ESPECIALIDADE DE INFECTOLOGIA%' AND D_E_L_E_T_=' ';
SELECT * FROM SE4010;

SELECT * FROM SF1010 WHERE F1_FILIAL = '11049' AND F1_DOC = '000001295';

SELECT * FROM SYP010 WHERE D_E_L_E_T_=' ' AND YP_CHAVE = '067909' AND YP_CAMPO = 'CN9_CODOBJ';

SELECT CN9_FILIAL FILIAL,CN9_NUMERO NUMERO,SUBSTR(CN9_DTINIC,7,2)||'/'||SUBSTR(CN9_DTINIC,5,2)||'/'||SUBSTR(CN9_DTINIC,1,4) INICIO,SUBSTR(CN9_DTASSI,7,2)||'/'||SUBSTR(CN9_DTASSI,5,2)||'/'||SUBSTR(CN9_DTASSI,1,4) ASSINATURA,CASE WHEN CN9_UNVIGE = '1' THEN 'DIAS' WHEN CN9_UNVIGE = '2' THEN 'MESES' WHEN CN9_UNVIGE = '3' THEN 'ANOS' ELSE 'INDETERMINADO' END VIGENCIA,CN9_VIGE QTD_VIGENC,SUBSTR(CN9_DTFIM,7,2)||'/'||SUBSTR(CN9_DTFIM,5,2)||'/'||SUBSTR(CN9_DTFIM,1,4) FIM,REPLACE(TRIM( COALESCE((SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '001' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '002' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '003' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '004' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '005' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '006' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '007' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '008' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '009' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(YP_TEXTO) FROM SYP010 WHERE  YP_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND YP_SEQ = '010' AND YP_CHAVE = CN9_CODOBJ AND SUBSTR(YP_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2)),(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '001' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '002' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '003' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '004' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '005' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '006' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '007' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '008' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '009' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  ||(SELECT TRIM(RDY_TEXTO) FROM RDY010 WHERE  RDY_CAMPO = 'CN9_CODOBJ' AND D_E_L_E_T_=' ' AND RDY_SEQ = '010' AND RDY_CHAVE = CN9_CODOBJ AND SUBSTR(RDY_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  )),'\13\10',' ') COD_OBJETO,(SELECT ED_DESCRIC FROM SED010 WHERE  ED_CODIGO = CN9_X_NAT AND SUBSTR(ED_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  NATUREZA,CASE WHEN CN9_SITUAC = '01' THEN 'CANCELADO' WHEN CN9_SITUAC = '02' THEN 'ELABORACAO' WHEN CN9_SITUAC = '03' THEN 'EMITIDO' WHEN CN9_SITUAC = '04' THEN 'APROVACAO' WHEN CN9_SITUAC = '05' THEN 'VIGENTE' WHEN CN9_SITUAC = '06' THEN 'PARALISA' WHEN CN9_SITUAC = '07' THEN 'SOL. FINALIZACAO' WHEN CN9_SITUAC = '08' THEN 'FINALIZADO' WHEN CN9_SITUAC = '09' THEN 'REVISAO' WHEN CN9_SITUAC = '10' THEN 'REVISADO' ELSE ' ' END SITUACAO,CASE WHEN CNC_CODIGO||CNC_LOJA IS NOT NULL THEN (SELECT A2_NOME FROM SA2010 WHERE  A2_COD||A2_LOJA = CNC_CODIGO||CNC_LOJA AND SUBSTR(A2_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2) AND SA2010.D_E_L_E_T_<>'*')  ELSE (SELECT A1_NOME FROM SA1010 WHERE  A1_COD||A1_LOJA = CN9_CLIENT||CN9_LOJACL AND SUBSTR(A1_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2) AND SA1010.D_E_L_E_T_<>'*')  END CLI_FOR,(SELECT E4_DESCRI FROM SE4010 WHERE  E4_CODIGO = CN9_CONDPG AND SE4010.D_E_L_E_T_<>'*' AND SUBSTR(E4_FILIAL,1,2) = SUBSTR(CN9_FILIAL,1,2))  COND_PAG,CN9_VLINI VLR_INICIAL,CN9_VLATU VLR_ATUALIZADO,COALESCE(TRIM(ACB_OBJETO),' ') DIGITALIZADO FROM CN9010 LEFT JOIN CNC010 ON CNC_FILIAL = CN9_FILIAL AND CNC_NUMERO = CN9_NUMERO AND CNC010.D_E_L_E_T_=' ' LEFT JOIN AC9010 ON AC9_FILENT = CN9_FILIAL AND AC9_ENTIDA = 'CN9' AND TRIM(AC9_CODENT) = TRIM(CN9_NUMERO) AND AC9010.D_E_L_E_T_<>'*' LEFT JOIN ACB010 ON AC9_CODOBJ = ACB_CODOBJ AND ACB_FILIAL = AC9_FILIAL AND ACB010.D_E_L_E_T_=' ' WHERE  CN9010.D_E_L_E_T_<>'*' AND CN9_FILIAL >= '11001' AND CN9_FILIAL <= '11001' AND CN9_DTINIC >= '20150101' AND CN9_DTINIC <= '20601231' AND CN9_NUMERO >= '               ' AND CN9_NUMERO <= 'ZZZZZZZZZZZZZZZ' AND CN9_SITUAC = '05'  ORDER BY  CN9_FILIAL, CN9_NUMERO;
