/*--Lista todos os funcionarios.*/
SELECT F.RA_CARGO COD_CARGO, S.Q3_DESCSUM CARGO, F.RA_CODFUNC COD_FUNCAO, J.RJ_DESC FUNCAO, J.RJ_CODCBO CBO,
F.RA_FILIAL FILIAL, F.RA_MAT MATRICULA, F.RA_SITFOLH SITUACAO,
SUBSTR(F.RA_ADMISSA,7,2)||'/'||SUBSTR(F.RA_ADMISSA,5,2)||'/'||SUBSTR(F.RA_ADMISSA,1,4) ADMISSAO,
SUBSTR(F.RA_DEMISSA,7,2)||'/'||SUBSTR(F.RA_DEMISSA,5,2)||'/'||SUBSTR(F.RA_DEMISSA,1,4) DEMISSAO,
F.RA_NOMECMP FUNCIONARIO, F.RA_HRSEMAN HORAS_SEMANA, M.RD_VALOR SALARIO, ROUND(M.RD_VALOR * 0.09,2) ENCARGOS,
M.RD_VALOR + ROUND(M.RD_VALOR * 0.09,2) TOTAL
FROM SRA010 F, SRD010 M, SRJ010 J, SQ3010 S
WHERE F.D_E_L_E_T_ = ' '
AND M.D_E_L_E_T_ = ' '
AND J.D_E_L_E_T_ = ' '
AND S.D_E_L_E_T_ = ' '
AND F.RA_FILIAL = M.RD_FILIAL
AND F.RA_MAT = M.RD_MAT
AND F.RA_CARGO = S.Q3_CARGO
AND F.RA_CODFUNC = J.RJ_FUNCAO
AND F.RA_CATFUNC NOT IN ('A','P')
AND M.RD_PD = '725'
AND M.RD_DATARQ = :DATA
ORDER BY J.RJ_CODCBO, S.Q3_DESCSUM, J.RJ_DESC, M.RD_VALOR, F.RA_HRSEMAN