SELECT 

DISTINCT

RA_FILIAL FILIAL,

1 CONTADOR,

RA_NOMECMP NOME,

RA_MAT MATRICULA,

RJ_CODCBO CBO,

RA_SINDICA COD_SINDICATO,

RA_CIC CPF,

RA_RG RG,

RA_PIS PIS,

CASE WHEN RA_TPCONTR = '1' THEN 'INDETERMINADO' WHEN RA_TPCONTR = '2' THEN 'DETERMINADO' ELSE '' END TIPO_CONTRIBUCAO,

RA_ESTADO ESTADO,

RA_MUNICIP CIDADE,

RA_SEXO SEXO,

RA_CATFUNC CATEGORIA,

RA_SALARIO SALARIO_BASE,

/*
(SELECT SUM(RD_VALOR) FROM SRD010 WHERE RD_HORAS != 0 AND RD_DATARQ = CASE WHEN (SELECT 1 FROM SRD010 WHERE RD_PD = '404' AND RD_MAT = RA_MAT AND RA_FILIAL = RD_FILIAL
AND RD_DATARQ = CASE WHEN TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') = '12' THEN TO_CHAR(ADD_MONTHS(sysdate,-12), 'YYYY') ELSE TO_CHAR(sysdate,'YYYY') END||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM')) = 1 
THEN EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-2), 'MM')
ELSE EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') END
AND RD_MAT = RA_MAT AND RD_PD IN('002','003','005','006','007','008','011','012','016','018','027','070','118','','HE1','HE2') AND RA_FILIAL = RD_FILIAL AND ROWNUM = 1)PROVENTOS,
*/

(SELECT SUM(RD_VALOR) FROM SRD010 WHERE RD_DATARQ = CASE WHEN (SELECT 1 FROM SRD010 WHERE RD_PD = '404' AND RD_MAT = RA_MAT AND RA_FILIAL = RD_FILIAL
AND RD_DATARQ = CASE WHEN TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') = '12' THEN TO_CHAR(ADD_MONTHS(sysdate,-12), 'YYYY') ELSE TO_CHAR(sysdate,'YYYY') END||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM')) = 1 
THEN EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-2), 'MM')
ELSE EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') END AND RD_MAT = RA_MAT AND RD_PD NOT IN ('101','102','129','130','131','161')
AND (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) = '1'
AND (SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) NOT LIKE '%FERIAS%'
AND RA_FILIAL = RD_FILIAL )PROVENTOS,

(SELECT SUM(RD_VALOR) FROM SRD010 WHERE RD_DATARQ = CASE WHEN (SELECT 1 FROM SRD010 WHERE RD_PD = '404' AND RD_MAT = RA_MAT AND RA_FILIAL = RD_FILIAL
AND RD_DATARQ = CASE WHEN TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') = '12' THEN TO_CHAR(ADD_MONTHS(sysdate,-12), 'YYYY') ELSE TO_CHAR(sysdate,'YYYY') END||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM')) = 1 
THEN EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-2), 'MM')
ELSE EXTRACT(YEAR FROM sysdate)||TO_CHAR(ADD_MONTHS(sysdate,-1), 'MM') END AND RD_MAT = RA_MAT AND RD_PD NOT IN ('508','604','499','418','431')
AND (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) = '2'
AND (SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RD_PD AND RV.D_E_L_E_T_=' ' ) NOT LIKE '%FERIAS%'
AND RA_FILIAL = RD_FILIAL )DESCONTOS,

RA_HRSEMAN HORAS_SEMANAL,

RA_HRSMES HORAS_MES,

(SUBSTR(RA_ADMISSA,7,2)||'/'||SUBSTR(RA_ADMISSA,5,2)||'/'||SUBSTR(RA_ADMISSA,1,4)) ADMISSAO,
(SUBSTR(RA_DEMISSA,7,2)||'/'||SUBSTR(RA_DEMISSA,5,2)||'/'||SUBSTR(RA_DEMISSA,1,4)) DEMISSAO,

RJ_DESC FUNCAO,

Q3_DESCSUM CARGO,

SUBSTR(RA_CC,1,5)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA_CC,1,5)||'       ' AND D_E_L_E_T_=' ' AND ROWNUM = 1) LOCAL_CC,

SUBSTR(RA_CC,1,8)||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = SUBSTR(RA_CC,1,8)||'    ' AND D_E_L_E_T_=' ' AND ROWNUM = 1) DEPTO_CC,

RA_CC||'-'||(SELECT CTT_DESC01 FROM CTT010 WHERE CTT_CUSTO = RA_CC AND D_E_L_E_T_=' ' AND ROWNUM = 1) DESC_CC

FROM SRA010 

LEFT JOIN SRJ010 ON RJ_FUNCAO = RA_CODFUNC AND SRJ010.D_E_L_E_T_=' '
LEFT JOIN SQ3010 ON Q3_CARGO = RA_CARGO AND SQ3010.D_E_L_E_T_=' '


WHERE SRA010.D_E_L_E_T_= ' ' /*AND RA_ADMISSA <= :DATA_REFERENCIA AND (RA_DEMISSA >= :DATA_REFERENCIA OR*/AND RA_DEMISSA = ' '/*) */;
