SELECT 
ZC_FILIAL FILIAL, 
ZC_PROJETO COD_PMS,
TRIM(AF8_DESCRI) PROJETO,
ZC_EDT EDT,
ZC_TAREFA COD_TAREFA,
TRIM(AF9_DESCRI) TAREFA,
ZC_PERIODO PERIODO,
ZC_VALOR + ZC_APLICA + ZC_TRANSF VALOR,
ZC_DTINI DATA_INICIO, 
ZC_DTFIM DATA_FIM

FROM SZC010
JOIN AF8010 ON AF8_FILIAL = ZC_FILIAL AND AF8_PROJET = ZC_PROJETO AND AF8010.D_E_L_E_T_<>'*'
JOIN AF9010 ON AF9_FILIAL = ZC_FILIAL AND AF9_PROJET = ZC_PROJETO AND AF9_TAREFA = ZC_TAREFA AND AF9_REVISA = AF8_REVISA AND AF9010.D_E_L_E_T_<>'*'
WHERE SZC010.D_E_L_E_T_<>'*'
AND ZC_FILIAL BETWEEN '11051' AND '11051'
AND ZC_PROJETO BETWEEN '000003' AND '000005'
AND ZC_TAREFA BETWEEN ' ' AND 'ZZZZZ'
AND ZC_DTINI BETWEEN '20180101' AND '20181231'
;



SELECT ZC_FILIAL FILIAL,ZC_PROJETO COD_PMS,
TRIM(AF8_DESCRI) PROJETO,ZC_EDT EDT,ZC_TAREFA COD_TAREFA,TRIM(AF9_DESCRI) TAREFA,ZC_PERIODO PERIODO,
COALESCE(ZC_VALOR + ZC_APLICA + ZC_TRANSF,0) ORCADO,
COALESCE((SELECT ROUND(SUM( COALESCE(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO,0)),2) AS SOMA FROM AJ7010 AJ7 JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL AND SC7.D_E_L_E_T_ <> '*' AND SC7.C7_NUM = AJ7.AJ7_NUMPC AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC AND SC7.C7_X_DTCON >= ZC_DTINI AND SC7.C7_X_DTCON <= ZC_DTFIM WHERE  AJ7.AJ7_FILIAL = ZC_FILIAL AND AJ7.D_E_L_E_T_ <> '*' AND AJ7.AJ7_PROJET = ZC_PROJETO AND AJ7.AJ7_TAREFA = ZC_TAREFA AND (SELECT COUNT(*) FROM SD1010 SD1 WHERE  SD1.D1_FILIAL = AJ7.AJ7_FILIAL AND SD1.D1_PEDIDO = AJ7.AJ7_NUMPC AND SD1.D1_ITEMPC = AJ7.AJ7_ITEMPC AND SD1.D_E_L_E_T_ = ' ' AND TRIM(SD1.D1_X_DTPMS) <> ' ' )  = 0),0)  PEDIDO,
COALESCE((SELECT ROUND(SUM( COALESCE(SD1.D1_QUANT * SD1.D1_VUNIT,0)),2) AS SOMA  FROM  AFN010 AFN LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL AND SD1.D1_DOC = AFN.AFN_DOC AND SD1.D1_SERIE = AFN.AFN_SERIE AND SD1.D1_ITEM = AFN.AFN_ITEM AND SD1.D1_FORNECE = AFN.AFN_FORNEC AND SD1.D1_LOJA = AFN.AFN_LOJA AND SD1.D1_COD = AFN.AFN_COD AND SD1.D_E_L_E_T_ = ' '  WHERE  AFN.AFN_FILIAL = ZC_FILIAL AND AFN.AFN_PROJET = ZC_PROJETO AND AFN.AFN_TAREFA = ZC_TAREFA AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE  AFN010.D_E_L_E_T_ = ' ' AND AFN_FILIAL = SD1.D1_FILIAL)  AND TRIM(SD1.D1_X_DTPMS) <> ' ' AND SD1.D1_X_DTPMS >= ZC_DTINI AND SD1.D1_X_DTPMS <= ZC_DTFIM ),0) NOTA,
COALESCE((SELECT SUM(AFR.AFR_VALOR1)  FROM  AFR010 AFR  WHERE  AFR.AFR_FILIAL = ZC_FILIAL AND AFR.AFR_PROJET = ZC_PROJETO AND AFR.AFR_TAREFA = ZC_TAREFA AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_DATA >= ZC_DTINI AND AFR.AFR_DATA <= ZC_DTFIM),0) TITULO,

COALESCE(ZC_VALOR + ZC_APLICA + ZC_TRANSF,0) -
(COALESCE((SELECT ROUND(SUM( COALESCE(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO,0)),2) AS SOMA FROM AJ7010 AJ7 JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL AND SC7.D_E_L_E_T_ <> '*' AND SC7.C7_NUM = AJ7.AJ7_NUMPC AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC AND SC7.C7_X_DTCON >= ZC_DTINI AND SC7.C7_X_DTCON <= ZC_DTFIM WHERE  AJ7.AJ7_FILIAL = ZC_FILIAL AND AJ7.D_E_L_E_T_ <> '*' AND AJ7.AJ7_PROJET = ZC_PROJETO AND AJ7.AJ7_TAREFA = ZC_TAREFA AND (SELECT COUNT(*) FROM SD1010 SD1 WHERE  SD1.D1_FILIAL = AJ7.AJ7_FILIAL AND SD1.D1_PEDIDO = AJ7.AJ7_NUMPC AND SD1.D1_ITEMPC = AJ7.AJ7_ITEMPC AND SD1.D_E_L_E_T_ = ' ' AND TRIM(SD1.D1_X_DTPMS) <> ' ' )  = 0),0) +
COALESCE((SELECT ROUND(SUM( COALESCE(SD1.D1_QUANT * SD1.D1_VUNIT,0)),2) AS SOMA FROM AFN010 AFN LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL AND SD1.D1_DOC = AFN.AFN_DOC AND SD1.D1_SERIE = AFN.AFN_SERIE AND SD1.D1_ITEM = AFN.AFN_ITEM AND SD1.D1_FORNECE = AFN.AFN_FORNEC AND SD1.D1_LOJA = AFN.AFN_LOJA AND SD1.D1_COD = AFN.AFN_COD AND SD1.D_E_L_E_T_ = ' '  WHERE  AFN.AFN_FILIAL = ZC_FILIAL AND AFN.AFN_PROJET = ZC_PROJETO AND AFN.AFN_TAREFA = ZC_TAREFA AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE  AFN010.D_E_L_E_T_ = ' ' AND AFN_FILIAL = SD1.D1_FILIAL)  AND TRIM(SD1.D1_X_DTPMS) <> ' ' AND SD1.D1_X_DTPMS >= ZC_DTINI AND SD1.D1_X_DTPMS <= ZC_DTFIM ),0) +

COALESCE((SELECT SUM(AFR.AFR_VALOR1) FROM AFR010 AFR  WHERE  AFR.AFR_FILIAL = ZC_FILIAL AND AFR.AFR_PROJET = ZC_PROJETO AND AFR.AFR_TAREFA = ZC_TAREFA AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_DATA >= ZC_DTINI AND AFR.AFR_DATA <= ZC_DTFIM),0)) SALDO,
TO_DATE(ZC_DTINI,'YYYYMMDD') DATA_INICIO,
TO_DATE(ZC_DTFIM,'YYYYMMDD') DATA_FIM
;
SELECT ZC_FILIAL FILIAL,ZC_PROJETO COD_PMS,TRIM(AF8_DESCRI) PROJETO,ZC_EDT EDT,ZC_TAREFA COD_TAREFA,TRIM(AF9_DESCRI) TAREFA,ZC_PERIODO PERIODO,COALESCE(ZC_VALOR + ZC_APLICA + ZC_TRANSF,0) ORCADO,COALESCE((SELECT ROUND(SUM( COALESCE(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO,0)),2) AS SOMA FROM AJ7010 AJ7 JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL AND SC7.D_E_L_E_T_ <> '*' AND SC7.C7_NUM = AJ7.AJ7_NUMPC AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC AND SC7.C7_X_DTCON >= ZC_DTINI AND SC7.C7_X_DTCON <= ZC_DTFIM WHERE  AJ7.AJ7_FILIAL = ZC_FILIAL AND AJ7.D_E_L_E_T_ <> '*' AND AJ7.AJ7_PROJET = ZC_PROJETO AND AJ7.AJ7_TAREFA = ZC_TAREFA AND (SELECT COUNT(*) FROM SD1010 SD1 WHERE  SD1.D1_FILIAL = AJ7.AJ7_FILIAL AND SD1.D1_PEDIDO = AJ7.AJ7_NUMPC AND SD1.D1_ITEMPC = AJ7.AJ7_ITEMPC AND SD1.D_E_L_E_T_ = ' ' AND TRIM(SD1.D1_X_DTPMS) <> ' ' )  = 0),0) PEDIDO,COALESCE((SELECT ROUND(SUM( COALESCE(SD1.D1_QUANT * SD1.D1_VUNIT,0)),2) AS SOMA  FROM  AFN010 AFN LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL AND SD1.D1_DOC = AFN.AFN_DOC AND SD1.D1_SERIE = AFN.AFN_SERIE AND SD1.D1_ITEM = AFN.AFN_ITEM AND SD1.D1_FORNECE = AFN.AFN_FORNEC AND SD1.D1_LOJA = AFN.AFN_LOJA AND SD1.D1_COD = AFN.AFN_COD AND SD1.D_E_L_E_T_ = ' '  WHERE  AFN.AFN_FILIAL = ZC_FILIAL AND AFN.AFN_PROJET = ZC_PROJETO AND AFN.AFN_TAREFA = ZC_TAREFA AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE  AFN010.D_E_L_E_T_ = ' ' AND AFN_FILIAL = SD1.D1_FILIAL)  AND TRIM(SD1.D1_X_DTPMS) <> ' ' AND SD1.D1_X_DTPMS >= ZC_DTINI AND SD1.D1_X_DTPMS <= ZC_DTFIM ),0) NOTA,COALESCE((SELECT SUM(AFR.AFR_VALOR1)  FROM  AFR010 AFR  WHERE  AFR.AFR_FILIAL = ZC_FILIAL AND AFR.AFR_PROJET = ZC_PROJETO AND AFR.AFR_TAREFA = ZC_TAREFA AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_DATA >= ZC_DTINI AND AFR.AFR_DATA <= ZC_DTFIM),0) TITULO,COALESCE(ZC_VALOR + ZC_APLICA + ZC_TRANSF,0) - ( COALESCE((SELECT ROUND(SUM( COALESCE(CASE WHEN C7_RESIDUO = 'S' THEN C7_QUJE ELSE SC7.C7_QUANT END * SC7.C7_PRECO,0)),2) AS SOMA FROM AJ7010 AJ7 JOIN SC7010 SC7 ON SC7.C7_FILIAL = AJ7.AJ7_FILIAL AND SC7.D_E_L_E_T_ <> '*' AND SC7.C7_NUM = AJ7.AJ7_NUMPC AND SC7.C7_ITEM = AJ7.AJ7_ITEMPC AND SC7.C7_X_DTCON >= ZC_DTINI AND SC7.C7_X_DTCON <= ZC_DTFIM WHERE  AJ7.AJ7_FILIAL = ZC_FILIAL AND AJ7.D_E_L_E_T_ <> '*' AND AJ7.AJ7_PROJET = ZC_PROJETO AND AJ7.AJ7_TAREFA = ZC_TAREFA AND (SELECT COUNT(*) FROM SD1010 SD1 WHERE  SD1.D1_FILIAL = AJ7.AJ7_FILIAL AND SD1.D1_PEDIDO = AJ7.AJ7_NUMPC AND SD1.D1_ITEMPC = AJ7.AJ7_ITEMPC AND SD1.D_E_L_E_T_ = ' ' AND TRIM(SD1.D1_X_DTPMS) <> ' ' )  = 0),0) +  COALESCE((SELECT ROUND(SUM( COALESCE(SD1.D1_QUANT * SD1.D1_VUNIT,0)),2) AS SOMA  FROM  AFN010 AFN LEFT JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFN.AFN_FILIAL AND SD1.D1_DOC = AFN.AFN_DOC AND SD1.D1_SERIE = AFN.AFN_SERIE AND SD1.D1_ITEM = AFN.AFN_ITEM AND SD1.D1_FORNECE = AFN.AFN_FORNEC AND SD1.D1_LOJA = AFN.AFN_LOJA AND SD1.D1_COD = AFN.AFN_COD AND SD1.D_E_L_E_T_ = ' '  WHERE  AFN.AFN_FILIAL = ZC_FILIAL AND AFN.AFN_PROJET = ZC_PROJETO AND AFN.AFN_TAREFA = ZC_TAREFA AND AFN.D_E_L_E_T_ = ' ' AND SD1.D1_DOC IN (SELECT AFN_DOC FROM AFN010 WHERE  AFN010.D_E_L_E_T_ = ' ' AND AFN_FILIAL = SD1.D1_FILIAL)  AND TRIM(SD1.D1_X_DTPMS) <> ' ' AND SD1.D1_X_DTPMS >= ZC_DTINI AND SD1.D1_X_DTPMS <= ZC_DTFIM ),0) +  COALESCE((SELECT SUM(AFR.AFR_VALOR1)  FROM  AFR010 AFR  WHERE  AFR.AFR_FILIAL = ZC_FILIAL AND AFR.AFR_PROJET = ZC_PROJETO AND AFR.AFR_TAREFA = ZC_TAREFA AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_DATA >= ZC_DTINI AND AFR.AFR_DATA <= ZC_DTFIM),0)) SALDO,TO_DATE(ZC_DTINI,'YYYYMMDD') DATA_INICIO,TO_DATE(ZC_DTFIM,'YYYYMMDD') DATA_FIM FROM SZC010 JOIN AF8010 ON AF8_FILIAL = ZC_FILIAL AND AF8_PROJET = ZC_PROJETO AND AF8010.D_E_L_E_T_<>'*' JOIN AF9010 ON AF9_FILIAL = ZC_FILIAL AND AF9_PROJET = ZC_PROJETO AND AF9_TAREFA = ZC_TAREFA AND AF9_REVISA = AF8_REVISA AND AF9010.D_E_L_E_T_<>'*' WHERE  SZC010.D_E_L_E_T_<>'*' AND ZC_FILIAL BETWEEN '11001' AND '11001' AND ZC_PROJETO BETWEEN '      ' AND 'ZZZZZZ' AND ZC_TAREFA BETWEEN '     ' AND 'ZZZZZ' AND ZC_DTINI BETWEEN '20150101' AND '20201231' ;


