SELECT 
E5_FILIAL FILIAL, 
TO_DATE(E5_DATA,'YYYYMMDD') BAIXA, 
E5_TIPO TIPO,
E5_VALOR VALOR,
E5_NATUREZ COD_NAT,
ED_DESCRIC NATUREZA,
E5_BANCO BANCO,
E5_AGENCIA AGENCIA,
E5_CONTA CONTA,
E5_BENEF BENEFICIARIO,
E5_HISTOR HISTORICO,
E5_PREFIXO PREFIXO,
E5_NUMERO NUMERO,
E5_PARCELA PARCELA,
AF8_DESCRI PROJETO_CONTA
FROM SE5010 JOIN AF8010 ON TRIM(AF8_X_BANK)||TRIM(AF8_X_AGEN)||TRIM(AF8_X_CONT) = TRIM(E5_BANCO)||TRIM(E5_AGENCIA)||TRIM(E5_CONTA) AND AF8010.D_E_L_E_T_=' '
JOIN SED010 ON ED_CODIGO = E5_NATUREZ AND SUBSTR(E5_FILIAL,1,2) = SUBSTR(ED_FILIAL,1,2) AND SED010.D_E_L_E_T_=' '
WHERE 
E5_DATA BETWEEN :DATA_INICIO AND :DATA_FIM
AND SE5010.D_E_L_E_T_=' '
AND (E5_FILIAL||E5_PREFIXO||E5_NUMERO||E5_FORNECE||E5_LOJA NOT IN (SELECT AFN_FILIAL||AFN_SERIE||AFN_DOC||AFN_FORNEC||AFN_LOJA FROM AFN010 WHERE AFN010.D_E_L_E_T_=' ')
OR E5_FILIAL||E5_PREFIXO||E5_NUMERO||E5_FORNECE||E5_LOJA NOT IN (SELECT AFR_FILIAL||AFR_PREFIX||AFR_NUM||AFR_FORNEC||AFR_LOJA FROM AFR010 WHERE AFR010.D_E_L_E_T_=' '))
AND E5_MOEDA NOT IN ('M1','TB') AND E5_TIPODOC IN('VL','BA') AND E5_NATUREZ NOT IN ('NATMOVP','NATMOVR') AND E5_TIPO = 'NF'
AND (E5_RECONC = 'x' OR E5_LOTE IN (SELECT B.E5_LOTE FROM SE5010 B WHERE B.E5_LOTE = SE5010.E5_LOTE AND B.E5_RECONC = 'x' AND B.D_E_L_E_T_=' ' AND B.E5_DATA BETWEEN :DATA_INICIO AND :DATA_FIM AND B.E5_NUMERO = ' '))
ORDER BY E5_FILIAL, E5_BANCO, E5_AGENCIA, E5_CONTA, E5_VALOR
;

SELECT * FROM SE5010 WHERE E5_LOTE <> ' ' AND E5_RECONC = 'x' AND E5_DATA >= '20180101' ;

