SELECT DISTINCT R0_FILIAL FILIAL, R0_MAT MATRICULA, RA_NOMECMP NOME, RA_ENDEREC ENDERECO, RA_COMPLEM COMPLEMENTO, RA_BAIRRO BAIRRO, RA_MUNICIP MUNICIPIO, RA_ESTADO ESTADO, RA_CEP CEP FROM SR0010 JOIN SRA010 ON RA_MAT = R0_MAT AND RA_FILIAL = R0_FILIAL AND SRA010.D_E_L_E_T_=' '
WHERE SR0010.D_E_L_E_T_=' ' AND RA_DEMISSA = ' ' AND RA_FILIAL IN ('11045','11047','11049') ORDER BY R0_FILIAL, R0_MAT
;