SELECT 

RC.RC_FILIAL FILIAL,
RC.RC_MAT MATRICULA,
RA.RA_NOMECMP NOME,

(SELECT RJ_DESC FROM SRJ010 WHERE RJ_FUNCAO = RA_CODFUNC AND D_E_L_E_T_=' ') FUNCAO,

(SELECT SQ3010.Q3_DESCSUM FROM SQ3010 WHERE Q3_CARGO = RA_CARGO AND D_E_L_E_T_=' ') CARGO,

CASE WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RC_PD AND RV.D_E_L_E_T_=' ' )= '2' THEN (RC.RC_VALOR)*-1 ELSE (RC.RC_VALOR) END VALOR,
RC_PD COD_VERBA,
(SELECT RV_DESC FROM SRV010 RV WHERE RV.RV_COD = RC_PD AND RV.D_E_L_E_T_=' ' )VERBA,

CASE WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RC_PD AND RV.D_E_L_E_T_=' ' ) = '1' THEN 'PROVENTO'
WHEN (SELECT RV_TIPOCOD FROM SRV010 RV WHERE RV.RV_COD = RC_PD AND RV.D_E_L_E_T_=' ' )= '2' THEN 'DESCONTO' ELSE 'BASE' END TIPO_VERBA,

SUBSTR(RC.RC_DATA,7,2)||'/'||SUBSTR(RC.RC_DATA,5,2)||'/'||SUBSTR(RC.RC_DATA,1,4) DATA_PGTO

FROM RC011502 RC INNER JOIN SRA010 RA ON RA.RA_MAT = RC.RC_MAT AND RA.RA_FILIAL = RC.RC_FILIAL

WHERE RA.D_E_L_E_T_=' ' /*AND RC.RC_PD IN ('403','405','427','495','500','520','444','624','621')*/ AND RC.D_E_L_E_T_=' ' /*AND RC.RC_DATARQ = '201502'*/ AND RC.RC_FILIAL = '11001' 
AND RA.RA_CATFUNC != 'A' ORDER BY RC.RC_MAT;



/* ========================== AFASTAMENTOS ======================================================= */
SELECT AF.R8_FILIAL FILIAL, AF.R8_MAT MATRICULA, 
(SELECT RA_NOMECMP FROM SRA010 WHERE RA_MAT = R8_MAT AND RA_FILIAL = R8_FILIAL AND SRA010.D_E_L_E_T_=' ') FUNCIONARIO,

AF.R8_TIPO COD_AFASTAMENTO, X5.X5_DESCRI AFASTAMENTO, AF.R8_PD VERBA, 

SUBSTR(AF.R8_DATAINI,7,2) DIA_INICIO,
SUBSTR(AF.R8_DATAINI,5,2) MES_INICIO,
SUBSTR(AF.R8_DATAINI,1,4) ANO_INICIO,

SUBSTR(AF.R8_DATAINI,7,2)||'/'||SUBSTR(AF.R8_DATAINI,5,2)||'/'||SUBSTR(AF.R8_DATAINI,1,4) DATA_INICIO, 
SUBSTR(AF.R8_DATAFIM,7,2)||'/'||SUBSTR(AF.R8_DATAFIM,5,2)||'/'||SUBSTR(AF.R8_DATAFIM,1,4) DATA_FINAL,

AF.R8_AFARAIS 

FROM SR8010 AF JOIN SX5010 X5 ON X5_TABELA = '30' AND X5.X5_CHAVE = AF.R8_TIPO ;/*AND AF.R8_TIPO IN ('O','P') AND AF.R8_DATAINI > '20150228' ORDER BY AF.R8_FILIAL, AF.R8_TIPO;*/

