SELECT I_MODULE 'MODULE'
    ,F_FUNCTION 'FUNCTION'
    ,I18N1.N_DESC 'PT_NAME'
    ,I18N2.N_DESC 'SPA_NAME'
    ,I18N3.N_DESC 'ENG_NAME'
FROM MPMENU_MENU MPN
INNER JOIN MPMENU_ITEM MPI ON I_ID_MENU = M_ID
    AND MPI.D_E_L_E_T_ = ' '
LEFT JOIN MPMENU_FUNCTION MPF ON F_ID = I_ID_FUNC
    AND MPF.D_E_L_E_T_ = ' '
INNER JOIN MPMENU_I18N I18N1 ON I18N1.N_PAREN_ID = I_ID
    AND I18N1.N_LANG = '1'
    AND I18N1.D_E_L_E_T_ = ' '
INNER JOIN MPMENU_I18N I18N2 ON I18N2.N_PAREN_ID = I_ID
    AND I18N2.N_LANG = '2'
    AND I18N2.D_E_L_E_T_ = ' '
INNER JOIN MPMENU_I18N I18N3 ON I18N3.N_PAREN_ID = I_ID
    AND I18N3.N_LANG = '3'
    AND I18N3.D_E_L_E_T_ = ' '
LEFT JOIN MPMENU_KEY_WORDS KW1 ON KW1.K_ID_ITEM = I_ID
    AND KW1.K_LANG = '1'
    AND KW1.D_E_L_E_T_ = ' '
LEFT JOIN MPMENU_KEY_WORDS KW2 ON KW2.K_ID_ITEM = I_ID
    AND KW2.K_LANG = '2'
    AND KW2.D_E_L_E_T_ = ' '
LEFT JOIN MPMENU_KEY_WORDS KW3 ON KW3.K_ID_ITEM = I_ID
    AND KW3.K_LANG = '3'
    AND KW3.D_E_L_E_T_ = ' '
WHERE F_FUNCTION IS NOT NULL
ORDER BY I_MODULE
    ,I_ORDER